### ISSUE TITLE
Increase nameIDs limit in `drop-mac-names` & `drop-superfluous-mac-names` in `fix.py`

### ISSUE THREAD

**Issue by kalapi** [googlefonts/gftools#1035]
Is there a reason for the upper limit of the nameID values to be 255 (in both `drop-mac-names` and `drop-superfluous-mac-names`?

I'm processing several fonts where the the nameIDs in VFs exceed that limit. 

![Screenshot 2024-09-27 at 7 11 50 PM](https://github.com/user-attachments/assets/6c91e642-3500-4fa3-a129-4c985e7848b9)

https://github.com/googlefonts/gftools/blob/a2b3549862d9bc7f62b09f84f6c87bc75da14bae/Lib/gftools/fix.py#L688

**Comment by simoncozens** [comment]
Yeah, that's a bug.
