### ISSUE TITLE
malloc failure when running gftools-autohint

### ISSUE THREAD

**Issue by cmyr** [googlefonts/gftools#1056]
I am running into an occasional failure when running gftools builder on some of the fonts in the [Soft Type Yarndings](https://github.com/scfried/soft-type-yarndings) family.

The actual issue is with `gftools-autohint`; with the binary included below, running

`$ gftools-autohint -o hmm.ttf Yarndings20-Regular.ttf`

will intermittently fail, with the following lovely output:

```
Python(2217,0x20798cf40) malloc: Heap corruption detected, free list is damaged at 0x600003f63860
*** Incorrect guard value: 13259081092435094325
Python(2217,0x20798cf40) malloc: *** set a breakpoint in malloc_error_break to debug
[1]    2217 abort      gftools-autohint -o yardings_out/auto.ttf yardings_out/Yarndings20-Regular.tt
```

(you might need to run this command ~10 times to see a failure)

I'm on macOS 14.6.1, on an M1 mac; it's possible this crash is environment specific.

[Yarndings20-Regular.ttf.zip](https://github.com/user-attachments/files/17602729/Yarndings20-Regular.ttf.zip)

**Comment by simoncozens** [comment]
gftools-autohint is a thin wrapper around the [ttfautohint-py](https://github.com/fonttools/ttfautohint-py) library; suggest asking Cosimo there.

**Comment by anthrotype** [comment]
hm I cannot reproduce on my M1 macbook pro. ttfautohint-py uses ctypes to wrap the libttfautohint library, it has to do a bunch of manual memory management so there's probably a bug hiding there

**Comment by anthrotype** [comment]
actually I _was_ able to reproduce just now, I had to retry a few times. I'll track it down with a debugger
