### ISSUE TITLE
gftools-what-subsets – ImportError: No module named gftools.util

### ISSUE THREAD

**Issue by thundernixon** [googlefonts/gftools#130]
I'm attempting to check the coverage of a TTF with the `what-subsets` tool.

However, it has a print error when installed with `pip install -U git+https://github.com/googlefonts/gftools` ([line 41](https://github.com/googlefonts/gftools/blob/589dad3dd95fee1f57292919a52aa4fe95c179cd/bin/gftools-what-subsets.py#L41) is missing parentheses) because it needs to edited to work in a python3 environment.

_However_ when I try to install my local repo of gftools with `pip install -e <local_gftools_path>` (so I can fix the print issue), I get the following error on usage:

```bash
(venv)▶ gftools what-subsets ofl/aladin/Aladin-Regular.ttf # any font; doesn't matter
Traceback (most recent call last):
  File "/Users/stephennixon/type-repos/google-font-repos/gftools/bin/gftools-what-subsets.py", line 24, in <module>
    from gftools.util import google_fonts as fonts
ImportError: No module named gftools.util
```

Strangely, when I use `gftools add-font` – which contains the exact same import line as `what-subsets` – `add-font` works just as I expect it to.

I've tried dumb fixes line copy-pasting all the imports from `add-font` into `what-subsets`. I've also tried installing gftools into a python2 virtual environment, but this has all sorts of other installation issues (though, I can do this more if anyone really thinks it's my best option).

What else might I try to solve this import error?

**Comment by felipesanches** [comment]
I'd like to take a look at this soon

**Comment by simoncozens** [comment]
This appears to have been fixed.
