### ISSUE TITLE
use argparse on the list-variable-source script and remove hardcoded directory

### ISSUE THREAD

**Issue by felipesanches** [googlefonts/gftools#14]
originally requested at:
https://github.com/googlefonts/fontbakery/issues/1414

@felipesanches said:

@m4rc1e We need to use argparse on bin/fontbakery-list-variable-source.py and pass the following hardcoded directory as a command line argument:

```
parent_dir = '/Users/marc/Documents/googlefonts/manual_font_cleaning/'
```

**Comment by felipesanches** [comment]
To be done after merging #10

**Comment by felipesanches** [comment]
@felipesanches said:

This looks similar to https://github.com/googlefonts/fontbakery/issues/1416

**Comment by felipesanches** [comment]
Also use arparse on `bin/gftools-ots.py`

**Comment by simoncozens** [comment]
This script is now deprecated in #638, which moved everything to argparse anyway.
