### ISSUE TITLE
Support multiple axes in fix-vf-meta

### ISSUE THREAD

**Issue by thundernixon** [googlefonts/gftools#144]
I'm trying to update [the Inter PR to google/fonts](https://github.com/google/fonts/pull/1908), and it's just been announced that GF now supports all registered axes.

Work is happening in https://github.com/thundernixon/inter/tree/qa/misc/googlefonts-qa, with my latest changes at https://github.com/thundernixon/inter/commit/abfec950a8c2e603aee7674a416b91f419109645

Currently, `fix-vf-meta` does not work for a multi-axis family. I know this will take some work to change, but with the update to Google Fonts, I think this is probably a pretty high priority to update.

Here's the current issue:

```
Dumping "/Users/stephennixon/type-repos/google-font-repos/inter/build/fonts/var/Inter.var.ttf" to "/Users/stephennixon/type-repos/google-font-repos/inter/build/fonts/var/Inter.var.ttx"...
Dumping 'head' table...
Traceback (most recent call last):
  File "/Users/stephennixon/type-repos/google-font-repos/inter/build/venv3/bin/gftools-fix-vf-meta.py", line 297, in <module>
    main()
  File "/Users/stephennixon/type-repos/google-font-repos/inter/build/venv3/bin/gftools-fix-vf-meta.py", line 290, in main
    create_stat_table(ttfont)
  File "/Users/stephennixon/type-repos/google-font-repos/inter/build/venv3/bin/gftools-fix-vf-meta.py", line 131, in create_stat_table
    raise Exception('VFs with more than one axis are currently '
Exception: VFs with more than one axis are currently not supported.
```

**Comment by davelab6** [comment]
@rsheeter cc

**Comment by weiweihuanghuang** [comment]
+1

**Comment by arialcrime** [comment]
Are there any updates on the state of the multi-axis update?

I’m running into a related issue here at the moment where fix-vf-meta.py tries to get default values in line [163](https://github.com/googlefonts/gftools/blob/master/bin/gftools-fix-vf-meta.py#L163), but (for obvious reasons) not finding the correct entries.

**Comment by m4rc1e** [comment]
@arialcrime I've been thinking of deprecating this script. The script now only builds a VF's STAT table. Imo, using https://github.com/daltonmaag/statmake is a better idea. It does require understanding the STAT table spec though.

**Comment by sursly** [comment]
Checking in to an update here. I'm also using statmake currently but would love it if this gftool was fixed for 2 or 3 axis fonts.

**Comment by simoncozens** [comment]
This tool has gone; gftools-gen-stat, axisregistry.build_stat or the gftools-builder all take care of STAT tables now.
