### ISSUE TITLE
"gftools qa -pr https://github.com/" doesn't download metadata files. (download_fonts_in_pr)

### ISSUE THREAD

**Issue by graphicore** [googlefonts/gftools#157]
This means the TravisCI bot is blind for all metadata checks concerned with `DESCRIPTION.en_us.html`, `METADATA.pb`, `OFL.txt`.

This lead to googlefonts/fontbakery#2675

Deeper investigation is in my comment: https://github.com/googlefonts/fontbakery/issues/2675#issuecomment-546159444

**Comment by m4rc1e** [comment]
Fixed in #158
