### ISSUE TITLE
add-font: METADATA.pb encode/decode issues

### ISSUE THREAD

**Issue by m4rc1e** [googlefonts/gftools#161]
I just merged a family with the following designer name

`designer: "Jos\303\251 Mar\303\255a Ribagorda, Octavio Pardo"`

when it should be `Jose Maria Ribagorda & Octavio Pardo`.

I'll look into why it's doing this next week.

cc @davelab6

**Comment by graphicore** [comment]
I believe it's good, see: https://github.com/google/fonts/pull/2238#discussion_r344287249

> That's serialized by the python protocol buffers library, it would be interesting if the correct string is in the parsed result.

> Looks good to me:
>
> ```
> In [1]: import gftools.fonts_public_pb2 as fonts_pb2
> In [2]: from google.protobuf import text_format
> In [3]: with open('METADATA.pb') as f: pbtxt = f.read()
> In [4]: msg = fonts_pb2.FamilyProto()
> In [5]: text_format.Merge(pbtxt, msg)
> In [6]: print(msg.designer)
> José María Ribagorda, Octavio Pardo
> ```

**Comment by vv-monsalve** [comment]
> I believe it's good, see: [google/fonts#2238 (comment)](https://github.com/google/fonts/pull/2238#discussion_r344287249)
> 
> > That's serialized by the python protocol buffers library, it would be interesting if the correct string is in the parsed result.
> 
> > Looks good to me:
> > ```
> > In [1]: import gftools.fonts_public_pb2 as fonts_pb2
> > In [2]: from google.protobuf import text_format
> > In [3]: with open('METADATA.pb') as f: pbtxt = f.read()
> > In [4]: msg = fonts_pb2.FamilyProto()
> > In [5]: text_format.Merge(pbtxt, msg)
> > In [6]: print(msg.designer)
> > José María Ribagorda, Octavio Pardo
> > ```

Indeed. It is a Spanish name and must include those acute marks.

**Comment by simoncozens** [comment]
I think there is no issue here, then.
