### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by weiweihuanghuang** [googlefonts/gftools#165]
I installed gftools in a Python3 venv, but I get this error when I tried to simply run `gftools`:
```
-bash: /Users/myusername/Type Design Work/VF Test/env/bin/gftools: /Users/myusername/Type: bad interpreter: No such file or directory
```

I realise it's because of the space in the path, is there anyway to still keep it running without changing the path of the env ?

**Comment by m4rc1e** [comment]
We're still working on full py3 support. For the time being you want to install these tools using the following commands:

```
python -m venv venv
source venv/bin/activate
pip install git+https://www.github.com/googlefonts/tools
```

**Comment by weiweihuanghuang** [comment]
I'm still running into that issue with the fact that there's a space in the path of gftools, is there no way around it except moving it into a path without a space?

**Comment by chrissimpkins** [comment]
Can you run it with an absolute path to the venv installed executable surrounded by quotes?

```
$ "/Users/myusername/Type Design Work/VF Test/env/bin/gftools" [OPTIONS] [ARGS]
```

**Comment by weiweihuanghuang** [comment]
No strangely can't

**Comment by chrissimpkins** [comment]
If you clone the repository and add the [`bin`](https://github.com/googlefonts/gftools/tree/master/bin) directory to your system PATH, you can call the scripts directly with their full module name on the command line:

```
$ gftools-fix-dsig.py [ARGS]
```

**Comment by weiweihuanghuang** [comment]
I found that if I just escaped the spaces in the env path for `VIRTUAL_ENV=` in `env/bin/activate` it solved it
