### ISSUE TITLE
gftools-fix-glyphs.py

### ISSUE THREAD

**Issue by felipesanches** [googlefonts/gftools#18]
Originally posted at https://github.com/googlefonts/fontbakery/issues/754

@davelab6 and @m4rc1e said:

Per https://github.com/googlefonts/fontbakery/blob/master/BRIEF.md#4-source-management there should be a `.glyphs` file checker. 

Generally binaries exported from Glyphs are good quality, but some of the application's defaults are not what we want, and it is easy to set them to what we do want with Custom Parameters. 

The changes I've requested/made so far are:
- [x] Font copyright set correctly
- [ ] Font vendorID set correctly
- [x] Font fsType, set to “not set” or "Installable" (empty)
- [x] Font license set correctly
- [x] Font licenseURL set correctly
- [x] Masters (or instances) 8 Vertical Metrics set correctly
- [x] Instance ExtraLight weightClass set to 275
- [ ] Instances italicAngle set to 0, if the master/instance slant value is not 0
- [x] Instance named Regular (400) for families with a single instance
- [x] Instance Bold style linking set for families with a 400 and 700 instance
- [x] Source master and instance interpolation values match the stem widths? ([reference](https://github.com/googlefonts/gf-docs/commit/805751608bd166632d73a6f7da392d3ee1be34eb))

It may be possible to detect and autofix these with https://github.com/googlei18n/glyphs2ufo/ but operating on the file as a plain text file will probably work well enough for detection, and autofixing can be postponed.

See the rest of the discussion at https://github.com/googlefonts/fontbakery/issues/754

**Comment by felipesanches** [comment]
If anything else still do be done here, then it will be after merging #10

**Comment by simoncozens** [comment]
I'm not sure if this is in scope any more; we abandoned the idea of fixing glyphs files. Maybe it's something worth coming back to one day, but a better approach is to give people templates with the correct values. Please reopen if I've misunderstood.
