### ISSUE TITLE
Upstream repo cookie cutter

### ISSUE THREAD

**Issue by m4rc1e** [googlefonts/gftools#183]
Once we have the spec/docs finished, it may be nice to provide an interactive cookie cutter to help create upstream font repos. The cutter could even take care of making a build script, installing dependencies etc. This should lower the barrier to entry.

This is merely an idea, not something we should rush off and create.

https://cookiecutter.readthedocs.io/

**Comment by laerm0** [comment]
I've had seen some requests for this, most recently from @yosiasz.

**Comment by yosiasz** [comment]
Most of the stuff I did was reverse engineering, based on Rubik and some East Indian fonts etc. Trial and error.  This would be super helpful!

- How do you create .nam files?
- Is there there a centralized location for seed files such as .nam files
- What google font tools do I need to get a basic font etc (right now there are a lot and bit daunting)

Thanks!

**Comment by yosiasz** [comment]
Going to build a js cli to help other Sub Saharians.

https://github.com/yosiasz/font-cli

**Comment by graphicore** [comment]
Also related but dated: https://github.com/graphicore/fontdev-adhoc-dump/tree/master/g_font_repositories

**Comment by simoncozens** [comment]
We did this with https://github.com/googlefonts/googlefonts-project-template
