### ISSUE TITLE
Add new fonts: "ZoomlaCusong"

### ISSUE THREAD

**Issue by zoomla** [googlefonts/gftools#185]
We are a Chinese font manufacturer, font brand name: z01, and was included in:https://docs.microsoft.com/en-us/typography/vendors/#z

We developed ZoomlaCusong fonts,There are CJK and Latin, and it is licenses are SIL Open Font License OFL 1.1.
We want to contribute this font add to Google Font.
GitHub repo: https://github.com/z01font/ZoomlaCusong
Releases: https://github.com/z01font/ZoomlaCusong/releases

Thanks.

**Comment by felipesanches** [comment]
@davelab6 / @RosaWagner can any of you migrate this issue to the **google/fonts** issue tracker? (I do not seem to have the rights to do so)

**Comment by simoncozens** [comment]
I don't think we can, but we can do it the slow way...
