### ISSUE TITLE
`.gitignore` ignores Lib on macOS

### ISSUE THREAD

**Issue by khaledhosny** [googlefonts/gftools#189]
The default macOS file system is case-insensitive, and the `.gitignore` file has an entry for `lib/` which causes `Lib` to be ignored as well, and trying to `git add` any file under gives this message:

```
The following paths are ignored by one of your .gitignore files:
Lib
hint: Use -f if you really want to add them.
hint: Turn this message off by running
hint: "git config advice.addIgnoredFile false"
```

**Comment by simoncozens** [comment]
This was fixed in 17ca2bf.
