### ISSUE TITLE
fix-isfixedpitch needs update for Panose setting

### ISSUE THREAD

**Issue by tphinney** [googlefonts/gftools#195]
Currently, fix-isfixedpitch always sets `OS/2.panose.bProportion` to 9, and ignores any existing Panose settings.

However, as discussed elsewhere (https://github.com/googlefonts/gf-docs/blob/master/Spec/README.md#monospace-fonts) —surprise!—the meaning of bProportion depends on the value of bFamilyType:
- If `OS/2.panose.bFamilyType` is 2 (Latin Text), set `OS/2.panose.bProportion` to 9.
- If `OS/2.panose.bFamilyType` is 3 (Latin Script), set `OS/2.panose.bProportion` to 3.
- if `OS/2.panose.bFamilyType` is 5 (Latin Picture), set `OS/2.panose.bProportion` to 3.

No question that bFamilyType of 2 is massively more common, but 3 and 5 do come up once in a while.

Also, if bFamilyType is ≠2 (including 0 or 1), then bProportion=9 would be invalid.

I propose:

fix-isfixedpitch needs to check for existing Panose values! 
- If bFamilyType is _already set to 2, 3 or 5_, set bProportion to 9, 3 or 3, respectively.
- If bFamilyType is 0 (which would be the case if Panose was blank), set bFamilyType to 2  in addition to setting bProportion to 9
- If bFamilyType is anything else, then bProportion does not need to be adjusted for fixed pitch.

One can also imagine additional optional flags for fix-isfixedpitch to set bFamilyType to 3 or 5, in addition to setting bProportion to 3. I *think* that is maybe excessive or out of scope? But not crazy.

**Comment by felipesanches** [comment]
I've implemented what you suggested. If you think I missed something, or that it could still be improved, please reopen the issue.

**Comment by tphinney** [comment]
Will do. I will take a look at the revised code, and try it on the font I am working on. Thanks!
