### ISSUE TITLE
document METADATA.pb

### ISSUE THREAD

**Issue by graphicore** [googlefonts/gftools#200]
In our Fridays meeting today and because of https://github.com/googlefonts/fontbakery/issues/2872 we noted that we're missing a lot of rationale about FB checks that involve METADATA.pb. 

I believe we should have a complete documentation about METADATA.pb in here to be referenced from the rationales of the checks.

Especially, since these structures were getting more complex with the addition of variable fonts and potentially other structures (#192). Since `gftools-add-fonts` and `fonts_public.proto` are located in this repository, I believe documentation should be as well located in here. But https://github.com/googlefonts/gf-docs could be a very good location as well.

**Comment by graphicore** [comment]
There's something: https://github.com/googlefonts/gf-docs/tree/master/METADATA

**Comment by davelab6** [comment]
Please schedule time with me to do this in a recorded video call

**Comment by davelab6** [comment]
I set up time tomorrow

**Comment by davelab6** [comment]
@graphicore and @m4rc1e I just had a video call about this; we resolved that there are dozens of metadata checks in the gf profile that need to be refactored,  as there appears to be a lot of redundancy, and Lasse will do this along with refactoring other parts of the gf profile, and the underlying fontbakery core code, related to super/sibling families, in June.

**Comment by davelab6** [comment]
Now June is coming to a close, what is the status of this?

**Comment by davelab6** [comment]
Well, I fixed the OP issue (https://github.com/googlefonts/gf-docs/commit/93998c1944467e027ab91e9519744469a9c3a392) 

I'll close this issue and open a new one in the fontbakery issue tracker.
