### ISSUE TITLE
Update PB py file

### ISSUE THREAD

**Issue by davelab6** [googlefonts/gftools#202]
Per chat with rod, someone needs to recompile https://github.com/googlefonts/gftools/blob/master/Lib/gftools/fonts_public_pb2.py as it appears to be rather far behind

https://developers.google.com/protocol-buffers/docs/pythontutorial#compiling-your-protocol-buffers explains why, tl;dr .proto is the source, you "compile" it to language-specific access classes. So here the fields you and I have played with are inaccessible to python until the python edition is compiled.

Someone should also update the readme so we don't forget

**Comment by graphicore** [comment]
I already PRed the recompile #201

**Comment by davelab6** [comment]
Thanks lasse
