### ISSUE TITLE
Fix 'add font' unicode escaping?

### ISSUE THREAD

**Issue by davelab6** [googlefonts/gftools#211]
In https://github.com/google/fonts/pull/2494/commits/c43cfa4c052758a57ad9135d636a00e4bdd4ae32 a new family was added to GF, and the METADATA designer string was

    designer: "Jonathan Barnbrook, Juli\303\241n Moncada"

@m4rc1e corrected this to

    designer: "Jonathan Barnbrook, Julián Moncada"

@vv-monsalve said,

> I used that string because it's the way the .pb format tends to convert or translate acuted-vowels. But if it works without it, the better.

Since it works for us without, if a tool in this repo is generating the 'escaped' strings, we should fix that tool :)

**Comment by graphicore** [comment]
I think the tool to fix would be the text-format implementation of protocol buffers, we're not generating the text format output with gftools internal code.

**Comment by graphicore** [comment]
https://googleapis.dev/python/protobuf/latest/google/protobuf/text_format.html

Ok, there's a bunch of arguments in
```
 google.protobuf.text_format.MessageToString(message, as_utf8=False, as_one_line=False, use_short_repeated_primitives=False, pointy_brackets=False, use_index_order=False, float_format=None, double_format=None, use_field_number=False, descriptor_pool=None, indent=0, message_formatter=None, print_unknown_fields=False)
```

I'd try:

**`as_utf8`** – Return unescaped Unicode for non-ASCII characters. In Python 3 actual Unicode characters may appear as is in strings. In Python 2 the return value will be valid UTF-8 rather than only ASCII.

**Comment by graphicore** [comment]
I can now confirm e.g. in `gftools-add-fonts.py`:

```py
  text_proto = text_format.MessageToString(metadata, as_utf8=True)
```

will do the trick.

**Comment by felipesanches** [comment]
thanks, Lasse!
