### ISSUE TITLE
Rename font script

### ISSUE THREAD

**Issue by RosaWagner** [googlefonts/gftools#213]
Is there a way to apply the rename-font script to a pack of fonts ?

Right it works if I do:
`gftools rename-font Name-Style.ttf NewName`
but not if I do:
`gftools rename-font *.ttf NewName`

**Comment by m4rc1e** [comment]
Most of our fix scripts will only work on a single font. If you want to update multiple fonts, your best bet is to call the script from a bash loop e.g

```
for font in $FONTS
do
  gftools rename-font $font NewName
  mv $font.fix $font
done
```
