### ISSUE TITLE
Update copyright string as hotfix

### ISSUE THREAD

**Issue by RosaWagner** [googlefonts/gftools#214]
trying to use [gftools-update-nameids.py](https://github.com/googlefonts/gftools/blob/master/bin/gftools-update-nameids.py) but I have an error message:
```
MBP-de-Rosalie:static rosalie$ gftools update-nameids -c="Copyright 2011 The Mulish Project Authors (github.com/googlefonts/mulish)" Mulish-Black.ttf
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/bin/gftools-update-nameids.py", line 102, in <module>
    main()
  File "/Library/Frameworks/Python.framework/Versions/3.7/bin/gftools-update-nameids.py", line 95, in main
    update_field(NAME_IDS[field.nameID], args, fields, font['name'])
  File "/Library/Frameworks/Python.framework/Versions/3.7/bin/gftools-update-nameids.py", line 58, in update_field
    swap_name(fields, nametable, text)
  File "/Library/Frameworks/Python.framework/Versions/3.7/bin/gftools-update-nameids.py", line 49, in swap_name
    text = str(font_name_field.getName(*field)).decode(enc)
AttributeError: 'str' object has no attribute 'decode'
MBP-de-Rosalie:static rosalie$ 
```

**Comment by felipesanches** [comment]
it seems to me that this line should instead be something like:

```python
text = font_name_field.getName(*field).string.decode(enc)
```

**Comment by m4rc1e** [comment]
I'm guessing this is a remnant from py2 days. `getName` also has a new `toUnicode` method which is better.

**Comment by RosaWagner** [comment]
But it worked :)

**Comment by RosaWagner** [comment]
@m4rc1e could you please describe as you would proceed with this method ? I don't understand what it means and I would like to learn this method too :)

**Comment by m4rc1e** [comment]
Sorry I was describing what we should do in order to fix the script. I've just pushed https://github.com/googlefonts/gftools/pull/215/files which should fix the issue. Please upgrade your gftools and retest.
