### ISSUE TITLE
Font authors find conflicting info in google/fonts/CONTRIBUTING.md versus GF Glyph Sets/README.md

### ISSUE THREAD

**Issue by belluzj** [googlefonts/gftools#217]
Hello,

I was trying to figure out what is the minimal glyph set for a font to be considered for inclusion in Google Fonts. From [that document](https://github.com/googlefonts/gftools/tree/master/Lib/gftools/encodings/GF%20Glyph%20Sets) I understand that covering those two files is mandatory:
* [Core](https://github.com/googlefonts/gftools/blob/master/Lib/gftools/encodings/latin_unique-glyphs.nam)
* [Plus](https://github.com/googlefonts/gftools/blob/master/Lib/gftools/encodings/latin-ext_unique-glyphs.nam)

However the Plus file lists many unassigned code points. What is the purpose of these? Do you expect the font to include little tofu glyphs for them?

![image](https://user-images.githubusercontent.com/3616772/85002669-17e98700-b14d-11ea-9a4d-dc440ce6cca1.png)

The whole 20C column is unassigned in the currency block:
![image](https://user-images.githubusercontent.com/3616772/85002799-44050800-b14d-11ea-8860-a803904dfbbb.png)

There is another list of unassigned code points later in the file. Thanks in advance for a clarification!

**Comment by graphicore** [comment]
@belluzj thanks for reporting this. I agree, 20C{x} looks like it shouldn't be there.

For reference [Currency SymbolsRange: 20A0–20CF](https://www.unicode.org/charts/PDF/U20A0.pdf) ([search](https://www.unicode.org/charts/))

> Do you expect the font to include little tofu glyphs for them?

No, definitely not.

> There is another list of unassigned code points later in the file.

Which code points are this?

**Comment by belluzj** [comment]
Parts of Latin Extended-D
![image](https://user-images.githubusercontent.com/3616772/85028407-f3a0a100-b172-11ea-97ea-0ff31aff5d95.png)

While we're discussing this, what is the rationale behind the Plus set? Is it just to cover whole Unicode blocks? To me it doesn't sound like most of the glyphs in Latin Extended D are useful in a general-purpose Google Font? Also, if Plus is indeed a requirement for new Google Fonts, that puts quite a high barrier to entry for new fonts, like some of these glyphs probably require quite advanced and niche language knowledge to be designed in a useful way?

**Comment by thlinard** [comment]
Hi @belluzj 

The requirements are here:
https://github.com/google/fonts/blob/master/CONTRIBUTING.md

The relevant line:

> * All font files have at a minimum the 215 glyphs listed in our [`latin_unique-glyphs.nam`](https://github.com/googlefonts/gftools/blob/master/Lib/gftools/encodings/latin_unique-glyphs.nam) file

**Comment by graphicore** [comment]
Please not that your link above that says "Plus" actually links "Extended" https://github.com/googlefonts/gftools/blob/master/Lib/gftools/encodings/latin-ext_unique-glyphs.nam Plus is https://github.com/googlefonts/gftools/blob/master/Lib/gftools/encodings/GF%20Glyph%20Sets/GF-latin-plus_unique-glyphs.nam

**Comment by belluzj** [comment]
Ah ok thanks for the link!

**Comment by belluzj** [comment]
So wait, is Core and Plus (with correct link) needed or just Core?

**Comment by graphicore** [comment]
OK, so this is quite a bit annoying and misleading: Don't use the glyph sets from https://github.com/googlefonts/gftools/tree/master/Lib/gftools/encodings these are used to configure the subsetter internally AFAIK. The lists for font authors are in: https://github.com/googlefonts/gftools/tree/master/Lib/gftools/encodings/GF%20Glyph%20Sets

**Comment by thlinard** [comment]
> Please not that your link above that says "Plus" actually links "Extended" https://github.com/googlefonts/gftools/blob/master/Lib/gftools/encodings/latin-ext_unique-glyphs.nam Plus is https://github.com/googlefonts/gftools/blob/master/Lib/gftools/encodings/GF%20Glyph%20Sets/GF-latin-plus_unique-glyphs.nam

Well… confusing links in https://github.com/googlefonts/gftools/blob/master/Lib/gftools/encodings/GF%20Glyph%20Sets/README.md:

> ### GF Latin Core
> 
> [encodings/latin_unique-glyphs.nam](https://github.com/googlefonts/gftools/blob/master/Lib/gftools/encodings/latin_unique-glyphs.nam)
> 
> ### GF Latin Plus (567 glyphs total + 25 optional)
> 
> [encodings/latin-ext_unique-glyphs.nam](https://github.com/googlefonts/gftools/blob/master/Lib/gftools/encodings/latin-ext_unique-glyphs.nam)

**Comment by thlinard** [comment]
> @thlinard Thanks for clarify. I saw the document you link to but also [this other one](https://github.com/googlefonts/gftools/blob/master/Lib/gftools/encodings/GF%20Glyph%20Sets/README.md) that got me confused:
> 
> > All new fonts submitted to the library must now support the Plus level as a minumum requirement.
> 
> I assume from your comment that CONTRIBUTING.md is the most up-to-date?

Good catch! I can't answer for Google, but I think these conflicting statements need to be resolved.

**Comment by graphicore** [comment]
@thlinard thanks for pointing out the wrong links in [GF Glyph Sets/README.md](https://github.com/googlefonts/gftools/blob/master/Lib/gftools/encodings/GF%20Glyph%20Sets/README.md)

@belluzj thanks for pointing out conflicting info in [google/fonts/CONTRIBUTING.md](https://github.com/google/fonts/blob/master/CONTRIBUTING.md) versus  [GF Glyph Sets/README.md](https://github.com/googlefonts/gftools/blob/master/Lib/gftools/encodings/GF%20Glyph%20Sets/README.md)

cc @davelab6

**Comment by davelab6** [comment]
https://github.com/googlefonts/gftools/pull/218 looks good to me

**Comment by davelab6** [comment]
With https://github.com/google/fonts/commit/9ae34c284f57a24ce484a0f49f38c26457f2603a and #218 I believe this issue should be resolved, @belluzj?

**Comment by davelab6** [comment]
Basically Plus is the new minimum, but I can offer exceptions on a case by case basis.

**Comment by belluzj** [comment]
Thanks Dave and Lasse, it is clear now!
