### ISSUE TITLE
update nameids --version

### ISSUE THREAD

**Issue by RosaWagner** [googlefonts/gftools#220]
Still experimenting with the corrected update-nameids.py script :) 

I updated version number for Poppins after modifying copyright string, but now the name table doesn't match the head table. How can I hotfix this ?

FB warning:
`head version is "4.003" while name version string (for platform 3, encoding 1) is "4.004".`

**Comment by m4rc1e** [comment]
You want

`gftools update-version [fonts] old-version-number new-version number`

This will also take care of the name table record.

**Comment by m4rc1e** [comment]
Here's the source, https://github.com/googlefonts/gftools/blob/master/bin/gftools-update-version.py

**Comment by RosaWagner** [comment]
Ah yes, I forgot about this one ^^ thank you Marc
