### ISSUE TITLE
fix-vf-meta hairline instance 

### ISSUE THREAD

**Issue by RosaWagner** [googlefonts/gftools#221]
vf-fix-meta script creates a Hairline instance instead of a Thin instance at 100. 

Issue probably comes from here: 
https://github.com/googlefonts/gftools/blob/7956c941bc58f21a9e32096a2f9db9129192ba70/Lib/gftools/util/google_fonts.py#L86

fix-vf-meta script works fine when I just delete this line in util/google_fonts.py. If this radical fix is okay for you I PR.

**Comment by m4rc1e** [comment]
@RosaWagner Thanks for inspecting this! no need to do anything, I'll make a fix.

**Comment by davelab6** [comment]
Hairline is `1`, ExtraBlack is `1000`

**Comment by m4rc1e** [comment]
I'll add hairline in my next PR. Thanks.
