### ISSUE TITLE
fix-vf-meta works on macOS, fails on Linux

### ISSUE THREAD

**Issue by alerque** [googlefonts/gftools#225]
I'm trying to cleanup the build/release process for a font with an existing build script that runs:

    gftools fix-vf-meta <input.ttf>

When I run this, I get

```
Traceback (most recent call last):
  File "/usr/bin/gftools-fix-vf-meta.py", line 206, in <module>
    main()
  File "/usr/bin/gftools-fix-vf-meta.py", line 196, in main
    update_nametable(roman_font)
  File "/usr/bin/gftools-fix-vf-meta.py", line 134, in update_nametable
    raise ValueError(f"Fvar instance coord {wght_val} needs to be "
ValueError: Fvar instance coord 277.0 needs to be within range 0-1000 and be a multiple of 100
```

The font designer (@sursly) runs the same build scrip on the same sources the font apparently builds for him. Tyler maybe you can add here what version you are running.

I've tried with v0.3.13, v0.3.14, and the latest git HEAD (apparently 2 commits ahead of the release, although without tags it's hard to say) and got the same results in each case.

There might indeed be a problem with the font as is suggested, but the fact that running the same command on macOS does not find the same problem is concerning.

**Comment by m4rc1e** [comment]
Thanks for the issue.

To diagnose, I'd do the following:

- run `ttx -t 'fvar' font.ttf` on both the mac and linux systems: This will dump the fvar table in the fonts.
- diff both .ttx files.

Since the exception that gets raised is trivial, I reckon the mac and linux fonts are different. The Mac font pass because its fvar instance coordinates are all multiples of 100.

**Comment by alerque** [comment]
@m4rc1e Thanks for that tip, I'll get on it. In that case we might have a `fontmake` bug...I'll update when we know.

**Comment by alerque** [comment]
Thanks again for the tip @m4rc1e. In the process of doing as you suggested it came to light that the "latest" version of gftools Tyler was using is actually 7 versions old. I'm able to replicate his results with the old version and the error being thrown in the new version is probably legitimate.

**Comment by m4rc1e** [comment]
Thanks @alerque. btw, I agree with you on tagging releases and having better notes. I'll start pushing tags in the future.
