### ISSUE TITLE
New tool: add-axis

### ISSUE THREAD

**Issue by davelab6** [googlefonts/gftools#234]
Similar to the `METADATA.pb` generator in the `add-font` tool, following https://github.com/google/fonts/pull/2541 we need simple little `add-axis` tool which will generate `$AXIS.protobuff` files for PR'ing into https://github.com/google/fonts by extracting the relevant information from the font's fvar/stat tables. 

(Note that the file extension may change, per https://github.com/google/fonts/issues/2595)

I guess we need the `axis.proto` file that defines the schema that these axis registry files use, too. @nathan-williams please could you supply that? :)

**Comment by nathan-williams** [comment]
The font binary only has some of the required axis metadata. Also, the GF Axis Registry axes are not intended to be font-specific.

IMO, such a utility doesn't add a lot of value and suggests a coupling between a specific font's axis definitions and those in the GF Axis Registry. What do you think?

**Comment by davelab6** [comment]
Given we will author a relatively small number of axes, perhaps the time taken to write such a tool isn't worth it. 

As we will also need to write FontBakery checks to ensure each family's METADATA is compliant with the registry, so perhaps a fontbakery developer like @graphicore or @felipesanches can pick this up at that moment as its a very small task.

**Comment by davelab6** [comment]
Proto file is now added per IM discussion; assigning to Lasse for now

**Comment by graphicore** [comment]
I'm not sure what to do with this assignment other than asking questions.

> The font binary only has some of the required axis metadata. Also, the GF Axis Registry axes are not intended to be font-specific.
> 
> IMO, such a utility doesn't add a lot of value and suggests a coupling between a specific font's axis definitions and those in the GF Axis Registry. What do you think?

We could use an existing font to jump start (pre-fill) a new `$AXIS.protobuff` then maybe drop into an interactive mode that helps authoring or just have the user pick up in the editor from there. Also provide some types/sanity checking/does-it-parse validation on top. Could be all one workflow or accessed separately:

 * jump-start from font
 * interactive authoring (maybe this just opens $EDITOR)
 * validation
 
> Given we will author a relatively small number of axes, perhaps the time taken to write such a tool isn't worth it.

Yes. Though, cut out the interactive stuff, or make it super simple based on $EDITOR plus  validation result, and it's probably small enough to start quickly.
