### ISSUE TITLE
Pillow still 7.0 instead of > 7.1

### ISSUE THREAD

**Issue by RosaWagner** [googlefonts/gftools#255]
Although #249 unpins Pillow, I still have the version 7.0.0 when I upgrade gftools and compile requirements. The guys from JetBrains Mono reported a "security alert" because of it…

**Comment by m4rc1e** [comment]
Perhaps your pip is using a cached version of Pillow?

Try creating a new virtualenv and installing gftools using `pip install gftools --no-cache-dir`. When I do this and run `pip freeze`, I get `Pillow==8.0.0`

**Comment by RosaWagner** [comment]
thanks it works
