### ISSUE TITLE
Update font_public.proto

### ISSUE THREAD

**Issue by m4rc1e** [googlefonts/gftools#258]
I see Ballet's [METADATA.pb](https://github.com/google/fonts/blob/master/ofl/ballet/METADATA.pb#L24-L27) includes a new field:

```
registry_default_overrides {
  key: "opsz"
  value: 16
}
```

@garretrieger do we have an updated fonts_public.proto file which includes this?

**Comment by garretrieger** [comment]
Fixed with: https://github.com/googlefonts/gftools/commit/aa20bb6ef9a82c7abeec20edee911becbde45a4b
