### ISSUE TITLE
pip installation on zsh may need to be escaped

### ISSUE THREAD

**Issue by frankrolf** [googlefonts/gftools#259]
Just found out (with @ruggeromagri) that the installation of the QA tools may require the following, escaped command:

```
pip install gftools\[qa\]
```

No idea why that’s happening – using zsh on macOS 10.15 (in case this is relevant)

**Comment by punchcutter** [comment]
zsh should work with quoting like `pip install 'gftools[qa]'` Really any pipping with zsh should use that and bash can also use it just fine.

**Comment by felipesanches** [comment]
thanks, @frankrolf
