### ISSUE TITLE
Core Latin coverage requirement

### ISSUE THREAD

**Issue by aaronbell** [googlefonts/gftools#266]
I'm working with a foundry to prepare Japanese fonts for release on Google Fonts, and found that the fonts are missing a small number of glyphs from the Core Latin font coverage. Specifically:

* FAIL: Missing required codepoints: 0x2074 (SUPERSCRIPT FOUR), 0x20AC (EURO SIGN) and 0x2215 (DIVISION SLASH) [code: missing-codepoints]

Per the discussion [here](https://github.com/Fontworks-TechService/DotGothic16/issues/4), @m4rc1e stated that he is OK with not including these glyphs in the fonts. 

It was my understanding that any font that includes Latin coverage should at minimum include the Core Latin glyph set (and actually according to the [README](https://github.com/googlefonts/gftools/tree/master/Lib/gftools/encodings/GF%20Glyph%20Sets) we should be enforcing the PLUS character set). Is that not the case?

**Comment by thlinard** [comment]
OK to not include €? The USA haven't conquered the European Union, yet. 😁

**Comment by davelab6** [comment]
Three aren't release blocking but I do hope the foundry will add them, and they might want to do this before the first release

**Comment by aaronbell** [comment]
That’s fine. I just wanted to confirm that it is still a requirement, even if only eventually :).

**Comment by m4rc1e** [comment]
> If there is space and design savings to be made, I suggest doing without the £: the absence of this character obviously 😁 doesn't matter.

Lol. If we do this, can we at least wait until the 1st of January 2021 please?

**Comment by thlinard** [comment]
> > If there is space and design savings to be made, I suggest doing without the £: the absence of this character obviously 😁 doesn't matter.
> 
> Lol. If we do this, can we at least wait until the 1st of January 2021 please?

With or without a deal? 😁
