### ISSUE TITLE
Glyph data excluded in latest release

### ISSUE THREAD

**Issue by alerque** [googlefonts/gftools#269]
I noticed when packaging 0.5.0 for Arch Linux that the package size went from ~7MB to somewhere less than 2MB. A quick diff of the file list suggests that the most likely candidate is that two XML files in `util/GlyphsInfo/` are not in the latest release?

I'm not even sure what they were used for before or if perhaps this was intentional, but the release notes don't mention it and it seems like a major change that *might* break something for someone.

**Comment by m4rc1e** [comment]
Ouch. I reckon this has happened because our github action to make the release isn't checking out the submodule which contains these files. I'll update the action to fetch the submodules. We need more tests to catch these issues.
