### ISSUE TITLE
[builder] default config filename

### ISSUE THREAD

**Issue by davelab6** [googlefonts/gftools#293]
Per "convention over configuration" I propose builder should work without any args if a config.y[a]ml exists in the pwd. So these would be equivalent

    gftools builder config.yml 
    gftools builder config.yaml 
    gftools builder

**Comment by m4rc1e** [comment]
There may be multiple configs in the same directory though.

**Comment by graphicore** [comment]
`builder.yml` would be better as we'd know what it is supposed to configure.

**Comment by davelab6** [comment]
`builder.yml` is fine too, my point is that I would like the tool to have sensible defaults and heuristics for projects that follow our conventions. 

For example in https://github.com/kosbarts/Oi/issues/2 a yaml config is provided, but all the information could likely be autodetected.

**Comment by davelab6** [comment]
> There may be multiple configs in the same directory though.

That's fine, only one would be used if it uses the conventional filename and builder is run without args, and none would be used if none are named conventionally, and any can be used when passed as an arg.

**Comment by RosaWagner** [comment]
> For example in kosbarts/Oi#2 a yaml config is provided, but all the information could likely be autodetected, or assumed as they are canonically conventional.

Actually for this font the config file is not even needed I think, `gftools builder Oi.glyphs` would be enough. But when I do, it builds a VF with wght and XXXX axis, although there is only one master.
