### ISSUE TITLE
[spec] How to handle slant axis in STAT table

### ISSUE THREAD

**Issue by RosaWagner** [googlefonts/gftools#295]
We have a bunch of fonts with a slant axis coming up (with slant, backslant, italic), I think we need to set up some kind of a standard to handle it properly even though GF won't serve it before a while. Nothing prevent from integrating it correctly into the STAT table and therefore the new config.yaml. 

- What fallback names? Right now axis registry has "0=Default". After discussing with @arrowtype, @vv-monsalve and @tphinney, "Upright/Oblique" seem appropriate for our projects. Although, doesn't give an answer for a BackSlant fallback.
- Range values accepted? It would make sense. 
- Linked value flag between Upright and Oblique when no ital axis?
- Do we tick the "is italic" flag in Glyphs when no ital axis?
- Axis Order ? I remember we said Oblique at the end, like Italic. So slant axis should be after weight. But then there is the Backslant which should go on the family name side…
- We should be able to give an examples for these 3 cases (STAT, Static Instances scheme) : 
    -- only slant (with Oblique fallback)
    -- only slant (with Oblique and Backslant fallbacks)
    -- slant + ital (use of STAT format 4?)

References from @arrowtype:
- [VF Slant Browser support](https://arrowtype.github.io/vf-slnt-test/)
- [VF Slant Browser support updated](https://arrowtype.github.io/vf-slnt-test/slnt-ital-tests/index.html)
- [Recursive STAT builder by @benkiel](https://github.com/arrowtype/recursive/blob/a1fab1a85ba775d0f6ba4e21ac2eac5ec5797dff/mastering/build_variable.py#L25
)

**Comment by RosaWagner** [comment]
Last question:
- Shall we include oblique instances in the fvar instances?

**Comment by m4rc1e** [comment]
Apologies for my late reply

> What fallback names? Right now axis registry has "0=Default". After discussing with @arrowtype, @vv-monsalve and @tphinney, "Upright/Oblique" seem appropriate for our projects. Although, doesn't give an answer for a BackSlant fallback.

What would happen if we upgrade a family to a VF and it has a slnt axis but there are already static Italic fonts? the fvar instances won't match the existing statics.

> Range values accepted? It would make sense.

I don't think we should restrict the range for users. I recommend we just use what the OT spec says, https://docs.microsoft.com/en-us/typography/opentype/spec/dvaraxistag_slnt#axis-definition

> Linked value flag between Upright and Oblique when no ital axis?

> Do we tick the "is italic" flag in Glyphs when no ital axis?

Agree with mr Phinney

> Axis Order ? I remember we said Oblique at the end, like Italic. So slant axis should be after weight. 

At the end sgtm. 

> But then there is the Backslant which should go on the family name side…

Do we have a url for a family with backslant? before I mention anything, we should test how it works.

**Comment by RosaWagner** [comment]
Examples:
- [Gluten](https://github.com/RosaWagner/Gluten): slant and backslant, no cursive substitutions
- [Commissioner](https://github.com/kosbarts/Commissioner): slant axis and already published with fvar instances named "italic"
- Geologisk: have slant+cursive alternates (but repo is still private), ital would be the reunion of both (like in recursive)

**Comment by RosaWagner** [comment]
@felipesanches this could have consequences on the related check ital/slant axis -> slant and ital axes shouldn't be in Metadata.pb, but okay in stat?

**Comment by RosaWagner** [comment]
I would like to set up examples for a STAT table + Naming scheme for these different case studies:

**1. Font has a slant axis, no italic/cursive substitutions**
a. with backslant fallback (eg. Gluten)
b. without backslant fallback (eg. Commissioner)

**2. Font has a slant axis with italic/cursive substitutions**
a. already published as 2 fonts (Roman, Italic) with ital axis and no slant (Eg. future update for Epilogue) 
b. already published as 1 font without ital axis (eg. Recursive)
c. not published yet (Eg. Geologisk)

**3. Font has ital axis and wishes to show variation of slope;** 
So 2 fonts Roman+Italic, with a new "slope" axis : could actually be the solution for case **2.a**

**Comment by vv-monsalve** [comment]
> What fallback names? Right now axis registry has "0=Default". After discussing with @arrowtype, @vv-monsalve and @tphinney, "Upright/Oblique" seem appropriate for our projects. Although, doesn't give an answer for a BackSlant fallback.

For a semantic pairing for the axis maybe Slanted/BackSlanted would be more direct, and perhaps clearer to the users. However this second one is a rare case, so it would make it better to stick to Oblique/BackSlanted.

> What would happen if we upgrade a family to a VF and it has a slnt axis but there are already static Italic fonts? the fvar instances won't match the existing statics.

Perhaps it could be handle with a multi-axis value combination (STAT format 4) like in Recursive.

> Range values accepted? It would make sense.

I don't think we would need them.

> Linked value flag between Upright and Oblique when no ital axis?
> Do we tick the "is italic" flag in Glyphs when no ital axis?

Agree with Thomas and Marc

> Axis Order ? I remember we said Oblique at the end, like Italic. So slant axis should be after weight. But then there is the Backslant which should go on the family name side…

I don't see another option, particularly if we are not going to include the Oblique instances in the fvar.

> We should be able to give an examples for these 3 cases (STAT, Static Instances scheme) :
> -- only slant (with Oblique fallback)

But,  «If we decide to name the slnt token as "Italic"» then the Oblique fallback would only apply for cases in which the "italic" token is not used for the slanted font.
Geologisk has both cases: "ital" (formed with slant + cursive) and It has another use of only "slant" under an Oblique variant.

> -- only slant (with Oblique and Backslant fallbacks)
> -- slant + ital (use of STAT format 4?)

Taking into consideration what it's said in the [spec](https://docs.microsoft.com/en-us/typography/opentype/spec/dvaraxistag_ital#additional-information) `The Italic axis is distinct from the Slant axis ('slnt'). Fonts may use one or the other, depending on the nature of the design, but should rarely use both.` I think this one should be avoided.

Other examples would be:

-- slant + cursive (combined under an "ital" token, use of STAT format 4 definitely needed)
-- only cursive (with Cursive fallback)

**Comment by RosaWagner** [comment]
To follow on Marc's comment https://github.com/googlefonts/gftools/issues/295#issuecomment-765359442
Shall we go for `Italic` everywhere ? (cf: https://github.com/googlefonts/fontbakery/issues/2795)

**Comment by arrowtype** [comment]
Would it be possible to allow either "Italic" (most common) or "Oblique" (less common but sometimes used) in instance naming, for a variable font with a Slant axis?

**Comment by RosaWagner** [comment]
Reading and re-reading the opentype spec… this is actually what I would do as the safest / most compatible option: **NOT treat slant axis as an ital axis**, but as a complete "Roman" font with an additional axis like width or whatever _(ie. no italic style linking)_. 

Since this is pretty restrictive, this would go for Google Fonts universe, not any font project of the world obviously.

Fallbacks can be:
- Oblique (negative value, right leaning slope)
- Upright (elided, value=0)
- Reverse (positive value, left leaning slope)

Slant fallbacks would go in the family name side of the file.

IF presence of "italic" alternates:
- Italic would be treated as usual (with a linked style for every roman styles — oblique, upright, reverse)
- Italic variable file would be separated from Roman

IF you really want to have your slanted font as the "italic" of your upright styles: slant is therefore treated as usual italic:
- VF separated from Roman (Upright)
- ital axis (value 0/1) and not a slant axis
- no variation slider for slant.

Now I need 2 fonts to test the different cases. BUT does anybody feel strongly against this ?

**Comment by eliheuer** [comment]
One thing to think about with this is Arabic fonts with bidirectional slant axes. The upstream of Cairo has an axis that interpolates between leftward (forward for Arabic) and a rightward (backwards for Arabic). I have an issue about this from last year that is still open: https://github.com/google/fonts/issues/2400

> Fallbacks can be:
Oblique (negative value, right leaning slope)
Upright (elided, value=0)
Reverse (positive value, left leaning slope)

Using the term reverse for a left-leaning slope would be very confusing for projects like Cairo, where the reverse slant is rightward.

**Comment by RosaWagner** [comment]
True, I was thinking in the scope of Latin which is wrong. 
So it can't be backslant either, nor backwards… do you already have something in mind?

Are Leftwards and Rightwards existing english words ? ^^'

**Comment by thlinard** [comment]
> Are Leftwards and Rightwards existing english words ? ^^'

https://en.wiktionary.org/wiki/leftward
https://en.wiktionary.org/wiki/leftwards
https://en.wiktionary.org/wiki/rightward
https://en.wiktionary.org/wiki/rightwards

You have to be French to have such linguistic insecurities. 😁

**Comment by arrowtype** [comment]
> a gif of the Cairo slnt axis from the last time I looked at it. The leftward slant is a negative value, which goes against the above fallback

It’s still slightly annoying to me that this is the case, but ... per the OpenType spec, negative values should be clockwise (rightwards) slant, following mathematical conventions. So, I think that GIF is technically showing incorrect behavior for the Slant axis, even though in a UI sense, it seems intuitive.

From the spec on [Slant](https://docs.microsoft.com/en-us/typography/opentype/spec/dvaraxistag_slnt):

> Note that the scale for the Slant axis is interpreted as the angle of slant in counter-clockwise degrees from upright. This means that a typical, right-leaning oblique design will have a negative slant value.

That said, instead of using leftwards/rightwards labels, we could use clockwise/counterclockwise.

Another thing to perhaps consider is that CSS has started using "start" and "end" syntax, so that the intent of a design made in a left-to-right language (e.g. left-aligned text) can easily be carried over in an RTL language. I don’t have a specific idea here, but I wonder if it might make sense to make an axis (potentially not Slant, as that is already defined) that is a user-focused axis to describe obliqueness. Then again, it is probably a bad idea to introduce yet another axis to this area.

**Comment by RosaWagner** [comment]
> That said, instead of using leftwards/rightwards labels, we could use clockwise/counterclockwise.

That's an idea. Since I still confuse my right and my left, it does make more sense to me, but `counterclockwise` is also a lot of characters.

> but I wonder if it might make sense to make an axis (potentially not Slant, as that is already defined) that is a user-focused axis to describe obliqueness

I thought about a "SLOP" axis in the past, but it sounded redundant with the slant axis, and also confusing with the WWS norm.

**Comment by RosaWagner** [comment]
I got confirmation from the eng team that slant axis will be treated as any other axis (and not like weight and ital).
Therefore if we agree on the fallback names, I could make a axis proposal and update the spec.

**Comment by vv-monsalve** [comment]
I would advocate for `LeftLeaning` `RightLeaning` fallback names as they are shorter and perhaps would be more intuitive, in a UI sense.

**Comment by m4rc1e** [comment]
How are you going to map fallback names to values when the values for the slnt axis are arbitrary?

**Comment by RosaWagner** [comment]
If it’s possible, another question for the eng team.
Or it could include ranges?

**Comment by yanone** [comment]
For my understanding: Why are the fallback names necessary? And do they need to be tied to a specific value?

Indeed for this axis and probably many others it will not be possible to tie the min and max value to a name in the axis definition.

**Comment by RosaWagner** [comment]
For now, adding the slant axis to the font will enable the use of the axis in the Type tester in GF, but there is still no instance value and name linked to it. Except for default=0. Min and max can be whatever you want in the font but should not appear in the STAT table.

So for now, Slant axis should only refer to elided "Default" value = 0. Like in Roboto Flex. Although I find "default" a bit lame, I would have opted for "Upright" personally. And no slanted instances in FVAR table.

This was for new fonts or new slant axis; for the fonts already onbaorded we can really modify anything, except for adding the axis in METADATA.pb

**Comment by RosaWagner** [comment]
What is confusing me is: where does it come in the axis order? @m4rc1e

**Comment by RosaWagner** [comment]
Closing this issue cause discussion has continued there: https://github.com/google/fonts/issues/2606 and there https://github.com/googlefonts/axisregistry/issues/10
