### ISSUE TITLE
fix-vf-meta should warn (or fail?) if font has more axes than weight 'wght'

### ISSUE THREAD

**Issue by tphinney** [googlefonts/gftools#342]
So, fix-vf-meta does 'STAT' table generation, but only does the right thing if there is only a Weight axis. This is a known thing, and statmake is the answer if you have more axes.

BUT it seems to me that it would be good if fix-vf-meta would *check* for the presence of more axes, and fail, or at least warn, if there are more axes, and tell the user they need to use something else.

**Comment by davelab6** [comment]
@m4rc1e says to use GFTools Builder, where you can specify the STAT table as a YAML file; and fix-vf-meta should only be used on weight axis fonts.

**Comment by tphinney** [comment]
Right, per discussion, will try GFTools Builder.

**Comment by simoncozens** [comment]
fix-vf-meta died in #501.
