### ISSUE TITLE
builder doesn't flatten nested components

### ISSUE THREAD

**Issue by alexeiva** [googlefonts/gftools#346]
I am working on a private repo with a builder workflow, and have some nested components.
I added a `flattenComponents: true` to config.yaml (but it should be on by default).
Fontbakery still gives me the nested components fail:
```
 * FAIL: The following glyphs have components which themselves are component glyphs:
	* uni1EB0
	* uni1EB4
	* uni1EAA
	* uni01C4
	* uni01C5
	* uni1EC4
	* uni01C8
	* uni01CB
	* uni1ED6
	* aacute and 196 more. [code: found-nested-components]
```

I tried to manually add a ufo2ft filter to the UFOs in master_ufo to unnest composites  as described in https://github.com/googlefonts/fontbakery/issues/2961#issuecomment-733745539
The generated fonts via fontmake then decompose correctly. 

It looks like the flattenComponents filter isn't working with builder. 

Reference:
https://github.com/googlefonts/youtube-sans/issues/12#issuecomment-800033139

**Comment by m4rc1e** [comment]
Have you upgraded your gftools? `pip install --upgrade gftools`

**Comment by alexeiva** [comment]
upgrading fonttools fixed the issue. thanks
