### ISSUE TITLE
builder - can't have two separate families in one outputDir

### ISSUE THREAD

**Issue by alexeiva** [googlefonts/gftools#347]
I have two separate families in a repo with different design spaces, and need them to export into one fonts folder.  I have two config files for each. When I build a config file builder removes everything from the fonts folder. So I can't export both families in one folder simultaneously.  Is there a way to have builder not clean the fonts folder before generating fonts?

Of course, I can specify different sub-folders for each family and avoid this conflict.

**Comment by simoncozens** [comment]
I think this is fixed now that "cleanup" is gone away and we just use temporary directories and move things into place instead.
