### ISSUE TITLE
macOS Big Sur v11.2: pip install gftools works, but --editable install fails

### ISSUE THREAD

**Issue by eliheuer** [googlefonts/gftools#352]
I'm trying to get `gftools` working on a 2020 M1 Mac Mini (Big Sur v11.2) Python v3.9.2, and having issues. 

Following the advice here...
https://github.com/googlefonts/gftools/issues/298
https://github.com/googlefonts/gftools/pull/300
I got `gftools` working on Big Sur 11.2 by installing [ttfautohint](https://www.freetype.org/ttfautohint/) manually, then `brew install libgit2`, and it works when using `pip install gftools`.

However, I want to make some PRs back to `gftools`, and when I try to install in `--editable` mode I get the old `ttfautohint-py` error:
```
Requirement already satisfied: babelfont in /Users/eli/Py/repos/babelfont/lib (from gftools==0.7.1.dev2+g3d633b9) (2.0.3.dev5+ge30aba5)
ERROR: Could not find a version that satisfies the requirement `ttfautohint-py` (from `gftools`)
ERROR: No matching distribution found for `ttfautohint-py`
```
Please let me know if anyone has been able to get `gftools` working in `--editable` mode on Big Sur with a M1 computer.

**Comment by simoncozens** [comment]
I think this is fixed now that we have ttfautohint-py wheels for M1. Feel free to let me know if not.
