### ISSUE TITLE
ital still in VF file name

### ISSUE THREAD

**Issue by RosaWagner** [googlefonts/gftools#363]
although this PR was merged https://github.com/googlefonts/gftools/pull/341
and gftools released recently,

`ital` still appears in font file name.
https://github.com/RosaWagner/Tourney

**Comment by m4rc1e** [comment]
Your Glyphsapp Axes customParameter includes "Italic" when this axis doesn't exist.


<img width="564" alt="Screenshot 2021-04-27 at 18 24 17" src="https://user-images.githubusercontent.com/7525512/116285277-e4708380-a785-11eb-925c-bd1b8a7e088a.png"


Remove this and you're all good.

**Comment by RosaWagner** [comment]
Ah thanks
