### ISSUE TITLE
Two sets of .nam files in this repo?

### ISSUE THREAD

**Issue by felipesanches** [googlefonts/gftools#364]
There are 2 different sets of **.nam** files in this repo, which seems to cause confusion among designers. A while ago a designer opened an issue about that in fontbakery (https://github.com/googlefonts/fontbakery/issues/2755) and he was simply looking at the wrong set of **.nam** files.

There are files in the `gftools/Lib/gftools/encodings/GF Glyph Sets/` directory, but there are also files in the parent folder.

It seems that one set of nam-files is controlled by the internal Google Fonts engineering team, while the other set was once polished to give it out to designers, e.g. to describe what they are expected to do.

I think we should describe this more explicitly in the documentation of each directory (or on google/fonts documentation) and on the main README.md on this repo.

**Comment by vv-monsalve** [comment]
I found this new Issue when I was about to make a really similar comment in the older Issue.

We should first identify which version would be the source of truth to clarify it in the documentation. Who would have the 'last word' on this?
