### ISSUE TITLE
Improve check-gf-github

### ISSUE THREAD

**Issue by davelab6** [googlefonts/gftools#373]
@m4rc1e Please could you add some docs to the gftools repo for the `gftools check-gf-github` command :)

The docstring in https://github.com/googlefonts/gftools/blob/main/bin/gftools-check-gf-github.py is OK but there's a bit more context and workflow steps to getting it set up that are latent/implied and it would be nice to make it clearer

Then, ideally, set up a Github Actions to run it regularly and post the results somewhere (maybe a new txt file once a month into the `check-gf-github` branch on this repo?) so we can just look up the info as needed :)

**Comment by m4rc1e** [comment]
Going to close this since https://google.github.io/fonts/ now exists :-)
