### ISSUE TITLE
builder: append gftools version number to font's unique font id name record

### ISSUE THREAD

**Issue by m4rc1e** [googlefonts/gftools#380]
This will be handy for debugging purposes. It also means we can write an FB check to test whether users are generating fonts with the latest version of gftools.

@eliheuer would you be interested in writing this?

**Comment by eliheuer** [comment]
Sure, I'll give this a try. Thanks!

**Comment by eliheuer** [comment]
Ok, it looks like all I need to do is update the `unique_name` function in `Lib/gftools/utils.py`, PR on the way.
