### ISSUE TITLE
Builder Schema doesn't accept 'Semi'-width values in config

### ISSUE THREAD

**Issue by aaronbell** [googlefonts/gftools#382]
I'm creating a config file for League Gothic, which contains "SemiCondensed" and "SemiExpanded" widths. According to the spec, these values should be set with a decimal:

> name | wdth coordinate value
> -- | --
> UltraCondensed | 50
> ExtraCondensed | 62.5
> Condensed | 75
> SemiCondensed | 87.5
>   | 100
> SemiExpanded | 112.5
> Expanded | 125.0
> ExtraExpanded | 150.0
> UltraExpanded | 200.0

However, the [Builder Schema](https://github.com/googlefonts/gftools/blob/8b53f595a08d1b3f86f86eb97e07b15b1f52f671/Lib/gftools/builder/schema.py) requires that any value provided in the config.yaml file must be an integer. 

I suggest changing the schema to allow for float values, or adding a variant into the check to ensure that "87.5" and "112.5" is allowed when 'wdth' is used.

**Comment by eliheuer** [comment]
I can try looking into this later this week if no one else has time.

> adding a variant into the check to ensure that "87.5" and "112.5" is allowed when 'wdth' is used.

This is probably the way Marc would prefer? Right now I can't think of any other reason why you would want to use a float here.

**Comment by m4rc1e** [comment]
> I can't think of any other reason why you would want to use a float here.

Ms Spec says that Stat values are the 'fixed' datatype. I suggest we accept both ints and floats so users are free to use either.

**Comment by m4rc1e** [comment]
Thanks Aaron, this should now be fixed. I will cut a new release today.
