### ISSUE TITLE
Last tag didn't get  built and sent to PyPi correctly

### ISSUE THREAD

**Issue by alerque** [googlefonts/gftools#386]
The *sdist* package used by Arch Linux and others for packaging didn't show up on PyPi for v0.7.3 so I just checked and it looks like the whole release is missing. Perhaps a CI tooling problem?

**Comment by m4rc1e** [comment]
Hey Caleb.

I accidentally made a local tag called `v.0.7.3` when it should've been `v0.7.3`. I thought I solved the issue by doing:

```
git tag v0.7.3 v.0.7.3 # this will create a dup which is named correctly
git tag -d v.0.7.3 # del old
git push tag v0.7.3
```

Unfortunately when I pushed the tag, the ci still thinks it's `v.0.7.3` which some lib in python cannot parse

I'm tempted to just make a new emergence `v0.7.4` release asap.

**Comment by simoncozens** [comment]
You probably need to push the deletion. `git push --delete origin v.0.7.3`

**Comment by m4rc1e** [comment]
It's strange because I never pushed the faulty tag.

**Comment by simoncozens** [comment]
I've just hit rerun, let's see what happens.

**Comment by simoncozens** [comment]
Argh, of course, that won't complete because the release does exist. Yeah, I'd release another.

**Comment by alerque** [comment]
I have to imagine the tag got pushed somehow (probably because you have tag pushing enabled by default for all push actions or something). Since it's not in the code the CI wouldn't have any other way of knowing.

Unfortunately though the tag isn't on the repo any more, the CI system seems to have it's own cache of the repo and is resolving references from that.

**Comment by m4rc1e** [comment]
Well it seems to be a strange bug that happens on annotated tags when you rename them locally. 

Setuptools_scm parses the version number from the `git describe` command. If I run this command, I get the following error message: 

`warning: tag 'v0.7.3' is externally known as 'v.0.7.3'`.

So git describe is picking up the previous incorrect number. One solution is to force push the tag but I don't like rewriting git history. Instead, I've simply cut a new `v0.7.4` release, https://github.com/googlefonts/gftools/releases/tag/v0.7.4.

Thanks both of you for your suggestions.
