### ISSUE TITLE
Document the CLS fallback keys in METADATA.pb files

### ISSUE THREAD

**Issue by davelab6** [googlefonts/gftools#391]
In https://github.com/google/fonts/pull/3542/files @rsheeter introduced new METADATA keys for CLS, so it would be good to update the documentation (https://github.com/googlefonts/gf-docs/edit/main/METADATA/README.md) and the public protobufs definition (https://github.com/googlefonts/gftools/blob/main/Lib/gftools/fonts_public.proto) so that our community tools continue to work well.

Also internally tracked as b/193193946

**Comment by rsheeter** [comment]
I don't want to update docs until we commit to the feature. Will send a PR for the proto file.

**Comment by rsheeter** [comment]
https://github.com/googlefonts/gftools/blob/proto_update/Lib/gftools/fonts_public.proto appears to have been updated in 513d9c1047, how convenient.
