### ISSUE TITLE
builder: Ability to set font version in config file

### ISSUE THREAD

**Issue by m4rc1e** [googlefonts/gftools#394]
It would be nice to have a field in the config file which sets the version number for all fonts. Imo it should take precedence over all other forms of setting the version number. 

cc @simoncozens

**Comment by simoncozens** [comment]
Definitely! In the source font or in the binary?

**Comment by m4rc1e** [comment]
Atm, I'm thinking just the binaries. Personally, I find the builder is simply adding features that don't exist in the source formats yet so we shouldn't tamper with existing sources.
