### ISSUE TITLE
Bring back the travis testing

### ISSUE THREAD

**Issue by graphicore** [googlefonts/gftools#4]
Used to be configured like this: https://github.com/google/fonts/blob/b8d3c3962a64ca89bf81874f310fb461968dbfc8/.travis.yml

Both are simple sanity checks. We could also use a proper testing suite, like [pytest](docs.pytest.org).

**Comment by felipesanches** [comment]
Who's the admin who can enable testing for this repo on Travis? Is it just @davelab6 ?

Ths `.travis.yml` is there (I've added it on the #25 pull request mentioned above) but some one has to register this repo on Travis and I tihnk I lack admin access to do so.

**Comment by chrissimpkins** [comment]
Confirming that for contributions here you would like the associated tests in pytest?

Also, is there a standard set of testing source files and font files that you use / plan to use for testing?   If not, is it OK to introduce new test files to the repo and are there license restrictions with these test files vs. your licensing here?

**Comment by felipesanches** [comment]
yes, we'd always ideally expect tests for new code.

I'm still transitioning the fontbakery scripts into this repo. Just noticed that there are still some left-over from the gftools packaging effort that I'll have to deal with (I gotta package the code from that `utils` directory as well).

So, please feel free to suggest the testing approaches that you like. My goal is that whatever we choose and implement is at least consistent throughout the full set of tools.

Regarding licensing, let's stick to Apache License v2.0 for the whole of the repo, please.

**Comment by chrissimpkins** [comment]
> So, please feel free to suggest the testing approaches that you like.

Will use whatever you intend to use here for the rest of your testing.  I like pytest as suggested by @graphicore. 

> Regarding licensing, let's stick to Apache License v2.0 for the whole of the repo, please.

For new scripts, but how about typeface source files and font binaries intended for testing?  Best to hold on contributions and associated tests until you've added a standard set of test files that you intend to use for the tests?

**Comment by m4rc1e** [comment]
We've moved to Github Actions.
