### ISSUE TITLE
builder: parallelize font instantiation 

### ISSUE THREAD

**Issue by m4rc1e** [googlefonts/gftools#404]
The gftools builder has the ability to use the fontTools instancer in order to generate static fonts. I recently ran it on a family which had 360 static fonts. It took so long I could've flown to Berlin and back. Implementing this feature should be fairly trivial since it is a self contained task so I could just use the Python multiprocessing lib.

cc @davelab6

**Comment by simoncozens** [comment]
This is kinda the ninja builder ->#569.
