### ISSUE TITLE
builder: filters specified in the UFO lib are ignored

### ISSUE THREAD

**Issue by khaledhosny** [googlefonts/gftools#408]
Pre-release glyphsLib sets erase open corners filer in UFO lib, but it is ignored when using `gftools builder`, apparently because it calls fontmake `--filter` whose documentation states `The option overrides the filters specified in the UFO lib.`

**Comment by simoncozens** [comment]
We now use the `...` option to maintain the UFO filters:

https://github.com/googlefonts/gftools/blob/4077eacfada19df2674808533c3f861a5fc67724/Lib/gftools/builder/__init__.py#L336-L338
