### ISSUE TITLE
Migrate from google-apputils to absl-py

### ISSUE THREAD

**Issue by gpshead** [googlefonts/gftools#41]
Your dependency `google-apputils` is deprecated. Please migrate to `absl-py` instead.

**Comment by graphicore** [comment]
Thanks @gpshead 

context:
https://github.com/google/google-apputils/pull/15
https://github.com/google/google-apputils/issues/14

**Comment by felipesanches** [comment]
I believe the code was already migrated, but we still mention the dependency on README.md and also have it commented out on `requirements.txt`

So, I think there are the last things we need to cleanup before fixing this issue.

![Screenshot from 2021-12-17 05-29-22](https://user-images.githubusercontent.com/213676/146514001-3c5dd27a-f734-4365-a99b-d9ffed835516.png)
