### ISSUE TITLE
Builder: Pinning dependencies for reproducible builds

### ISSUE THREAD

**Issue by m4rc1e** [googlefonts/gftools#426]
At the moment, we do not pin the dependencies which are used for building fonts e.g fontmake. By not pinning we cannot guarantee that font builds are reproducible.

Before the builder arrived, we used to build fonts by writing a shell script which glued all the tools together. The font repo included a requirements.txt file which contained all the dependencies pinned to a specific version. This was generated by using the command `pip freeze > requirements.txt`. Basically, each font repo had to pin its own dependencies.

If we decide to pin font build dependencies in gftools, we cannot simply pin the dependencies in the setup.py to a specific version because these dependencies may have child dependencies which are unpinned or use the “>=“ syntax. You must literally pin the whole dependency tree.

Another downside if we do pin is that we may not be able to use the libs in this repo in other projects. Imagine if a developer requires a specific version of glyphsLib, they may not be able to use `gftools.fix` as a dependency because gftools is pinned to an older version glyphsLib. However, Afaik, it looks like we only use gftools in font repos and not in other libraries so this may not be an issue.

I just chatted to Cosimo and he has the following idea:

The builder config.yml file must specify which version of gftools has been used. If the user’s version of gftools is incorrect, they will be asked to upgrade/downgrade it.

All the dependencies in gftools setup.py and requirements.txt which are used to build the fonts are pinned to a specific version. If we want to upgrade any of these dependencies, we must bump the dependency and also cut a new release of gftools.

Cosimo, feel free to point out any inaccuracies

@anthrotype @simoncozens @RosaWagner @vv-monsalve @alerque

**Comment by simoncozens** [comment]
I think this is best handled at the font repo level, not by the builder.
