### ISSUE TITLE
Builder: decomposeTransformedComponents filter leads to incompatible glyphs

### ISSUE THREAD

**Issue by yanone** [googlefonts/gftools#440]
I ran into this `ufo2ft` bug today that has already been reported: https://github.com/googlefonts/ufo2ft/issues/507

It decomposes glyphs individually per master, not taking into account VF compatibility. In the case where a component is transformed only in one master, this leads to incompatible masters.

In the linked issue, Cosimo proposes a solution that is beyond my comprehension: 

> For the time being I recommend either decomposing those components in the source, **or adding an additional decomposeComponents pre-filter to all the VF masters with an include list containing only the problematic composite glyphs**.

I'm reporting this here in case his suggestion can be automated into `gftools builder`.

**Comment by m4rc1e** [comment]
I've already discovered this snag, https://github.com/googlefonts/gftools/issues/432#issuecomment-952020337. I outline a possible solution

**Comment by m4rc1e** [comment]
Sorry, didn't mean to close. Github auto closed it.

**Comment by simoncozens** [comment]
This was fixed in https://github.com/googlefonts/ufo2ft/pull/609.
