### ISSUE TITLE
M1 setup notes

### ISSUE THREAD

**Issue by simoncozens** [googlefonts/gftools#442]
I got a new Mac. First thing I did was installed the Developer Command Line Tools and homebrew.

Next:

* `pip3 install gftools` failed because there's no ttfautohint-py release.
* Why not? It turns out the version of `pip` and `wheel` that comes with Mac OS 12.0's system python doesn't support universal wheels. `pip3 install -U pip wheel ; pip3 install gftools` gets a lot further - ttfautohint installed, and a bunch of others too. pandas takes ages. (Why do we need pandas?)

However:

* cffsubr dies because of not having xcodebuild.
* pynacl dies with a similar `config.sub` problem to the one I was having with ttfautohint (https://github.com/fonttools/ttfautohint-py/issues/9)
* pygit2 dies with no git2.h. `brew install libgit2` doesn't help; `brew install libgit2; LIBGIT2=/opt/homebrew pip3 install pygit2` is the magic.

## Action items
- [x] Maybe we should demand the latest `wheel` and `pip` versions in our own requirements. Would that work? If not, *a README item asking M1 users to upgrade wheel/pip is essential*. (#444)
- [x] cffsubr: Probably easiest thing here is to *make sure there are cffsubr built wheels for macOS universal*. I can work on that. (https://github.com/adobe-type-tools/cffsubr/pull/20)
- [x] pygit2: Hopefully macOS universal builds will come in time. (I don't know if the new macOS runner has been rolled out for everyone yet.) But this is only used for the packager - *is it worth having a build option for Google users versus ordinary designers*? (https://github.com/libgit2/pygit2/pull/1109)
- [ ] pynacl: What's even requiring this? Something in PyGithub. They're building wheels using CI, maybe we could try and get a PR for a universal build there as well. How much do we use PyGithub? It's imported but not used in utils, *that import should probably go*. Otherwise it's used in pushstats, so another case for pushing into a Google-only option.

**Comment by simoncozens** [comment]
* I'm working on a cffsubr PR.
* Tracking issue for pygit2: https://github.com/libgit2/pygit2/issues/1102

**Comment by m4rc1e** [comment]
Thanks Simon. This is great.

I'll assist with these tasks on Monday. My M1 MBA is currently in transit so I may have it next week.

**Comment by anthrotype** [comment]
> Maybe we should demand the latest wheel and pip versions in our own requirements. Would that work?

no don't do that. Just mention in the Readme that for M1 macs they have to make sure they update their pip. Wheel should not be required, unless for building stuff from source, but we want to make sure all deps already publish precompiled binary wheel packages anyway.

**Comment by anthrotype** [comment]
> is it worth having a build option for Google users versus ordinary designers?

you can move optional stuff to `extras_require`

**Comment by simoncozens** [comment]
Yeah. We have extras for qa already. Currently going through and working out which of the dependencies we actually *use*. (Lots of imports that are unused; pylint is helping find them.)

**Comment by m4rc1e** [comment]
I've just received my shiny new M1 and have tried to install gftools.

The M1 mac I received ships with python3.8.9 and most importantly pip 21.3.1. It installed ttfa without a hitch.

The only snag I hit was pygit2 as Simon has pointed out. My current workaround is to install libgit2 using brew, `brew install libgit2`. Since we already require users to use brew to install other packages, I'm just going to add libgit2 to the brew command as a temp fix. In an ideal world, there shouldn't be a brew step at all.

**Comment by anthrotype** [comment]
does python3 get preinstalled? I would not recommend that you use whatever Apple ships with the OS, as we were already recommending people not to use the built-in python2.7 in older macOS.
also 3.8 is already relatively old. You may as well install the latest from Python.org or homebrew since you're installing it anew.

**Comment by m4rc1e** [comment]
>  I would not recommend that you use whatever Apple ships with the OS, for the same reasons we were already recommending people not to use the built-in python2.7 in older macOS.

If users are creating fresh virtualenvs for each project, I cannot see any issue since they're not adding dependencies to the preinstalled python. However, if a user forgets to enable the virtualen,v they could end up bloating their system python3 so your recommendation does make sense.

**Comment by m4rc1e** [comment]
> pynacl: What's even requiring this? Something in PyGithub.

Yes. PyGithub requires this. We're using PyGithub in order to generate reports for google/fonts, https://github.com/googlefonts/gftools/blob/main/bin/gftools-push-stats.py.

**Comment by simoncozens** [comment]
pygit2 universal wheels now available.

**Comment by anthrotype** [comment]
btw, yesteday I also published universal2 wheels for pyclipper and compreffor

**Comment by simoncozens** [comment]
This was my pynacl issue: https://github.com/pyca/pynacl/issues/657

Install will fail if you have GNU's `arch` installed and in path before Darwin's own version. `PATH="/usr/bin:$PATH" pip3 install pynacl` works in this case.

**Comment by simoncozens** [comment]
I think we basically have universal wheels for everything at this point. If not, please let me know and I'll reopen.
