### ISSUE TITLE
Why was source_type removed from fonts_public.proto?

### ISSUE THREAD

**Issue by MTCoster** [googlefonts/gftools#454]
#434 seems to have removed this field without explanation.

I'm currently trying to update homebrew-cask-font's `import_google_fonts` script to work with 0.8.x releases, but this omission is causing problems.

**Comment by m4rc1e** [comment]
Apologies. It's back now, https://github.com/googlefonts/gftools/blob/main/Lib/gftools/fonts_public.proto#L30
