### ISSUE TITLE
Include gftools-lang-support in gftools-add-font

### ISSUE THREAD

**Issue by m4rc1e** [googlefonts/gftools#456]
We had a commit which added language fields to the METADATA.pb files in google/fonts, https://github.com/google/fonts/commit/633ebadbf5280a439a49ee831ab9446093b27f62.

If we plan on adding these fields to every metadata file, wouldn't it just be easier to include this functionality in the existing gftools add-font tool? atm users need to run both add-font and lang-support.

@nathan-williams wdyt? I'll happily implement this if you want as well.

discovered in https://github.com/google/fonts/pull/4194

**Comment by RosaWagner** [comment]
Ah, lang-support should be also run on new families like… by us?

**Comment by m4rc1e** [comment]
Fixed in #460 

@RosaWagner add-font now does this automatically. No need to do anything.
