### ISSUE TITLE
gen-push-lists: Retain existing data

### ISSUE THREAD

**Issue by davelab6** [googlefonts/gftools#457]
In https://github.com/googlefonts/gftools/blob/main/bin/gftools-gen-push-lists.py I suggest the script read the current values, and retain them.

**Comment by RosaWagner** [comment]
What Marc suggests is a good idea: if a directory is in one the lists but not in the Traffic Jam project, then it should not be removed and we should have a message about it.

**Comment by m4rc1e** [comment]
Fixed in #462
