### ISSUE TITLE
gen-push-lists: Add recently changed but untagged fams as comments

### ISSUE THREAD

**Issue by davelab6** [googlefonts/gftools#458]
Similar to #457 I wonder that if there are recently merged but untagged PRs, those could be added as `# pending tags` comments to the `to_sandbox` file?

**Comment by RosaWagner** [comment]
If we look at Marc's report, 1/3 of the commits are infrasctructure, ie not aimed to send to sandbox. 

<img width="610" alt="Capture d’écran 2022-01-07 à 11 44 41" src="https://user-images.githubusercontent.com/12222436/148532778-f099aac3-1f16-4999-9238-f4d889a10716.png">

Although, I am thinking of 2 possible automations:
- Packager could assign the Traffic Jam project when opening a PR
- We could have gh-action that assign Traffic Jam and eventually some labels when a PR modifies the `ofl` and the `designers` directories.
