### ISSUE TITLE
Fix the broken links caused by 0110c90

### ISSUE THREAD

**Issue by ctrlcctrlv** [googlefonts/gftools#459]
0110c90 causes a lot of broken links.

I commented on the commit, but seems @felipesanches only looks at issues. To copy:

> I'm sorry, this change is quite bad at least for searchers, it broke links all over the place. See e.g.:
>
> https://github.com/google/fonts/blob/main/CONTRIBUTING.md
> https://github.com/googlefonts/glyphsets/issues/25
> https://github.com/googlefonts/glyphsets/issues/13
>
> I'm not asking you to do a revision, good heavens no, I'm sure it's good for your software's logical design. But to add a file to `Lib/gftools/encodings/` rather than rm whole dir, e.g. put a README.md there @felipesanches, saying what happened, then maybe you symbolic link old files to the README, or make them all contain a link to it. Otherwise you just made tons of old discussions impossible to follow. 

—https://github.com/googlefonts/gftools/commit/0110c9003f48ae79d484357075a56928d6f82d36#commitcomment-62742341

**Comment by felipesanches** [comment]
@ctrlcctrlv, I had seen your message on the commit during vacations and planned to address this in early January 2022. Sorry that I did not mention that with a small comment.

I plan to address this asap (tomorrow :-D)
