### ISSUE TITLE
Font shaping tests using the lang data?

### ISSUE THREAD

**Issue by m4rc1e** [googlefonts/gftools#465]
Since we now have [language data](https://github.com/googlefonts/gftools/tree/main/Lib/gftools/lang), it may be a nice idea to make some font shaping tests from it. It would be interesting to see whether a new font has the same/similar hb-shape output as an old font when using the lang data as input

At the very least, we should have a check to ensure that a new family doesn't produce any .notdefs for sample texts.

I guess this could exist as a separate tool in this repo or as fb checks.

If this already exists, please chuck me a url.

**Comment by felipesanches** [comment]
@simoncozens has implemented a few Font Bakery checks last year to validate expected shaping. I think what you describe here could complement that as additional Font Bakery checks in that same profile.

**Comment by simoncozens** [comment]
Yeah, it can do this, and also check for nodefs while shaping text.
