### ISSUE TITLE
[Builder] can't build non-interpolable statics fonts while fontmake does

### ISSUE THREAD

**Issue by emmamarichal** [googlefonts/gftools#472]
I have this error when I want to build a font (has 3 masters, but is not variable) with gftools builder, but I tried to export it with only Fontmake and then it worked.

    raise FontmakeError(fontmake.errors.FontmakeError: In 'CrimsonText.glyphs' -> 'master_ufo/CrimsonText.designspace': Interpolating instance 'SemiBold' failed.: Failed to generate instance of glyph 'brevecomb_hookabovecomb.case': list index out of range. (Note: the most common cause for an error here is that the glyph outlines are not point-for-point compatible or have the same starting point or are in the same order in all masters.)

Source file + config.yaml:
[CrimsonText.zip](https://github.com/googlefonts/gftools/files/7959082/CrimsonText.zip)

**Comment by simoncozens** [comment]
I just hit the same thing. The problem is we pass the interpolate flag to fontmake whether we need it or not. We should make that a config option.

**Comment by RosaWagner** [comment]
The font is now exporting without the variable font, so this issue is partly fixed.
We are having the case where a glyphs is empty in one of the master, then the builder tries to interpolate it and fail. 
Ideally, we should be able to build static fonts with incompatible masters, missing glyphs etc while the design is still WIP.

**Comment by IvanUkhov** [comment]
@simoncozens, well said here:

> We should make that a config option.

It would really help to have a dedicated option for this so as to be able to control externally, which is proposed in #657.
