### ISSUE TITLE
gftools-add-font.py: Ability to add variable fonts

### ISSUE THREAD

**Issue by m4rc1e** [googlefonts/gftools#49]
Atm, [gftools-add_font.py](https://github.com/googlefonts/tools/blob/master/bin/gftools-add-font.py) cannot generate METADATA.pb files for family dirs which contain variable fonts. I totally understand we need to implement this and we're still establishing a workflow.

```
(env)Marc:tools marc$ python bin/gftools-add-font.py /Users/marc/Documents/googlefonts/fonts/ofl/lemonada
Traceback (most recent call last):
  File "bin/gftools-add-font.py", line 220, in <module>
    app.run()
  File "/Users/marc/Documents/googlefonts/tools/env/lib/python2.7/site-packages/google/apputils/app.py", line 239, in run
    return _actual_start()
  File "/Users/marc/Documents/googlefonts/tools/env/lib/python2.7/site-packages/google/apputils/app.py", line 268, in _actual_start
    really_start()
  File "/Users/marc/Documents/googlefonts/tools/env/lib/python2.7/site-packages/google/apputils/app.py", line 221, in really_start
    sys.exit(main(argv))
  File "bin/gftools-add-font.py", line 206, in main
    metadata = _MakeMetadata(fontdir)
  File "bin/gftools-add-font.py", line 111, in _MakeMetadata
    file_family_style_weights = _FileFamilyStyleWeights(fontdir)
  File "bin/gftools-add-font.py", line 90, in _FileFamilyStyleWeights
    result = [fonts.FileFamilyStyleWeight(f) for f in files]
  File "/Users/marc/Documents/googlefonts/tools/Lib/gftools/util/google_fonts.py", line 462, in FileFamilyStyleWeight
    sw = StyleWeight(m.group(2))
  File "/Users/marc/Documents/googlefonts/tools/Lib/gftools/util/google_fonts.py", line 446, in StyleWeight
    return ('normal', _KNOWN_WEIGHTS[styleweight])
KeyError: 'VF'

```

**Comment by davelab6** [comment]
@rsheeter are you set up for taking patches from external contributors like Marc to the gftools scripts like `add_font.py`?

**Comment by m4rc1e** [comment]
@davelab6 I think its a bit too early for them. I can imagine they're still heavily refining their implementation.

**Comment by davelab6** [comment]
My concern is that `add_font.py` is developed like TruFont - in private, with updates published on Github when the developers feel like it ;)

**Comment by rsheeter** [comment]
We can take patches. Please ping about proposed changes before anything extensive. We should make sure our copy and the internal one are in sync before anyone embarks on patches.

**Comment by jhpratt** [comment]
@m4rc1e @davelab6 @rsheeter Any updates? Variable fonts has landed in the current version of all major browsers. ([source](https://caniuse.com/#feat=variable-fonts))

**Comment by m4rc1e** [comment]
@jhpratt I'm guessing this relates to the Inter UI issue on google/fonts?

We're working on converting/adding VF families to Google Fonts. Adding the necessary features to support VFs will take time.

Now if you just want to get Inter UI on Google Fonts, it must pass our linter, [Font Bakery](https://github.com/googlefonts/fontbakery). I quickly ran the fonts through and the family is producing many fails.

At some point, I'll take a look at them in more detail. Unfortunately I have other more pressing matters to inspect/fix (it is a nice family though)

**Comment by jhpratt** [comment]
Yes, that was my purpose behind posting here, but I know other fonts support it as well.

I'll take a look at the linter, though. Thanks for that.

**Comment by eliheuer** [comment]
I love this font and want to see in on Google Fonts. There is another open issues that is similar to this one, perhaps we can close one and merge these conversations: https://github.com/googlefonts/gftools/issues/93

I can start looking at `fontbakery` issues with this over the weekend, I had no problems building the variable font with `fontmake` yesterday.
