### ISSUE TITLE
packager: --no-source strips out language comments

### ISSUE THREAD

**Issue by m4rc1e** [googlefonts/gftools#494]
@yanone noticed that language comments are stripped out if the packager is called with `--no-source`. I'm guessing the issue is in https://github.com/googlefonts/gftools/blob/main/Lib/gftools/packager.py#L1461-L1493.

I will get this fixed by the end of the day.

Also, we don't need to call the packager any more with `--no-source` because the source field has been added to the protobuf file, https://github.com/googlefonts/gftools/blob/main/Lib/gftools/fonts_public.proto#L23

**Comment by m4rc1e** [comment]
Yep, I've pushed some prs which didn't include the flag and there wasn't any issues. I'll strip it out if you'd like?

**Comment by graphicore** [comment]
Yes, sure. I'm happy when it's gone.

**Comment by RosaWagner** [comment]
Which PR @m4rc1e ? We can ask confirmation to the eng-team to be sure

**Comment by m4rc1e** [comment]
Fredoka One, https://github.com/google/fonts/pull/4170/files#diff-6f60b90578b606c1fac4886bd77a11baee5eef7c042f2cec54c0a526b282858bR29-R32

Went through just fine.

**Comment by RosaWagner** [comment]
This should be stripped out too then (if the field is in METADATA.pb)

```
🔥 FAIL: Check upstream.yaml file contains all required fields
[com.google.fonts/check/repo/upstream_yaml_has_required_fields](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/repo/upstream_yaml_has_required_fields)
--- Rationale ---
If a family has been pushed using the gftools packager, we must check that all
the required fields in the upstream.yaml file have been populated.
🔥 FAIL The upstream.yaml file is missing the following fields: ['repository_url'] [code: missing-fields]
```
