### ISSUE TITLE
Devanagari: Issue with `_ra-deva` glyphs when built with gftools

### ISSUE THREAD

**Issue by tallchai** [googlefonts/gftools#497]
I have developed a Devanagari font in Glyphs app and using `gftools builder` to build the font (from the glyphs file).
These issues are with conjunct glyphs that end with `_ra-deva`. Examples: ka_ra-deva, kha_ra-deva, tta_ra-deva etc.
The issue is specifically tied to the way the _matras_ (Devanagari marks) show up for them.

✅ Correct: What the look like when exported from **GlyphsApp**
<img width="597" alt="Screen Shot 2022-02-17 at 12 48 17 PM" src="https://user-images.githubusercontent.com/73443155/154540654-bc159eae-5294-4ada-a1ad-e1c64e7f418f.png">

❌ Incorrect: What they look like when built with **gftools**:
<img width="622" alt="Screen Shot 2022-02-17 at 12 40 52 PM" src="https://user-images.githubusercontent.com/73443155/154540739-f8ab34a1-ce98-4454-a30e-92b3557f3364.png">

I tried adding anchors explicitly to the `_ra-deva` glyphs (although it is not needed), but it did not work.

Here's the builder.yaml file:
```
sources:
  - source.glyphs
axisOrder:
    - wght
    - cntr
outputDir: "../fonts"
buildStatic: true
buildVariable: true
buildTTF: true
buildOTF: false
buildWebfont: false
```

Thanks

**Comment by simoncozens** [comment]
Here’s my betting: https://github.com/googlefonts/glyphsLib/issues/756

**Comment by simoncozens** [comment]
(But without seeing the font it’s hard to see.)

**Comment by tallchai** [comment]
@simoncozens That is the issue.
I set the **subcategory** for those glyphs from "Ligature" to "Other".
That fixes the issue for most of them. But there are some of them like **ह्य** or **द्य** that do not work.

**Comment by tallchai** [comment]
@simoncozens Checked with schriftgestalt regarding this problem on the linked issue [here](https://github.com/googlefonts/glyphsLib/issues/756).

This does not look like an issue with GlyphsApp.
I have summarized this issue again [here](https://github.com/googlefonts/glyphsLib/issues/756#issuecomment-1061259826).

Wondering if there was any fix found for this? 
Thanks :)

**Comment by simoncozens** [comment]
I'm afraid I don't understand that - when you say you manually edit the cjct feature to make it work... I assume the cjct feature is always manually edited! Are you saying that with the glyphs defined as Ligature, Glyphs.app can automatically generate the cjct feature for you, but then when you compile that font with fontmake (gftools, ufo2ft, whatever), the mark attachment for the ligature glyphs goes wrong? I can imagine that making sense, because ufo2ft will probably try to do a mark-to-ligature attachment on a ligature glyph, which is not actually what you need here.

**Comment by simoncozens** [comment]
I'm sorry I didn't reply to this. I will need to look into how Glyphs.app generates cjct features. But at the same time, this is not actually related to gftools, and is best discussed under that horrible ufo2ft issue.
