### ISSUE TITLE
hyperglot is a GPLv3 dependency

### ISSUE THREAD

**Issue by felipesanches** [googlefonts/gftools#498]
see: https://github.com/felipesanches/gflanguages/pull/4

**Comment by vv-monsalve** [comment]
> see: https://github.com/felipesanches/gflanguages/pull/4

This link is broken

**Comment by felipesanches** [comment]
here's the new place where that issue lives nowadays :-D
https://github.com/googlefonts/lang/pull/4

**Comment by moyogo** [comment]
@felipesanches this can be closed, no? The dependency has been removed afaik.

**Comment by simoncozens** [comment]
No, we still use it in `Lib/gftools/scripts/lang.py` and `Lib/gftools/util/google_fonts.py`.
