### ISSUE TITLE
Simple Python client for Google Fonts 

### ISSUE THREAD

**Issue by m4rc1e** [googlefonts/gftools#50]
I've noticed recurring patterns across our tooling. A lot of them involve downloading families from Google Fonts. It would be fab to have a simple Python api for this stuff.

```
googlefonts = GoogleFonts()

googlefonts.has_family('Roboto')
family = googlefonts.download('Roboto')
```

It would be nice to have this code in one place and have it polished.

**Comment by davelab6** [comment]
This repo is pretty wooly. That sounds good to me but should be balanced
against the other important stuff on our roadmap.

**Comment by simoncozens** [comment]
We now have this!
