### ISSUE TITLE
builder: fails silenty

### ISSUE THREAD

**Issue by yanone** [googlefonts/gftools#506]
I’ve noticed the builder to output error messages but then complete the process with the message `INFO:GFBuilder:Building variable completed. All done!` as well as exit status `0`, which confuses both the human as well as the machine.

Example:
```
INFO:fontmake.font_project:Building master UFOs and designspace from Glyphs source
INFO:fontmake.font_project:Building variable font ../fonts/variable/Arima-VF.ttf
ERROR:GFBuilder:Could not build variable font: In 'Arima.glyphs' -> 'master_ufo/Arima.designspace': Generating fonts from Designspace failed: Base master not found.
INFO:GFBuilder:Building variable completed. All done!
INFO:GFBuilder:Removing auxiliary dirs/files {'master_ufo'}
```

I believe a real measurable error should be thrown.
Side effect is that also the UFO folders get cleaned up (unless explicitly instructed not to in `builder.yaml`), but the files are necessary for debugging.

**Comment by RosaWagner** [comment]
Already opened an issue: https://github.com/googlefonts/gftools/issues/503

**Comment by yanone** [comment]
Oh, sorry. Closing because duplicate
