### ISSUE TITLE
gftools-add-font.py METADATA: Generate registry_default_overrides data when needed

### ISSUE THREAD

**Issue by davelab6** [googlefonts/gftools#509]
Montagu Slab is an example of this, where the optical size axis is defined like [this](https://github.com/google/fonts/blob/2fba0d68602b7eb3374d030c1c34939de56023f9/ofl/montaguslab/METADATA.pb#L19-L23):

```
axes {
  tag: "opsz"
  min_value: 16.0
  max_value: 144.0
}
```

But since the [opsz default in the axis registry](https://github.com/google/fonts/blob/2fba0d68602b7eb3374d030c1c34939de56023f9/axisregistry/optical_size.textproto#L8) is 14, that won't work for the range 16..144, and therefore in the METADATA there's an `registry_default_overrides` property after the set of `axes` defs, [like this](https://github.com/google/fonts/blob/2fba0d68602b7eb3374d030c1c34939de56023f9/ofl/montaguslab/METADATA.pb#L29-L31):

```
registry_default_overrides {
  key: "opsz"
  value: 144.0
}
```

The gftools-add-font.py should generate this, for the Roboto Flex release, where it will be needed for most of the axes.

**Comment by m4rc1e** [comment]
SGTM. On it.
