### ISSUE TITLE
Use external `axisregistry` module

### ISSUE THREAD

**Issue by felipesanches** [googlefonts/gftools#515]
Similar to #510, now we have a python module for handling data from the Google Fonts Axis Registry.

https://pypi.org/project/axisregistry/

**Comment by m4rc1e** [comment]
However, Nate clearly knows it exists ;-)

<img width="925" alt="Screenshot 2022-03-10 at 09 56 17" src="https://user-images.githubusercontent.com/7525512/157637428-f83bd219-883f-47a3-8a79-d72705c60c6d.png">

Guess it may just be a case of redirecting people instead.
