### ISSUE TITLE
Fontbakery error when it's run with gftools qa

### ISSUE THREAD

**Issue by emmamarichal** [googlefonts/gftools#518]
Hello!

I have this error when I run `gftools qa -f *.ttf --fontbakery` 
I tested it on several fonts, it doesn't work, except when I run fontbakery without gftools qa. (with `fontbakery check-googlefonts *.ttf`). I've updated all the tools, including the latest one from gftools.

> Traceback (most recent call last):
>   File "/Users/marichalemma/Google/env/bin/gftools-qa.py", line 487, in <module>
>     main()
>   File "/Users/marichalemma/Google/env/bin/gftools-qa.py", line 430, in main
>     family_on_gf = Google_Fonts_has_family(family_name)
>   File "/Users/marichalemma/Google/env/lib/python3.9/site-packages/gftools/utils.py", line 57, in Google_Fonts_has_family
>     data = json.loads(r.text[5:])
>   File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/__init__.py", line 346, in loads
>     return _default_decoder.decode(s)
>   File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/decoder.py", line 337, in decode
>     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
>   File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/decoder.py", line 355, in raw_decode
>     **raise JSONDecodeError("Expecting value", s, err.value) from None
> json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)**

Thanks!

**Comment by m4rc1e** [comment]
Thanks for this!

It appears that the endpoint is finally valid json! they used to include a few characters before we'd need to remove.

Lemme make a fix asap.

cc @felipesanches this may affect you in fb as well.

**Comment by m4rc1e** [comment]
I've just cut v0.9.2. Please upgrade gftools and you should be good.
