### ISSUE TITLE
Module Found Error for `gftools.axisreg` under v0.9.2

### ISSUE THREAD

**Issue by vv-monsalve** [googlefonts/gftools#523]
Doing a PR after upgrading gftools to `v0.9.2` is reporting the following error preventing the PR from being performed:

`ModuleNotFoundError: No module named 'gftools.axisreg'`

This is the complete output text: [My-Sould-PR.txt](https://github.com/googlefonts/gftools/files/8334737/My-Sould-PR.txt)

I've done a test [PR](https://github.com/google/fonts/pull/4399) under a venv with only gftools `v0.9.0` (no gftools[qa]) and the PR worked, the files were included ok but the QA action was not triggered. `This branch has not been deployed`
Would it be related to the above?

**Comment by RosaWagner** [comment]
Same happens if we run `gftools add-font` alone

**Comment by vv-monsalve** [comment]
> I've done a test [PR](https://github.com/google/fonts/pull/4399) under a venv with only gftools `v0.9.0` (no gftools[qa]) and the PR worked, the files were included ok but the QA action was not triggered. `This branch has not been deployed`
> Would it be related to the above?

I've redone the PR with `gftools 0.090` + `[qa]` and after a few attempts, it finally work. So the QA action seems to not be an issue anymore.

**Comment by m4rc1e** [comment]
try `pip install axisregistry`

**Comment by m4rc1e** [comment]
Thanks Felipe. On it now.

**Comment by m4rc1e** [comment]
Fixed in https://github.com/googlefonts/gftools/releases/tag/v0.9.4
