### ISSUE TITLE
Use googlefonts/lang for sample text in gen-html

### ISSUE THREAD

**Issue by simoncozens** [googlefonts/gftools#533]
I'm using a googlefonts-project-template fork for Noto, and want to build up some proof sheets using `make proof`. For many scripts this won't work because the scripts aren't in `uhdr_all.txt`. However, we do have sample texts for each language in the textprotos.

I'm be interested in making a PR which uses the languages repository to grab a sample text for a font if nothing could not be found in the uhdr. How does that sound?

**Comment by m4rc1e** [comment]
SGTM. The current implementation is very basic so I'd welcome any improvements,.

**Comment by felipesanches** [comment]
that's great! ;-)
