### ISSUE TITLE
[gen-push-lists] path of lang files

### ISSUE THREAD

**Issue by RosaWagner** [googlefonts/gftools#549]
weither it is for Axis Registry or Lang directories, changes to these dir should result in listing the modified files and not the dir only (so not like ofl and catalog).

Eg:
`lang/Lib/gflanguages/data/languages/ar_Arab.textproto`
instead of 
`lang/Lib/gflanguages/data/languages`

and 
`Axisregistry/Lib/axisregistry/data/softness.textproto`
instead of
`Axisregistry/Lib/axisregistry/data/`

**Comment by m4rc1e** [comment]
> changes to these dir should result in listing the modified files and not the dir only (so not like ofl and catalog).

I don't list the dirname for .textprotos because I saw gf eng including the full path for each .textproto file.

@nathan-williams Is it ok for us just to list the dirname for updated .textproto files? or shall we continue listing the full path for each .textproto file?

**Comment by RosaWagner** [comment]
Rod corrected the last sandbox file, which gives us the proper expected path:
Eg:
`lang/languages/ar_Arab.textproto`

**Comment by RosaWagner** [comment]
Evan says:
Regarding the language paths, they should look like:

lang/languages/ar_Arab.textproto

The way I think about it is that the paths in to_production.txt are neutral as they are neither GitHub or Google paths. The code that processes the to_production.txt file recognizes the "lang/" prefix and then uses the rest of the path to build the GitHub and Google paths.  Using the ar_Arab.textproto from above, those become:

GitHub path: lang/Lib/gflanguages/data/languages/ar_Arab.textproto
Google path: googledata/fonts/lang/languages/ar_Arab.textproto



--> Shall we update the push script and the CI @m4rc1e ?

**Comment by RosaWagner** [comment]
The CI in google/fonts fails correctly, but gen-push-lists still generate the wrong path. Unless there is PR open about that?

**Comment by vv-monsalve** [comment]
> Rod corrected the last sandbox file, which gives us the proper expected path: Eg: `lang/languages/ar_Arab.textproto`

This is still happening on `gftools 0.9.15` @m4rc1e

**Comment by vv-monsalve** [comment]
Now that well have the `pull subtree` [command to update axisregystry](https://googlefonts.github.io/gf-guide/googlefonts.html#axis-registry) and lang directories in google/fonts, we'll need to add a cleaning for other repeated paths.

E.g. [Sandbox list Aug 18](https://github.com/google/fonts/commit/605a98205e6d3da673b55164de9bbd3fbb26f343) after Chris update performed on [#5072](https://github.com/google/fonts/pull/5072). The only intended file here is the inclusion of the `element_grid.textproto`

```
axisregistry # https://github.com/google/fonts/pull/5072
axisregistry/.github/workflows # https://github.com/google/fonts/pull/5072
axisregistry/Lib/axisregistry # https://github.com/google/fonts/pull/5072
axisregistry/Lib/axisregistry/data/element_grid.textproto # https://github.com/google/fonts/pull/5072
axisregistry/tests # https://github.com/google/fonts/pull/5072
axisregistry/tests/data # https://github.com/google/fonts/pull/5072
```

**Comment by vv-monsalve** [comment]
Paths confirmed from [Garret's fix](https://github.com/google/fonts/pull/5147) and [Chris's PR](https://github.com/googlefonts/gftools/issues/603)

- Axes  `axisregistry/[AXIS].textproto`
- Languages. `lang/languages/[LANG].textproto`
