### ISSUE TITLE
gftools fix-fsselection doesn't work

### ISSUE THREAD

**Issue by emmamarichal** [googlefonts/gftools#553]
Hello! 
I wanted to add `usetypometrics` (bit7) to this font: https://github.com/silnrsi/font-taiheritagepro, using `gftools fix-fsselection` but it doesn't work. I've also tried on this font: https://github.com/silnrsi/font-abyssinica, same issue.
I have no error, but the command seems to have no effect on the font.

```
gftools fix-fsselection /Users/marichalemma/Downloads/SIL/SIL_To\ do/TaiHeritagePro-test/TaiHeritagePro-Regular.ttf --usetypometrics
| filename                   | fsSelection       |
|:---------------------------|:------------------|
| TaiHeritagePro-Regular.ttf | 00000000 01000000 |
```

Any ideas? 
Thanks!

**Comment by emmamarichal** [comment]
Thanks, but I have this white space now:

```
gftools fix-fsselection /Users/marichalemma/Downloads/SIL/SIL_To\ do/TaiHeritagePro-test/TaiHeritagePro-Regular.ttf --autofix --usetypometrics

(env) MBPdeMarichal2:~ marichalemma$
```

**Comment by m4rc1e** [comment]
`clear` may help :-)

**Comment by m4rc1e** [comment]
@emmamarichal did `clear` and `--autofix` solve this?

**Comment by emmamarichal** [comment]
It doesn't change anything... it's weird

**Comment by emmamarichal** [comment]
Thanks @m4rc1e, just tested, it works! :)
