### ISSUE TITLE
[Variable Fonts] Post processing script

### ISSUE THREAD

**Issue by m4rc1e** [googlefonts/gftools#56]
We need to create a script which adds the following post processing steps.

- STAT table generation
- Dummy dsig table generation
- Possible hinting touchups/automation

Fontmake can't do these steps yet. I've already filed issues for the dsig and stat table in the fontmake repo.

I almost have a STAT and nametable which equals our static ttf menu naming setup, https://groups.google.com/d/msg/googlefonts-discuss/K2_FumuWLB8/_pgdNXtwAAAJ

**Comment by davelab6** [comment]
Why not contribute upstream to fontmake? :)

**Comment by m4rc1e** [comment]
Time mainly.

The devs of fontmake still don't know where to store the necessary data to gen fonts with good STAT tables, https://github.com/googlei18n/fontmake/issues/436.

Since I'm finally able to make my own STATs by hand, I'd like to script this for the time being. I don't have time to write an implementation in fontmake or its sibling libs which implement the table properly for all edgecases.

**Comment by davelab6** [comment]
Makes sense. Sounds good!
