### ISSUE TITLE
fix-dsig disappeared in v0.9.0

### ISSUE THREAD

**Issue by rsms** [googlefonts/gftools#564]
Upgraded gftools today and my build broke as the "fix-dsig" subcommand disappeared in v0.9.0.

- [bin/gftools-fix-dsig.py v0.8.8 (found)](https://github.com/googlefonts/gftools/blob/v0.8.8/bin/gftools-fix-dsig.py)
- [bin/gftools-fix-dsig.py v0.9.0 (missing)](https://github.com/googlefonts/gftools/blob/v0.9.0/bin/gftools-fix-dsig.py)

I've looked through the list of subcommands and part of the source code of v0.9x to see if it changed name, but it seems it was simply removed (the subcommand; the implementation code is still there in the lib dir.)

**Comment by m4rc1e** [comment]
We've stopped including dummy dsig tables in our fonts, https://github.com/googlefonts/fontbakery/issues/3398. I removed this script in, https://github.com/googlefonts/gftools/pull/501. Can readd it and include a deprecated message if that will help you? However, I suggest just ignoring this table completely.

**Comment by rsms** [comment]
Ah, thanks for the info. It was added to the Inter build process to satisfy Google Fonts, so I guess I can remove that step now :•)

**Comment by ctrlcctrlv** [comment]
This should _not_ have been closed without updating the documentation. This just caused a build failure for me in a font that was working months ago.

I recommend…

* Removing reference to `fix-dsig` on <https://github.com/googlefonts/gftools#tool-usage-examples> (`README.md`).
* Either:
  * Keeping around a help item for it (I don't know how to do this thus haven't opened PR) saying it's deprecated and to drop it from scripts
  * Adding it back, warning users Google no longer requires it but it remains as perhaps they want it …
