### ISSUE TITLE
Don't kill MVAR table in fix-font

### ISSUE THREAD

**Issue by simoncozens** [googlefonts/gftools#580]
We've re-thought the fontbakery check that complained about the MVAR table (https://github.com/googlefonts/fontbakery/issues/3400) but we still drop the MVAR table in fix-font. The problem with this is that fonts instantiated from a VF with no MVAR table have the wrong vertical metrics.

**Comment by m4rc1e** [comment]
I totally agree that we now shouldn't drop this table at all. However, we're still using browserstack which uses old browsers which are affected by the presence of an MVAR table. I plan to move us away from bstack and use github actions with headless chrome on a platform matrix in q3/q4, https://github.com/googlefonts/gftools/pull/420

Related https://github.com/googlefonts/fontbakery/issues/3413
