### ISSUE TITLE
Builder familyName not working

### ISSUE THREAD

**Issue by guidoferreyra** [googlefonts/gftools#585]
I have a project that is built with GF Tools builder using a config.yaml file, and when the font is built it is not using the familyName from the config but the designspace file name. Is this intended or am I missing something?

Here is my config:

```
sources:
  - myFont.designspace
  - myFont-Italic.designspace
axisOrder:
  - wdth
  - wght
  - ital
familyName: MyFontBeta
```

**Comment by simoncozens** [comment]
This is intended; the `familyName` option is not intended to change the family name but to inform gftools-builder of the family name. It's then passed to `fontmake`, where it *can* change the family name for Glyphs sources, but not for designspace sources. If you think fontmake should change the family name of DS sources when the `--family-name` option is passed, I would recommend raising an issue in the fontmake repo.

**Comment by guidoferreyra** [comment]
Hi Simon, thanks for the clarification! Maybe what you said worth to be mentioned here?
https://github.com/googlefonts/gftools/blob/e8007261c84245542aa5e820a8330ae5cfde9d89/Lib/gftools/builder/__init__.py#L96
