### ISSUE TITLE
gen-html: Use gflanguages for genning sample texts

### ISSUE THREAD

**Issue by m4rc1e** [googlefonts/gftools#587]
Atm, we currently generate sample texts by using the Universal Declaration of Human Rights. Instead, we should be using the gflanguages [repo](https://github.com/googlefonts/lang) since it contains more languages.

cc @twardoch

**Comment by simoncozens** [comment]
You might find this code useful: https://github.com/simoncozens/font-engineering/blob/master/gimmesometext

**Comment by m4rc1e** [comment]
Cool thank you!

**Comment by simoncozens** [comment]
Fixed in #534.
