### ISSUE TITLE
New script: which characters in a TTF are not in any GF `.nam` subset?

### ISSUE THREAD

**Issue by felipesanches** [googlefonts/gftools#6]
@davelab6 said:

> Please provide a script to tell us which characters in a TTF are not in any GF .nam subset.

Originally requested at:
https://github.com/googlefonts/fontbakery/issues/1466

**Comment by felipesanches** [comment]
I've just implemented this and will send a pull request

**Comment by felipesanches** [comment]
@davelab6 You can test it by cloning this repo and running, from within the root dir the `test_gf_coverage.py` script.

I'll later package this, according to #3 and https://github.com/googlefonts/fontbakery/issues/1639

**Comment by felipesanches** [comment]
PLease let me know if you need further improvements to the script.

**Comment by felipesanches** [comment]
@davelab6 Reopen if you need anything else here.

**Comment by felipesanches** [comment]
Also, after packaging, the script will be available as a subcommand (just like we do in FontBakery). Something like this:

`gftools test-gf-coverage filename.ttf`

**Comment by davelab6** [comment]
$ for i in ~/fonts/*/*/*ttf; do python2 ./test_gf_coverage.py $i; done

...

The following codepoints are
 missing on /Users/dcrossland/fonts/apache/cousine/Cousine-Italic.ttf:

0x0132 0x0133 0x0149 0x017F 0x0180 0x0181 0x0182 0x0183 0x0184 0x0185 0x0186 0x0187 0x0188 0x0189 0x018A 0x018B 0x018C 0x018D 0x018E 0x0190 0x0191 0x0193 0x0194 0x0195 0x0196 0x0197 0x0198 0x0199 0x019A 0x019B 0x019C 0x019D 0x019E 0x019F 0x01A2 0x01A3 0x01A4 0x01A5 0x01A6 0x01A7 0x01A8 0x01A9 0x01AA 0x01AB 0x01AC 0x01AD 0x01AE 0x01B1 0x01B2 0x01B3 0x01B4 0x01B5 0x01B6 0x01B7 0x01B8 0x01B9 0x01BA 0x01BB 0x01BC 0x01BD 0x01BE 0x01BF 0x01C0 0x01C1 0x01C2 0x01C3 0x01CD 0x01CE 0x01CF 0x01D0 0x01D1 0x01D2 0x01D3 0x01D4 0x01D5 0x01D6 0x01D7 0x01D8 0x01D9 0x01DA 0x01DB 0x01DC 0x01DD 0x01DE 0x01DF 0x01E0 0x01E1 0x01E2 0x01E3 0x01E4 0x01E5 0x01E8 0x01E9 0x01EC 0x01ED 0x01EE 0x01EF 0x01F0 0x01F1 0x01F2 0x01F3 0x01F4 0x01F5 0x01F6 0x01F7 0x01F8 0x01F9 0x021C 0x021D 0x021E 0x021F 0x0220 0x0221 0x0222 0x0223 0x0224 0x0225 0x0226 0x0227 0x0228 0x0229 0x022E 0x022F 0x0234 0x0235 0x0236 0x0238 0x0239 0x023A 0x023B 0x023C 0x023D 0x023E 0x023F 0x0240 0x0241 0x0242 0x0243 0x0244 0x0245 0x0246 0x0247 0x0248 0x0249 0x024A 0x024B 0x024C 0x024D 0x024E 0x024F 0x0250 0x0251 0x0252 0x0253 0x0254 0x0255 0x0256 0x0257 0x0258 0x025A 0x025B 0x025C 0x025D 0x025E 0x025F 0x0260 0x0261 0x0262 0x0263 0x0264 0x0265 0x0266 0x0267 0x0268 0x0269 0x026A 0x026B 0x026C 0x026D 0x026E 0x026F 0x0270 0x0271 0x0272 0x0273 0x0274 0x0275 0x0276 0x0277 0x0278 0x0279 0x027A 0x027B 0x027C 0x027D 0x027E 0x027F 0x0280 0x0281 0x0282 0x0283 0x0284 0x0285 0x0286 0x0287 0x0288 0x0289 0x028A 0x028B 0x028C 0x028D 0x028E 0x028F 0x0290 0x0291 0x0292 0x0293 0x0294 0x0295 0x0296 0x0297 0x0298 0x0299 0x029A 0x029B 0x029C 0x029D 0x029E 0x029F 0x02A0 0x02A1 0x02A2 0x02A3 0x02A4 0x02A5 0x02A6 0x02A7 0x02A8 0x02A9 0x02AA 0x02AB 0x02AC 0x02AD 0x02AE 0x02AF 0x02B0 0x02B1 0x02B2 0x02B3 0x02B4 0x02B5 0x02B6 0x02B7 0x02B8 0x02BD 0x02C0 0x02C1 0x02C2 0x02C3 0x02C4 0x02C5 0x02CD 0x02CE 0x02CF 0x02D0 0x02D1 0x02D2 0x02D3 0x02D4 0x02D5 0x02D6 0x02D7 0x02DE 0x02DF 0x02E0 0x02E1 0x02E2 0x02E3 0x02E4 0x02E5 0x02E6 0x02E7 0x02E8 0x02E9 0x02EA 0x02EB 0x02EC 0x02ED 0x02EE 0x02EF 0x02F0 0x02F1 0x02F2 0x02F3 0x02F4 0x02F5 0x02F6 0x02F7 0x02F8 0x02F9 0x02FA 0x02FB 0x02FC 0x02FD 0x02FE 0x02FF 0x0305 0x030D 0x030E 0x0310 0x0313 0x0314 0x0315 0x0316 0x0317 0x0318 0x0319 0x031A 0x031C 0x031D 0x031E 0x031F 0x0320 0x0321 0x0322 0x0325 0x0329 0x032A 0x032B 0x032C 0x032D 0x032F 0x0330 0x0332 0x0333 0x0334 0x0336 0x0337 0x0338 0x0339 0x033A 0x033B 0x033C 0x033D 0x033E 0x033F 0x0340 0x0341 0x0342 0x0343 0x0344 0x0345 0x0346 0x0347 0x0348 0x0349 0x034A 0x034B 0x034C 0x034D 0x034E 0x034F 0x0350 0x0351 0x0352 0x0353 0x0354 0x0355 0x0356 0x0357 0x0358 0x0359 0x035A 0x035B 0x035C 0x035D 0x035E 0x035F 0x0360 0x0361 0x0362 0x0363 0x0364 0x0365 0x0366 0x0367 0x0368 0x0369 0x036A 0x036B 0x036C 0x036D 0x036E 0x036F 0x0374 0x0375 0x037A 0x037B 0x037C 0x037D 0x037E 0x0384 0x0385 0x0386 0x0387 0x0388 0x0389 0x038A 0x038C 0x038E 0x038F 0x0390 0x0391 0x0392 0x0393 0x0394 0x0395 0x0396 0x0397 0x0398 0x0399 0x039A 0x039B 0x039C 0x039D 0x039E 0x039F 0x03A0 0x03A1 0x03A3 0x03A4 0x03A5 0x03A6 0x03A7 0x03A8 0x03A9 0x03AA 0x03AB 0x03AC 0x03AD 0x03AE 0x03AF 0x03B0 0x03B1 0x03B2 0x03B3 0x03B4 0x03B5 0x03B6 0x03B7 0x03B8 0x03B9 0x03BA 0x03BB 0x03BC 0x03BD 0x03BE 0x03BF 0x03C1 0x03C2 0x03C3 0x03C4 0x03C5 0x03C6 0x03C7 0x03C8 0x03C9 0x03CA 0x03CB 0x03CC 0x03CD 0x03CE 0x03D0 0x03D1 0x03D2 0x03D3 0x03D4 0x03D5 0x03D6 0x03D7 0x03D8 0x03D9 0x03DA 0x03DB 0x03DC 0x03DD 0x03DE 0x03DF 0x03E0 0x03E1 0x03E2 0x03E3 0x03E4 0x03E5 0x03E6 0x03E7 0x03E8 0x03E9 0x03EA 0x03EB 0x03EC 0x03ED 0x03EE 0x03EF 0x03F0 0x03F1 0x03F2 0x03F3 0x03F4 0x03F5 0x03F6 0x03F7 0x03F8 0x03F9 0x03FA 0x03FB 0x03FC 0x03FD 0x03FE 0x03FF 0x0400 0x0401 0x0402 0x0403 0x0404 0x0405 0x0406 0x0407 0x0408 0x0409 0x040A 0x040B 0x040C 0x040D 0x040E 0x040F 0x0410 0x0411 0x0412 0x0413 0x0414 0x0415 0x0416 0x0417 0x0418 0x0419 0x041A 0x041B 0x041C 0x041D 0x041E 0x041F 0x0420 0x0421 0x0422 0x0423 0x0424 0x0425 0x0426 0x0427 0x0428 0x0429 0x042A 0x042B 0x042C 0x042D 0x042E 0x042F 0x0430 0x0431 0x0432 0x0433 0x0434 0x0435 0x0436 0x0437 0x0438 0x0439 0x043A 0x043B 0x043C 0x043D 0x043E 0x043F 0x0440 0x0441 0x0442 0x0443 0x0444 0x0445 0x0446 0x0447 0x0448 0x0449 0x044A 0x044B 0x044C 0x044D 0x044E 0x044F 0x0450 0x0451 0x0452 0x0453 0x0454 0x0455 0x0456 0x0457 0x0458 0x0459 0x045A 0x045B 0x045C 0x045D 0x045E 0x045F 0x0460 0x0461 0x0462 0x0463 0x0464 0x0465 0x0466 0x0467 0x0468 0x0469 0x046A 0x046B 0x046C 0x046D 0x046E 0x046F 0x0470 0x0471 0x0472 0x0473 0x0474 0x0475 0x0476 0x0477 0x0478 0x0479 0x047A 0x047B 0x047C 0x047D 0x047E 0x047F 0x0480 0x0481 0x0482 0x0483 0x0484 0x0485 0x0486 0x0487 0x0488 0x0489 0x048A 0x048B 0x048C 0x048D 0x048E 0x048F 0x0490 0x0491 0x0492 0x0493 0x0494 0x0495 0x0496 0x0497 0x0498 0x0499 0x049A 0x049B 0x049C 0x049D 0x049E 0x049F 0x04A0 0x04A1 0x04A2 0x04A3 0x04A4 0x04A5 0x04A6 0x04A7 0x04A8 0x04A9 0x04AA 0x04AB 0x04AC 0x04AD 0x04AE 0x04AF 0x04B0 0x04B1 0x04B2 0x04B3 0x04B4 0x04B5 0x04B6 0x04B7 0x04B8 0x04B9 0x04BA 0x04BB 0x04BC 0x04BD 0x04BE 0x04BF 0x04C0 0x04C1 0x04C2 0x04C3 0x04C4 0x04C5 0x04C6 0x04C7 0x04C8 0x04C9 0x04CA 0x04CB 0x04CC 0x04CD 0x04CE 0x04CF 0x04D0 0x04D1 0x04D2 0x04D3 0x04D4 0x04D5 0x04D6 0x04D7 0x04D8 0x04D9 0x04DA 0x04DB 0x04DC 0x04DD 0x04DE 0x04DF 0x04E0 0x04E1 0x04E2 0x04E3 0x04E4 0x04E5 0x04E6 0x04E7 0x04E8 0x04E9 0x04EA 0x04EB 0x04EC 0x04ED 0x04EE 0x04EF 0x04F0 0x04F1 0x04F2 0x04F3 0x04F4 0x04F5 0x04F6 0x04F7 0x04F8 0x04F9 0x04FA 0x04FB 0x04FC 0x04FD 0x04FE 0x04FF 0x0500 0x0501 0x0502 0x0503 0x0504 0x0505 0x0506 0x0507 0x0508 0x0509 0x050A 0x050B 0x050C 0x050D 0x050E 0x050F 0x0510 0x0511 0x0512 0x0513 0x051A 0x051B 0x051C 0x051D 0x0591 0x0592 0x0593 0x0594 0x0595 0x0596 0x0597 0x0598 0x0599 0x059A 0x059B 0x059C 0x059D 0x059E 0x059F 0x05A0 0x05A1 0x05A2 0x05A3 0x05A4 0x05A5 0x05A6 0x05A7 0x05A8 0x05A9 0x05AA 0x05AB 0x05AC 0x05AD 0x05AE 0x05AF 0x05B0 0x05B1 0x05B2 0x05B3 0x05B4 0x05B5 0x05B6 0x05B7 0x05B8 0x05B9 0x05BA 0x05BB 0x05BC 0x05BD 0x05BE 0x05BF 0x05C0 0x05C1 0x05C2 0x05C3 0x05C4 0x05C5 0x05C6 0x05C7 0x05D0 0x05D1 0x05D2 0x05D3 0x05D4 0x05D5 0x05D6 0x05D7 0x05D8 0x05D9 0x05DA 0x05DB 0x05DC 0x05DD 0x05DE 0x05DF 0x05E0 0x05E1 0x05E2 0x05E3 0x05E4 0x05E5 0x05E6 0x05E7 0x05E8 0x05E9 0x05EA 0x05F0 0x05F1 0x05F2 0x05F3 0x05F4 0x1D00 0x1D01 0x1D02 0x1D03 0x1D04 0x1D05 0x1D06 0x1D07 0x1D08 0x1D09 0x1D0A 0x1D0B 0x1D0C 0x1D0D 0x1D0E 0x1D0F 0x1D10 0x1D11 0x1D12 0x1D13 0x1D14 0x1D15 0x1D16 0x1D17 0x1D18 0x1D19 0x1D1A 0x1D1B 0x1D1C 0x1D1D 0x1D1E 0x1D1F 0x1D20 0x1D21 0x1D22 0x1D23 0x1D24 0x1D25 0x1D26 0x1D27 0x1D28 0x1D29 0x1D2A 0x1D2B 0x1D2C 0x1D2D 0x1D2E 0x1D2F 0x1D30 0x1D31 0x1D32 0x1D33 0x1D34 0x1D35 0x1D36 0x1D37 0x1D38 0x1D39 0x1D3A 0x1D3B 0x1D3C 0x1D3D 0x1D3E 0x1D3F 0x1D40 0x1D41 0x1D42 0x1D43 0x1D44 0x1D45 0x1D46 0x1D47 0x1D48 0x1D49 0x1D4A 0x1D4B 0x1D4C 0x1D4D 0x1D4E 0x1D4F 0x1D50 0x1D51 0x1D52 0x1D53 0x1D54 0x1D55 0x1D56 0x1D57 0x1D58 0x1D59 0x1D5A 0x1D5B 0x1D5C 0x1D5D 0x1D5E 0x1D5F 0x1D60 0x1D61 0x1D62 0x1D63 0x1D64 0x1D65 0x1D66 0x1D67 0x1D68 0x1D69 0x1D6A 0x1D6B 0x1D6C 0x1D6D 0x1D6E 0x1D6F 0x1D70 0x1D71 0x1D72 0x1D73 0x1D74 0x1D75 0x1D76 0x1D77 0x1D78 0x1D79 0x1D7A 0x1D7B 0x1D7C 0x1D7D 0x1D7E 0x1D7F 0x1D80 0x1D81 0x1D82 0x1D83 0x1D84 0x1D85 0x1D86 0x1D87 0x1D88 0x1D89 0x1D8A 0x1D8B 0x1D8C 0x1D8D 0x1D8E 0x1D8F 0x1D90 0x1D91 0x1D92 0x1D93 0x1D94 0x1D95 0x1D96 0x1D97 0x1D98 0x1D99 0x1D9A 0x1D9B 0x1D9C 0x1D9D 0x1D9E 0x1D9F 0x1DA0 0x1DA1 0x1DA2 0x1DA3 0x1DA4 0x1DA5 0x1DA6 0x1DA7 0x1DA8 0x1DA9 0x1DAA 0x1DAB 0x1DAC 0x1DAD 0x1DAE 0x1DAF 0x1DB0 0x1DB1 0x1DB2 0x1DB3 0x1DB4 0x1DB5 0x1DB6 0x1DB7 0x1DB8 0x1DB9 0x1DBA 0x1DBB 0x1DBC 0x1DBD 0x1DBE 0x1DBF 0x1DC0 0x1DC1 0x1DC2 0x1DC3 0x1DC4 0x1DC5 0x1DC6 0x1DC7 0x1DC8 0x1DC9 0x1DCA 0x1DFE 0x1DFF 0x1E00 0x1E01 0x1E02 0x1E03 0x1E04 0x1E05 0x1E06 0x1E07 0x1E0A 0x1E0B 0x1E10 0x1E11 0x1E12 0x1E13 0x1E18 0x1E19 0x1E1A 0x1E1B 0x1E1E 0x1E1F 0x1E22 0x1E23 0x1E26 0x1E27 0x1E28 0x1E29 0x1E2C 0x1E2D 0x1E30 0x1E31 0x1E32 0x1E33 0x1E34 0x1E35 0x1E38 0x1E39 0x1E3C 0x1E3D 0x1E3E 0x1E3F 0x1E40 0x1E41 0x1E4A 0x1E4B 0x1E54 0x1E55 0x1E56 0x1E57 0x1E58 0x1E59 0x1E5C 0x1E5D 0x1E6A 0x1E6B 0x1E70 0x1E71 0x1E72 0x1E73 0x1E74 0x1E75 0x1E76 0x1E77 0x1E7C 0x1E7D 0x1E7E 0x1E7F 0x1E86 0x1E87 0x1E88 0x1E89 0x1E8A 0x1E8B 0x1E8C 0x1E8D 0x1E90 0x1E91 0x1E94 0x1E95 0x1E96 0x1E98 0x1E99 0x1E9A 0x1E9B 0x1F00 0x1F01 0x1F02 0x1F03 0x1F04 0x1F05 0x1F06 0x1F07 0x1F08 0x1F09 0x1F0A 0x1F0B 0x1F0C 0x1F0D 0x1F0E 0x1F0F 0x1F10 0x1F11 0x1F12 0x1F13 0x1F14 0x1F15 0x1F18 0x1F19 0x1F1A 0x1F1B 0x1F1C 0x1F1D 0x1F20 0x1F21 0x1F22 0x1F23 0x1F24 0x1F25 0x1F26 0x1F27 0x1F28 0x1F29 0x1F2A 0x1F2B 0x1F2C 0x1F2D 0x1F2E 0x1F2F 0x1F30 0x1F31 0x1F32 0x1F33 0x1F34 0x1F35 0x1F36 0x1F37 0x1F38 0x1F39 0x1F3A 0x1F3B 0x1F3C 0x1F3D 0x1F3E 0x1F3F 0x1F40 0x1F41 0x1F42 0x1F43 0x1F44 0x1F45 0x1F48 0x1F49 0x1F4A 0x1F4B 0x1F4C 0x1F4D 0x1F50 0x1F51 0x1F52 0x1F53 0x1F54 0x1F55 0x1F56 0x1F57 0x1F59 0x1F5B 0x1F5D 0x1F5F 0x1F60 0x1F61 0x1F62 0x1F63 0x1F64 0x1F65 0x1F66 0x1F67 0x1F68 0x1F69 0x1F6A 0x1F6B 0x1F6C 0x1F6D 0x1F6E 0x1F6F 0x1F70 0x1F71 0x1F72 0x1F73 0x1F74 0x1F75 0x1F76 0x1F77 0x1F78 0x1F79 0x1F7A 0x1F7B 0x1F7C 0x1F7D 0x1F80 0x1F81 0x1F82 0x1F83 0x1F84 0x1F85 0x1F86 0x1F87 0x1F88 0x1F89 0x1F8A 0x1F8B 0x1F8C 0x1F8D 0x1F8E 0x1F8F 0x1F90 0x1F91 0x1F92 0x1F93 0x1F94 0x1F95 0x1F96 0x1F97 0x1F98 0x1F99 0x1F9A 0x1F9B 0x1F9C 0x1F9D 0x1F9E 0x1F9F 0x1FA0 0x1FA1 0x1FA2 0x1FA3 0x1FA4 0x1FA5 0x1FA6 0x1FA7 0x1FA8 0x1FA9 0x1FAA 0x1FAB 0x1FAC 0x1FAD 0x1FAE 0x1FAF 0x1FB0 0x1FB1 0x1FB2 0x1FB3 0x1FB4 0x1FB6 0x1FB7 0x1FB8 0x1FB9 0x1FBA 0x1FBB 0x1FBC 0x1FBD 0x1FBE 0x1FBF 0x1FC0 0x1FC1 0x1FC2 0x1FC3 0x1FC4 0x1FC6 0x1FC7 0x1FC8 0x1FC9 0x1FCA 0x1FCB 0x1FCC 0x1FCD 0x1FCE 0x1FCF 0x1FD0 0x1FD1 0x1FD2 0x1FD3 0x1FD6 0x1FD7 0x1FD8 0x1FD9 0x1FDA 0x1FDB 0x1FDD 0x1FDE 0x1FDF 0x1FE0 0x1FE1 0x1FE2 0x1FE3 0x1FE4 0x1FE5 0x1FE6 0x1FE7 0x1FE8 0x1FE9 0x1FEA 0x1FEB 0x1FEC 0x1FED 0x1FEE 0x1FEF 0x1FF2 0x1FF3 0x1FF4 0x1FF6 0x1FF7 0x1FF8 0x1FF9 0x1FFA 0x1FFB 0x1FFC 0x1FFD 0x1FFE 0x200C 0x200D 0x200E 0x200F 0x2017 0x201B 0x201F 0x202A 0x202B 0x202C 0x202D 0x202E 0x2034 0x203C 0x203E 0x205E 0x206A 0x206B 0x206C 0x206D 0x206E 0x206F 0x207F 0x2090 0x2091 0x2092 0x2093 0x2094 0x20A0 0x20A2 0x20A5 0x20A8 0x20AA 0x20AE 0x20AF 0x20B0 0x20B3 0x20B4 0x20F0 0x2105 0x2117 0x214D 0x214E 0x2184 0x2194 0x2195 0x21A8 0x221F 0x2229 0x2261 0x2302 0x2310 0x2320 0x2321 0x2500 0x2502 0x250C 0x2510 0x2514 0x2518 0x251C 0x2524 0x252C 0x2534 0x253C 0x2550 0x2551 0x2552 0x2553 0x2554 0x2555 0x2556 0x2557 0x2558 0x2559 0x255A 0x255B 0x255C 0x255D 0x255E 0x255F 0x2560 0x2561 0x2562 0x2563 0x2564 0x2565 0x2566 0x2567 0x2568 0x2569 0x256A 0x256B 0x256C 0x2580 0x2584 0x2588 0x258C 0x2590 0x2591 0x2592 0x2593 0x25AA 0x25AB 0x25AC 0x25BA 0x25C4 0x25CB 0x25CC 0x25CF 0x25D8 0x25D9 0x25E6 0x263A 0x263B 0x263C 0x2640 0x2642 0x2660 0x2663 0x2665 0x2666 0x266A 0x266B 0x266F 0x2C60 0x2C61 0x2C62 0x2C63 0x2C64 0x2C65 0x2C66 0x2C67 0x2C68 0x2C69 0x2C6A 0x2C6B 0x2C6C 0x2C6D 0x2C71 0x2C72 0x2C73 0x2C74 0x2C75 0x2C76 0x2C77 0x2E17 0xA717 0xA718 0xA719 0xA71A 0xA71B 0xA71C 0xA71D 0xA71E 0xA71F 0xA720 0xA721 0xA788 0xA789 0xA78A 0xA78B 0xA78C 0xFB1D 0xFB1E 0xFB1F 0xFB20 0xFB21 0xFB22 0xFB23 0xFB24 0xFB25 0xFB26 0xFB27 0xFB28 0xFB29 0xFB2A 0xFB2B 0xFB2C 0xFB2D 0xFB2E 0xFB2F 0xFB30 0xFB31 0xFB32 0xFB33 0xFB34 0xFB35 0xFB36 0xFB38 0xFB39 0xFB3A 0xFB3B 0xFB3C 0xFB3E 0xFB40 0xFB41 0xFB43 0xFB44 0xFB46 0xFB47 0xFB48 0xFB49 0xFB4A 0xFB4B 0xFB4C 0xFB4D 0xFB4E 0xFB4F 0xFE20 0xFE21 0xFE22 0xFE23

...

```

But these are in our sets. 


```
$ grep 0132 encodings/*nam
encodings/latin-ext_unique-glyphs.nam:0x0132  Ĳ LATIN CAPITAL LIGATURE IJ
$ grep 0133 encodings/*
encodings/latin-ext_unique-glyphs.nam:0x0133  ĳ LATIN SMALL LIGATURE IJ
$ grep 0149 encodings/*
encodings/latin-ext_unique-glyphs.nam:0x0149  ŉ LATIN SMALL LETTER N PRECEDED BY APOSTROPHE
$
```

**Comment by davelab6** [comment]
I updated this in 91ee82e

**Comment by felipesanches** [comment]
ok, I fixed a silly mistake in the logic of that. This is what we get now:

![screenshot at 2017-10-31 20 49 06](https://user-images.githubusercontent.com/213676/32252569-18cc2c38-be7d-11e7-89fb-250a9f33732c.png)

@davelab6  what do you think?

**Comment by felipesanches** [comment]
Some of the codepoints missing, as listed in the output above are:
* Unicode Character 'HAIR SPACE' (U+200A)
* Unicode Character 'CARRIAGE RETURN (CR)' (U+000D)
* Unicode Character 'MATHEMATICAL LEFT ANGLE BRACKET' (U+27E8)
* Unicode Character 'WHITE LEFT-POINTING TRIANGLE' (U+25C1)

**Comment by felipesanches** [comment]
is it good now, @davelab6 ?

**Comment by davelab6** [comment]
Yes I think so

**Comment by rsheeter** [comment]
Is the intent of this tool to find characters the production API wouldn't support? - if so you should use the nam files that prod uses instead.
