### ISSUE TITLE
push.py: axisregistry and lang paths check does not use expected path

### ISSUE THREAD

**Issue by chrissimpkins** [googlefonts/gftools#603]
Based on https://github.com/google/fonts/pull/5147#discussion_r958226762, the google/fonts axisregistry directory path checks in the to_sandbox.txt and to_production.txt files should use the following path syntax:

```
axisregistry/[AXIS].textproto
```

instead of the actual file path in the repository:

```
axisregistry/Lib/axisregistry/data/[AXIS].textproto
```

Language files need to be:
```
lang/languages/[LANG].textproto
```

Not

```
lang/Lib/gflanguages/data/languages/[LANG].textproto
```

An example failing CI test is https://github.com/google/fonts/runs/8103625159?check_suite_focus=true

**Comment by m4rc1e** [comment]
Thanks Chris. I'll implement this.
