### ISSUE TITLE
gftools --list-subcommands: Output needs readability improvements

### ISSUE THREAD

**Issue by eliheuer** [googlefonts/gftools#61]
Just a small formatting update to make this more readable would be helpful. Ideally `gftools --list-subcommands` would also give some usage information for each spript.

![screen shot 2018-07-13 at 1 43 26 pm](https://user-images.githubusercontent.com/5162664/42706018-5df5bd26-86a3-11e8-8e85-07e2a9782d98.png)

**Comment by simoncozens** [comment]
`--list-subcommands` is (as the --help text says) "usually only used to generate the shell completion code". `--help` actually prints the subcommands in a more user-friendly way.
