### ISSUE TITLE
Can't have Regular and Italics in the same file

### ISSUE THREAD

**Issue by weiweihuanghuang** [googlefonts/gftools#615]
I have a font that has the Regular and Italic masters in the same file. No interpolation will be done between them, and no variable font will be generated. When I try to use the gftools builder it only generates the italics and I get this message:

`WARNING:glyphsLib.builder.axes:Instance user-space location (400) redefined by 'Italic'`

Is there a way to configure the gftools builder so it doesn't do that?

**Comment by weiweihuanghuang** [comment]
Also is there a way to disable generating variable fonts?

**Comment by weiweihuanghuang** [comment]
Ok I figured out that I needed to change the axis name to "Italic" and it worked as expected.

**Comment by m4rc1e** [comment]
If you're using the builder, you can disable variable font generation by including `buildVariable: false` in your yaml file.
