### ISSUE TITLE
[gen-push-lists] remove invalid path

### ISSUE THREAD

**Issue by RosaWagner** [googlefonts/gftools#642]
Last run I had:
- `ofl/reemkufi/static`
But we just want the font dir, not the sub dir

- `lang`
- `lang/tests`
But we just want `lang/languages/*` and `lang/scripts/*`

See prod and sandbox list at commit:
https://github.com/google/fonts/pull/5662/commits/fe8663ba6450cb76392c3a6c9ab1f100d9ec0ae1

with CI fail:
https://github.com/google/fonts/actions/runs/3594031341/jobs/6051766310

**Comment by RosaWagner** [comment]
Adding to the thread axis registry related path to remove:

```
axisregistry 
axisregistry/.github/ISSUE_TEMPLATE
axisregistry/Lib/axisregistry 
axisregistry/tests
axisregistry/tests/data 
```

**Comment by m4rc1e** [comment]
I think https://github.com/googlefonts/gftools/pull/637 will solve this. I plan to cut a release next week once #643 is finished.

**Comment by RosaWagner** [comment]
Yeah the script seems to be broken when using the main branch eheh

**Comment by RosaWagner** [comment]
Update on this thread with last gftools version. 

It is listing only `axisregistry # https://github.com/google/fonts/pull/5853` and `lang # https://github.com/google/fonts/pull/5925` instead of the textproto path

**Comment by m4rc1e** [comment]
Confirmed. I'll fix this now and apologies.
