### ISSUE TITLE
Where did gen_html.py go?

### ISSUE THREAD

**Issue by madig** [googlefonts/gftools#650]
https://github.com/googlefonts/googlefonts-project-template/blob/cf074e5dd4b8deb23ca2ba5a1af92bad156b4b63/Makefile#L35-L36 stopped working.

**Comment by m4rc1e** [comment]
Apologies, it's been moved to diffenator2, https://github.com/googlefonts/diffenator2. I cut the new gftools too prematurely.

**Comment by m4rc1e** [comment]
Once gftools ci is fixed on Mon, I'll update the project template as well. Existing users of the project-template are not affected by this.

**Comment by emmamarichal** [comment]
hey @m4rc1e!
I installed the last version of gftools (0.9.23), but I can't generate any proofs or diff (with `gftools qa -f .*ttf -a -gfb` or `gftools gen-html diff -fb -fa -imgs`). do I have to install diffenator2 in addition?

**Comment by m4rc1e** [comment]
Use Diffenator2 .

`diffenator2 diff -fb fonts.ttf -fa fonts.ttf -imgs`
