### ISSUE TITLE
[builder] ensure ital axis last in STAT

### ISSUE THREAD

**Issue by yanone** [googlefonts/gftools#651]
A new check (https://github.com/googlefonts/fontbakery/pull/4023) now FAILs if the `ital` axis isn't last in the `STAT` table.

Therefore, the builder should build fonts that way.

**Comment by m4rc1e** [comment]
Auto STAT tables will put the Slant and Italic axes last, https://github.com/googlefonts/axisregistry/blob/main/Lib/axisregistry/__init__.py#L136-L142

I don't think I want to force the builder to put it last by default, since people may want a different order if they declare their own STAT table.

**Comment by yanone** [comment]
Okay, cool, thanks. It's a FAIL only for GF profile anyway. Closing this again.
