### ISSUE TITLE
[builder] COLRv0: Reorder glyphs in font to have empty glyph in GID1

### ISSUE THREAD

**Issue by yanone** [googlefonts/gftools#658]
Reacting to a Windows rendering bug, a COLRv0 font needs to have an empty glyph in GID1, such as the `space` glyph.

Could the builder make that happen in a post-processing stage?

I think it's not in the responsibility of a source author to ensure or even know that glyphs are to be ordered a certain way to react to stupid bugs.

The post-processing would happen on the binary, because AFAIK gftools has no control over the UFO sources, given that it can process several different kinds of sources.

I'm offering to write a fonttools script to make that happen.

**Comment by m4rc1e** [comment]
It should already do this, https://github.com/googlefonts/gftools/blob/main/Lib/gftools/fix.py#L694-L708

**Comment by m4rc1e** [comment]
Ah, just seen it may not be getting called due to https://github.com/googlefonts/gftools/blob/main/Lib/gftools/fix.py#L730-L732. Let me fix this.

**Comment by yanone** [comment]
Okay, let me check using the repo version of gftools

**Comment by yanone** [comment]
I just retried using the repo gftools, to same result. No reordering.

> Ah, just seen it may not be getting called due to https://github.com/googlefonts/gftools/blob/main/Lib/gftools/fix.py#L730-L732.

From that code I don't see how it wouldn't run, honestly.

**Comment by m4rc1e** [comment]
Alright, there's a bug in the existing code for making GID 1 a blank glyph. I'll take a look now.

**Comment by anthrotype** [comment]
may I just say that it would be much better if this fix were applied on the glyphOrder parameter (or public.glyphOrder lib key) directly in the input to fontmake instead of hacking the font post-build?
I know I myself suggested Marc to use nanoemoji reolder_glyphs functionality, but given that glyph order is something that touches basically all glyph-related tables it's a very deep surgery that should best be avoided if we can...

**Comment by anthrotype** [comment]
I would gladly merge a PR to ufo2ft that creates a glyphOrder with empty GID1 to be used for the build whenever we detect that the font will contain a COLRv0 table
