### ISSUE TITLE
[builder] Making more (or all) fontmake arguments available

### ISSUE THREAD

**Issue by vv-monsalve** [googlefonts/gftools#660]
After adding alternate layers for swapping cursive shapes, the build process for Geologica fails with the error "Compatibility check failed". Fontmake has the `--no-check-compatibility` argument that works to build the font ok, but it's not yet available.

Only some [Fontmake arguments are exposed](https://github.com/googlefonts/gftools/pull/617) to be used by Builder. But it would be of great help to have the option to make all the already available/in-use fontmake arguments to be able to build from Builder and keep using its facilities.

cc @m4rc1e

**Comment by m4rc1e** [comment]
Thanks. I've just run into this issue myself.

I'm curious, which fontmake arguments would you like me to expose if I cannot get arbitrary args to work elegantly?
