### ISSUE TITLE
[packager] Link PR with issue

### ISSUE THREAD

**Issue by yanone** [googlefonts/gftools#665]
Just typing down a thought that would greatly enhance the packaging workflow. I've had it ever since we transitioned to fully leveraging Github project management, but it's becoming more important now that we're using the new project boards which don't allow linking PRs with issues directly from the board, which the old projects allowed:

When submitting a font with the packager, a Github issue ID should be provided _mandatorily_ as soon as `--pr` is used, and be omittable only with `--noissue`.

Then the PR can be automatically linked with the issue and all other measures taken to label/assign the PR correctly following whatever data can be derived from the issue, and also the issue status changed.

`gftools packager whateverfont.yaml ./fonts --pr -i 3667` or
`gftools packager whateverfont.yaml ./fonts --pr --noissue`

I think it should be the `packager` command where the linking takes place.

@m4rc1e @RosaWagner

**Comment by RosaWagner** [comment]
I agree
