### ISSUE TITLE
default languagesystems clipped from imported FEA

### ISSUE THREAD

**Issue by aaronbell** [googlefonts/gftools#675]
I'm suing ufoMerge to import a Thai font into a Latin font. However, I'm finding that ufoMerge strips out the `languagesystem thai dflt;` code from the FEA file. Strangely, `languagesystem thai MLY;` is preserved. 

per @simoncozens, this is a known bug and I am currently working around the issue by importing the `languagesystem` definitions into the upstream source file.

**Comment by simoncozens** [comment]
New version of ufomerge (separate package to gftools) fixes this.
