### ISSUE TITLE
ufoMerge ignores prefix lookups

### ISSUE THREAD

**Issue by aaronbell** [googlefonts/gftools#676]
I'm merging an Arabic font into a Latin font (both Glyphs sources) which includes a large set of lookups in the Prefix section:

<img width="129" alt="Screen Shot 2023-04-27 at 10 28 20 PM" src="https://user-images.githubusercontent.com/8460297/235061997-d5ee68ad-8bbd-4c7d-adde-836aae6b552f.png">

In the UFO, they do not appear within any OT feature code but rather at the top level, akin to the `languagesystem` data. 

As far as I can tell, ufoMerge simply drops these lookups when they are in the UFO being merged in. As a result, the Arabic shaping code is not functioning as expected and I have had to move all of the Arabic code upstream to the Latin source to ensure that it is preserved as expected. 

ufoMerge should preserve this data if it exists in the UFO being merged in.

**Comment by moyogo** [comment]
@aaronbell Did you try with https://github.com/googlefonts/ufomerge? It has superceded gftools ufo-merge.

**Comment by aaronbell** [comment]
Oh yes. I can close this. The googlefonts one works for me :)
