### ISSUE TITLE
napostrophe.sc present in expert_unique-glyphs but not Napostrophe or napostrophe anywhere

### ISSUE THREAD

**Issue by weiweihuanghuang** [googlefonts/gftools#69]
https://github.com/googlefonts/gftools/search?q=napostrophe&unscoped_q=napostrophe

**Comment by eliheuer** [comment]
Ok, I can make a pull request to include Napostrophe and napostrophe. @weiweihuanghuang I'm looking into this, let me know if you have any suggestions or comments regarding this issue.

**Comment by eliheuer** [comment]
Now that I'm looking at this more it looks like `napostrophe` is deprecated: http://unicode.org/cldr/utility/character.jsp?a=0149

So removing `napostrophe.sc` might be the way to resolve this issue.

**Comment by eliheuer** [comment]
https://github.com/googlefonts/gftools/commit/ba769ed6b693e8018e0e17b4df9541cb7befcba2

Looking at [this commit message](https://github.com/googlefonts/gftools/commit/ba769ed6b693e8018e0e17b4df9541cb7befcba2) it seems like `napostrophe` was removed, but I don't see why `napostrophe.sc` should remain.

**Comment by alexeiva** [comment]
It is safe to remove `napostrophe.sc`.    `napostrophe` was originally included in the set for compatibility issues, but later stripped. Apparently I forgot to remove it from the sc list.

**Comment by eliheuer** [comment]
Thanks, I'm preparing the pull request now.

**Comment by EbenSorkin** [comment]
Great! I agree that's what should be done.
