### ISSUE TITLE
[ufo-merge] Merged .ufo has random glyph-order for glyphs from ufo-2

### ISSUE THREAD

**Issue by kalapi** [googlefonts/gftools#701]
Hello! The merged .ufo should ideally have a combined `public.glyphOrder` with the values from ufo-2 key appended to the values from ufo-1. 

Example below from a generated TTF in OTMaster with the glyphOrder of the Latin subset jumbled.

![Screenshot 2023-07-31 at 6 58 44 PM](https://github.com/googlefonts/gftools/assets/15804460/aeaf594c-34bd-4cc5-813d-00d4f8d25d12)

**Comment by moyogo** [comment]
@kalapi Can you try with https://github.com/googlefonts/ufomerge instead? It has superceded gftools ufo-merge.

**Comment by simoncozens** [comment]
Yes, please move to ufomerge; but I think this is fixed as we now use lists instead of sets to store the glyph order.
