### ISSUE TITLE
Latest gftools (0.9.33) does not support new METADATA.pb format

### ISSUE THREAD

**Issue by Bo98** [googlefonts/gftools#706]
Reading METADATA.pb files modified by https://github.com/google/fonts/commit/47a6c224b3e0287b2e48e3ffef8c9ce2ca4931f4 or https://github.com/google/fonts/commit/ea42b7c32f18e96539fafbe3e04f0133332df032 result in the following error, due to the prototype definitions not being synced with this repo:

```
google.protobuf.text_format.ParseError: 18:1 : Message type "google.fonts_public.FamilyProto" has no field named "stroke".
```

**Comment by eliheuer** [comment]
Good catch, thanks!

I can try fixing this if no one else has time.

**Comment by m4rc1e** [comment]
I've requested a new family proto file from the backend team.
