### ISSUE TITLE
[Packager] should not add empty fields in metadata.pb

### ISSUE THREAD

**Issue by RosaWagner** [googlefonts/gftools#707]
In [the PR for Ubuntu](https://github.com/google/fonts/pull/6609/files#diff-910688eb24ef99919a229972cd8fdfc7e0fbb70e1c31904b43afb2dc2c85de0c), a sample text entry was add but empty. I don't think this entry should be added automatically if there was not one already before

Also this PR from Rod to correct Wixmadefor Display: https://github.com/google/fonts/pull/6646

This issue seems to only affect Marc's PRs

**Comment by simoncozens** [comment]
I tried to replicate this but couldn't; I wonder if Marc had his own development version installed when he was making these PRs.
