### ISSUE TITLE
Primary script: Zinh automatically added

### ISSUE THREAD

**Issue by emmamarichal** [googlefonts/gftools#708]
Hello,

When I use gftools packager, a "primary_script: Zinh" is automatically added in metadata.pb
any idea?

thanks!

**Comment by emmamarichal** [comment]
It happened in my last PRs, so since end of July I would say
-https://github.com/google/fonts/pull/6651
-https://github.com/google/fonts/pull/6561
-https://github.com/google/fonts/pull/6585

**Comment by simoncozens** [comment]
Weird, I don't see that, but I *do* see the "empty sample text"!

**Comment by simoncozens** [comment]
OK, got it; fixing...

**Comment by emmamarichal** [comment]
great, thank you!

**Comment by vv-monsalve** [comment]
This auto addition for "Zinh" still happening

- https://github.com/google/fonts/pull/6673
- https://github.com/google/fonts/pull/6662/commits/29abece3f8ff02fe64d95bf489bbf9a612870ecf

**Comment by simoncozens** [comment]
I think updating your local gftools-packager will fix it.
