### ISSUE TITLE
Proposal: `private` flag in config.yaml

### ISSUE THREAD

**Issue by bramstein** [googlefonts/gftools#712]
This may be a tad specific to our needs, but I thought I'd propose it anyway to gauge interest. Like Google Fonts, we (The Type Founders) manage our font families in Git repositories. However, we use a monorepo per foundry, so all of a foundry's families are stored in a single repository.

We often run into situations where we would like to mark a family as private for various reasons: because it is a work-in-progress, a custom modification, or simply because we're not ready to publish it yet. We could store this information separately in a configuration file in each family directory, but it feels appropriate and generally useful to have it in the config.yaml file (much like package managers like Crate and NPM have a `private` flag in their package configurations).

This could be accomplished in two ways:

* Add a `private` flag in the configuration schema.
* Some sort of extension scheme in the configuration which gftools ignores.

Curious to hear thoughts.

**Comment by simoncozens** [comment]
Sounds good. I suggest we add a `local_metadata` field (we can bikeshed the name) which is ignored by the tooling, but you can fill it with a map of whatever metadata you like.

**Comment by bramstein** [comment]
Awesome, that would work for us. I'll leave the bike shedding to others, but I'd be happy to open a PR to implement it.

**Comment by arrowtype** [comment]
Chiming in to say that I’m now wishing this existing! Admittedly, it’s for another use case at The Type Founders, but it would still be handy.

If bike shedding is welcome... `local_metadata` is fine, but another possible option might be to use `lib`, as is the convention in UFOs and Designspace documents. Maybe that’s too generic, though...
