### ISSUE TITLE
The gftools packager workflow needs to be updated for the Q3 2023 categories update

### ISSUE THREAD

**Issue by eliheuer** [googlefonts/gftools#720]
In Q3 2023 the Google Fonts site was updated to a new version that can have multiple categories per font.

There was a batch update to the `METADATA.pb` files for this:
https://github.com/google/fonts/pull/6596
https://github.com/google/fonts/pull/6604
https://github.com/google/fonts/pull/6622
https://github.com/google/fonts/pull/6625

The packager workflow needs to be updated so that new fonts are added with `METADATA.pb` files that conform to the new category system.

**Comment by eliheuer** [comment]
No, yesterday I looked though all the fonts added between when Evan made the first batch update (Aug 3) and now, and only new font had multiple categories, and thus had an incomplete metadata file, that was Playpen Sans: https://github.com/google/fonts/pull/6673 (handwriting, sans serif).

The fonts with only one category, sans or serif, but not monospace, display, handwriting, slab, etc, have `metadata.pb` files created that work as expected as far as I can tell.

**Comment by m4rc1e** [comment]
Ok, I think I now understand how these two new fields work.

- The new fields are used when searching for families in the new fonts.google.com site
- Currently, Google Fonts only uses the last entry in the existing category field. The new classification field can be used multiple times!
- Metadata files don't require the new fields to be populated. However, if the family is say a Slab Serif, then it makes sense to set the stroke field to SLAB_SERIF. Likewise, if a family is a symbol font, then it makes sense for the classification field to be set to symbols.

**Comment by vv-monsalve** [comment]
> No, yesterday I looked though all the fonts added between when Evan made the first batch update (Aug 3) and now, and **only one new font had multiple categories, and thus had an incomplete metadata file**, that was Playpen Sans: https://github.com/google/fonts/pull/6673 (handwriting, sans serif stroke).

Hi Eli, I'm a bit confused about what you mean. Are you saying that only one font _should have_ multiple categories? If that's correct, I think it's important to include information about how this new system works in the Guide at the same time as we add these fields to the packager. This will help users better understand how to fill them out.

**Comment by eliheuer** [comment]
Yeah, the guide will need an update to cover this, I made an issue about that here: https://github.com/googlefonts/googlefonts.github.io/issues/110

I'm not saying only one font should have multiple categories. I'm saying only one font onboarded recently had multiple categories. New fonts need to be given categories that accurately describe them.

An important thing to keep in ming is that this is just the first pass of the updated category system. Late this year or early next year, more categories will be added.

**Comment by vv-monsalve** [comment]
> I'm saying only one font onboarded recently had multiple categories.

This is clear. What was not clear was "only one new font had multiple categories, and thus had an incomplete metadata file". I was confused since having multiple categories didn't sound like having incomplete metadata. But is clear now the case.

**Comment by eliheuer** [comment]
Yeah, sorry. The font had multiple categories (in the design), but the metadata did not because the packager has not been updated yet.

**Comment by eliheuer** [comment]
I wrote a bash script to analyze the current metadata, here are the values associated with each key:

`category:`
```
DISPLAY
HANDWRITING
MONOSPACE
SANS_SERIF
SERIF
``` 
`stroke:`
```
SANS_SERIF
SERIF
SLAB_SERIF
```
`classifications:`
```
DISPLAY
HANDWRITING
MONOSPACE
SYMBOLS
```
