### ISSUE TITLE
Help: unsure how to export Glyphs from FontLab

### ISSUE THREAD

**Issue by mahtaran** [googlefonts/gftools#724]
So, I am looking into adding small capitals and old-style figures to [googlefonts/lexend](https://github.com/googlefonts/lexend). I downloaded the FontLab 8 trial (since I'm on Windows), opened the `.glyphs` file, duplicated the glyphs, used actions to transform them across all instances universally, added the features, and all _seemed_ to be fine. When I export it to a Variable TT file using FontLab, all is fine, and the font works as expected.

However, when I export it to a Glyphs file and use it with `gftools`, I get a bunch of `Glyphs named '<glyph>' have different number of segments` errors, even for glyphs that I never touched. Is there any kind of export setting I need to change to have my files be compatible with `gftools`?

I have already tried:

- [x] Setting the export settings such that all curves are converted to TrueType curves
- [x] Setting the export settings such that it decomposes all/transformed composite glyphs
- [x] I had a look at [VFB2UFO3](https://pypi.org/project/vfb2ufo3), but for the life of me couldn't understand how to use it
- [x] Exporting as Designspace or UBO files, the same problem persists

I'm quite new and at a loss here, so any kind of help would be much appreciated. Thanks!

**Comment by eliheuer** [comment]
Do you have the same problem if you import the original `.glyphs` file into FontLab and export it without making changes?

If so, you can start with a clean file and copy your changes over, testing with gftools as you go.

Just getting a Mac and Glyphs might save you a lot of time.

**Comment by madig** [comment]
FontLab may apply magic to the font that breaks compilation, or not apply magic during export, also breaking compilation. It may be best to ask over in the FontLab support forum for how to achieve a proper export to .glyphs.

**Comment by davelab6** [comment]
@mahtaran 

> am looking into adding small capitals and old-style figures to [googlefonts/lexend](https://github.com/googlefonts/lexend)

Is this just for your own use, or for submission to GF? 

If for yourself, I'd just export from Fontlab and call it a day.

If for GF, we are working on a new version that has a lot of changes, so I'd postpone working on this until after that round of development is done.

**Comment by mahtaran** [comment]
Hi @davelab6! Any news on when we can expect that new version?
