### ISSUE TITLE
[builder] ttfautohint not found

### ISSUE THREAD

**Issue by RosaWagner** [googlefonts/gftools#727]
I have a message saying that ttfautohint command not found when building with the last gftools

```
[4/8] ttfautohint ../fonts/ttf/Borel-R...ts/ttf/Borel-Regular.ttf.autohintstamp
FAILED: ../fonts/ttf/Borel-Regular.ttf.autohintstamp 
ttfautohint ../fonts/ttf/Borel-Regular.ttf ../fonts/ttf/Borel-Regular.ttf.autohinted && mv ../fonts/ttf/Borel-Regular.ttf.autohinted ../fonts/ttf/Borel-Regular.ttf && touch ../fonts/ttf/Borel-Regular.ttf.autohintstamp
/bin/sh: ttfautohint: command not found

```

**Comment by anthrotype** [comment]
gftools depends on ttfautohint-py; the latter does _not_ install a `ttfautohint` script. If you want to call it from the command line you need to do `python -m ttfautohint`. I recommend you use `sys.executable` when you define the ttfautohint build rule so you call the same python that gftools was called with.

**Comment by RosaWagner** [comment]
> gftools depends on ttfautohint-py; the latter does not install a ttfautohint script. If you want to call it from the command line you need to do python -m ttfautohint. 

I got that, thanks. But several stuff have changed with the last version of gftools, and I _think_ `ttfautohint-py` was part of gftools package and we didn't need to install it locally. Otherwise all the fonts using the google fonts project template with a gh-action for building wouldn't be autohinted, right?

**Comment by anthrotype** [comment]
ttautohint-py is still listed among gftools' setup.py install_requires so when one does pip install gftools they will also automatically get ttfautohint-py.

**Comment by anthrotype** [comment]
> we didn't need to install it locally

that's right, you should not need to install it separately. The build rule for running ttfautohint from the ninja-based gftools builder needs to be changed so that it invokes the ttfautohint-py console entry point (`"{sys.executable} -m ttfautohint"`) instead of plain `ttfautohint` command which is not available normally (unless one also happens to have `ttfautohint` command installed independently from gftools itself, e.g. via homebrew, but I would not recommend that)

**Comment by simoncozens** [comment]
The new builder uses gftools-autohint, and the old one should too.

**Comment by RosaWagner** [comment]
Confirming that it is now working youpi!
