### ISSUE TITLE
[builder] missing gftools version number in font version number

### ISSUE THREAD

**Issue by RosaWagner** [googlefonts/gftools#729]
Usually we have a version number that would look like this "version 1.004 gftools 0.9.34" in the name table, but it looks like gftools version number is missing.

**Comment by simoncozens** [comment]
Do we still need to do this if we do #776?

**Comment by m4rc1e** [comment]
I don't think we'll need it. Cosimo and myself are contemplating to use your "debg" table instead of "meta" atm.

**Comment by simoncozens** [comment]
Let's do #776 instead. I don't like polluting font version numbers with build information.
