### ISSUE TITLE
Use JSON UFOs for intermediate output

### ISSUE THREAD

**Issue by madig** [googlefonts/gftools#731]
Glyphs files are converted to normal UFOs currently, which is slow. Writing out JSON blobs is faster, especially for bigger projects.

**Comment by eliheuer** [comment]
Thanks! This can all be done just with `ufoLib2` right? The stuff from this [PR](https://github.com/fonttools/ufoLib2/pull/230)? I'll look into it if no one else has time.

**Comment by madig** [comment]
Yep. Instead of `Font.open(...)` and `ufo.save(...)` you do `Font.json_loads(...)` `ufo.json_dumps(...)` or whatsitcalled.

**Comment by anthrotype** [comment]
if you're calling fontmake as a subprocess (as you should) you just need to pass `--ufo-structure=json` option, optionally with `--indent-json` if you want it human readable (probably not if you care about speed).
If you're messing with fontmake internal API, there's a `ufo_structure` and `indent_json` parameters to various methods on FontProject that accomplish the same (grep for it).

**Comment by anthrotype** [comment]
also, you want to depend on fontmake[json] extra which activates ufoLib2[json] extra which in turns pulls in cattrs and orjson

**Comment by simoncozens** [comment]
After much trial and error I discovered that I need to write a function like this:

```python
def open_ufo(path):
    if os.path.isdir(path):
        return ufoLib2.Font.open(path)
    else:
        return ufoLib2.Font.json_loads(open(path, "rb").read())
```

**Comment by anthrotype** [comment]
yes, like fontmake itself does: https://github.com/googlefonts/fontmake/blob/6a8b2907891537ce559dd3d6fcfe68d8b55d6bc9/Lib/fontmake/font_project.py#L160-L169

we didn't want Font.open to handle json because this is not an official UFO format but only a private ufoLib2-only serialization format

**Comment by anthrotype** [comment]
@simoncozens your `open_ufo` snippet above woudl not correctly handle .ufoz (zipped UFOs, which are also not a directory), it's better you check if the suffix is .json, treat it as such otherwise let ufoLib2 Font.open handle the others

**Comment by simoncozens** [comment]
I sort of see that for UFO libraries *in general*, this is ufoLib2 and we're talking about ufoLib2-specific format. It should be able to open its own files.

**Comment by simoncozens** [comment]
Using standard UFOs in the new builder, on Noto Sans Mono (158 build steps, 120 targets)

1238.11s user 90.81s system 654% cpu 3:23.10 total
1274.70s user 91.34s system 667% cpu 3:24.56 total

Using JSON UFOs:

998.50s user 31.00s system 665% cpu 2:34.74 total
1047.40s user 33.79s system 626% cpu 2:52.69 total

20% speed-up. Nice.

**Comment by simoncozens** [comment]
Closing this because builder2 (which is the future) does it.
