### ISSUE TITLE
gen-push-lists only allows 100 files per PR

### ISSUE THREAD

**Issue by simoncozens** [googlefonts/gftools#737]
Paginating things in a GitHub GraphQL query is a nightmare. Currently the code we have does this:

https://github.com/googlefonts/gftools/blob/cc53fb57e939e0a1eeb256c5dcdb04caec5987cd/Lib/gftools/push.py#L83-L88

and then

https://github.com/googlefonts/gftools/blob/cc53fb57e939e0a1eeb256c5dcdb04caec5987cd/Lib/gftools/push.py#L106-L112

We correctly loop over multiple pages because we know that there may be more than 100 "items" in the project board, but we assume there are at most 100 files per PR; this isn't a good assumption in something like a big lang update or a catalogue-wide metadata update.

However (and this is where it gets difficult) to make that work you need to say "give me page 2 of the files on page 3 of the items", and you [can't use multiple pagination cursors in a GitHub GraphQL query](https://stackoverflow.com/questions/59192308/github-graphql-v4-api-nested-pagination-multiple-pagination-cursors-can-not-be) (See also [this issue](https://github.com/shurcooL/graphql/issues/69#issuecomment-843128806)).

So we may need to do this the inefficient way: grab all the items and their associated PRs first, paging through all the pages of items, and then do a query for *each* PR, paging through all the lists of files.

Urgh.

**Comment by m4rc1e** [comment]
Thanks for looking into this Simon. I don't mind seeing what I can do since I wrote the original query.

**Comment by davelab6** [comment]
> we may need to do this the inefficient way

But if we have `totalCount` and can gate on if that is over 99, then that inefficient way can happen only as a Plan B, under an `else` statement..?

**Comment by simoncozens** [comment]
That's really smart. In pseudocode:

```
if pr.totalCount > 99:
   prs_to_investigate_further.push(pr.id)
```
