### ISSUE TITLE
add option to autohint OTF-CFF font

### ISSUE THREAD

**Issue by RosaWagner** [googlefonts/gftools#751]
That would be a major highlight for all the upstream repos. A lot of designers are using fonts on Mac Adobe, PS hinting is really needed. Could we run AFDKO as a default option on all OTF-CFF export?

**Comment by simoncozens** [comment]
I can add autohinting for OTF static exports, but it's worth noting that we don't current support building CFF2 variable fonts in the builder; if people want that, that can be a separate issue.

**Comment by RosaWagner** [comment]
yeah I think we are only aiming for the OTF static atm
