### ISSUE TITLE
temp file for stat table not deleted after successful export

### ISSUE THREAD

**Issue by RosaWagner** [googlefonts/gftools#764]
I have this file `HedvigLettersSerif-Regular[opsz].ttf.stat.yaml` in the `variablefont` directory each time after export. In https://github.com/RosaWagner/HedvigLetters/commit/2cd282da2077b297b69cf16758144342ed11e32c

Also `instances_ttf` is not removed after successful export of (only) otf-cff fonts.

**Comment by simoncozens** [comment]
This is something which will get fixed when builder2 lands, as builder2 is more conscientious about putting temporary files in the temporary directory.
