### ISSUE TITLE
manual TT hinting applied after converting glyph names to prod names?

### ISSUE THREAD

**Issue by RosaWagner** [googlefonts/gftools#772]
This is what is reported by the designers of the Intel One Mono project:

> Seeing a number of glyphs where the hinting did not attach properly; for example, the Regular shows 199 glyphs that have lost their TT instructions, marked red in the attached screenshot. I am seeing differences on a hinting proof, and comparing ttx dumps of your new TTF build vs our existing one reveals missing <instructions> blocks. As this appears to concern glyphs whose glyph names are reassigned in production, I wonder if that might be a good place to start investigating (maybe the hinting, which already uses TTF names, is attached to the font before the glyph names are converted?).

I asked if they could provide the hinting program with ttf files already converted to prod names. But I don't know if this is something that is recurrent with manual hinted fonts; we might want to change the process to avoid that issue (although it might be complicated with the idea of patching a TT hinting program after export).

https://github.com/RosaWagner/intel-one-mono/tree/googlefonts

![Screenshot 2023-10-20 at 4 49 20 PM](https://github.com/googlefonts/gftools/assets/12222436/6a9b31b8-bf11-4b64-9513-262a4909a3e4)

**Comment by m4rc1e** [comment]
`--no-production-names` actually exists in fontmake ;-)

**Comment by m4rc1e** [comment]
I'd prefer it if we changed vtLib so it can handle both sets of names :-). Lemme think about that and I may have something this week.

**Comment by m4rc1e** [comment]
I'm assuming the issue is that they've hinted ttfs with nice names, when they should've hinted a ttf with prod names.

**Comment by RosaWagner** [comment]
Yes. I don't know what's right or wrong here. Maybe a simple script to convert to prod name the hinted-ttx we use should be enough? Does it worth upgrading the tooling for this one exception?

**Comment by m4rc1e** [comment]
I think it makes sense to improve vttLib. I'll check how feasible this is now.

**Comment by m4rc1e** [comment]
@RosaWagner  A VTT dump doesn't include any table which resembles a glyph order so we cannot make a mapping. Can we simply just rename the glyphs in the vtt source ttf? if so, I can write a quick tool.

**Comment by m4rc1e** [comment]
I've thought about this issue a bit more and having VTT sources which use nice names does make sense it's more designer friendly,

**Comment by RosaWagner** [comment]
if you can make a script that convert nice names to prod names, I am more than happy :)
