### ISSUE TITLE
Install problem on Python 3.11, via psautohint

### ISSUE THREAD

**Issue by justvanrossum** [googlefonts/gftools#789]
Just in case others run into this:

I tried to pip install gftools on macOS 14, with Python 3.11 and it failed trying to build wheels for psautohint.

It turns out psautohint doesn't have wheels for 3.11, and is unmaintained/deprecated, and building it locally somehow didn't work in my setup.

I solved it by using Python 3.10 instead.

**Comment by m4rc1e** [comment]
Thanks Just! I'll look into getting this repo to work on 3.11 and 3.12.

**Comment by simoncozens** [comment]
afdko 4.0.0:

* depends on psautohint 🤔
* includes otfautohint 🫢

**Comment by ftCLI** [comment]
Same on Windows. I also tried to fork AFDKO, remove psautohint from requirements.txt and tried to install. The installation failed while trying to build wheels for AFDKO.

Works if Visual Studio is installed: https://github.com/ftCLI/FoundryTools-CLI/issues/118#issuecomment-1783856177

**Comment by m4rc1e** [comment]
The standalone psautohint appears to be deprecated, https://github.com/adobe-type-tools/psautohint#important-note-otfautohint. @simoncozens any reason why we can't use the AFDKO's otfautohint? we already have the AFDKO has a dependency,

**Comment by m4rc1e** [comment]
Installs for me on OS X 13.1, python 3.12. Lemme check 3.11. I'm thinking about adding tox.

**Comment by justvanrossum** [comment]
It could very well be that my dev env is slightly messed up. However, no wheels for psautohint also means no install for people without dev tools installed.

**Comment by simoncozens** [comment]
psautohint dep was removed in afdko 4.0.1
