### ISSUE TITLE
API vs Repo for Early Access

### ISSUE THREAD

**Issue by felipesanches** [googlefonts/gftools#8]
Original request at:
https://github.com/googlefonts/fontbakery/issues/1592

@davelab6 said:

- [ ] The github.com/google/fonts repo doesn't include all the fonts available in fonts.google.com/earlyaccess but it should. Please provide a script which provides details about which versions are available in each place. 

- [ ] Additionally, for Noto fonts, check the upstream version too, to accelerate our ability to keep them up to date.

**Comment by simoncozens** [comment]
Early access is no longer a thing, closing.
