### ISSUE TITLE
Builder don't seem to care for the info in config.yaml

### ISSUE THREAD

**Issue by RosaWagner** [googlefonts/gftools#802]
All lexend subfamilies need to be built from the same source. Lexend has a weight, width, SPAC and ital axes, all the sub families are slice located at a specific point on the width and SPAC axis. Therefore the subfamilies only have weight and ital axes.

In the source file there are different set of instances with different family names to define all the different families. Logically, the "familyName" in config.yaml should help selecting a specific set of instances for a specific font. So I purposely use different config.yaml to:
- specify different family names 
- select a particular set of instances in the FVAR
- to define a specific STAT table. 

This use to work great the first time I built all the subfamilies.

Now:
- the specified family name doesn't help to export a specific set of instances with a specific family name 
- the STAT table is made automatically using the axis registry, without taking into account the one I specified in the config file to overwrite the axis registry.
- the STAT includes values for axes that are not listed in the AxisOrder

This cause issues in:
- font naming: wrong family name
- STAT table: contains too much axes resulting in a wrong naming when using the font in a desktop app
- FVAR table: **contain all active instances from the source**

Before I used the config file to workaround `fonttools varLib.instancer` which I noticed keep axes in the STAT table that are supposed to be dropped.

**Comment by simoncozens** [comment]
OK, this will be a problem both with the ninja builder and builder2. builder2 does not support selecting instances directly, and it doesn't currently support changing family names. This may be a situation where you write a `recipe` by hand (or generate one from a script), but this will be cumbersome if there are many instances. For example you may be able to get what you want by building the whole variable, using varLib.instancer to subspace it, `rename` to change the family name, then using `gftools-gen-stat` to fix up the stat table.

**Comment by simoncozens** [comment]
Remaining part here is #850.
