### ISSUE TITLE
Allow remove codepoints in `remap-font`

### ISSUE THREAD

**Issue by WordlessEcho** [googlefonts/gftools#811]
Since [notofonts/nototools](https://github.com/notofonts/nototools/) has been archived. There is a function [`delete_from_cmap`](https://github.com/notofonts/nototools/blob/04fc995b13655698f2e7787c242524081aef2fc1/nototools/font_data.py#L216C3-L216C3) that used in [subset_noto_cjk.py of AOSP](https://cs.android.com/android/platform/superproject/main/+/main:external/noto-fonts/scripts/subset_noto_cjk.py;l=89;drc=d8536c6637d9506ccd8ffb09810ceb7e864e20d8). I thought we could make `remap-font` used to remove codepoints.

Currently we have those:
```python3
    if glyph not in font.getGlyphOrder():
        print(f"Glyph {glyph} (to be mapped to {codepoint}) not found in font")
            sys.exit(1)

cmap = font["cmap"]
for table in cmap.tables:
    for codepoint, glyph in mapping.items():
        table.cmap[codepoint] = glyph
```

Could we change like this?
```python3
    if glyph != "" and glyph not in font.getGlyphOrder():
        print(f"Glyph {glyph} (to be mapped to {codepoint}) not found in font")
            sys.exit(1)

cmap = font["cmap"]
for table in cmap.tables:
    for codepoint, glyph in mapping.items():
        if glyph == "":
            del table.cmap[codepoint]
        else:
            table.cmap[codepoint] = glyph
```

Or we just write a new function?

**Comment by simoncozens** [comment]
This will leave the glyph in the font but remove its cmap assignment. Is that what you want to do? If you want to remove the glyph, hb-subset or similar is a better option.

**Comment by WordlessEcho** [comment]
> If you want to remove the glyph, hb-subset or similar is a better option.
Okay, thanks!
