### ISSUE TITLE
[builder] Making more (or all) fontmake arguments available? (Needing `--masters-as-instances`)

### ISSUE THREAD

**Issue by arrowtype** [googlefonts/gftools#845]
Past issues such as https://github.com/googlefonts/gftools/issues/660 and those listed at https://github.com/googlefonts/gftools/pull/617 have expressed needs for more fontmake args. Well, here’s another!

I have a Glyphs source that has several Masters that are incompatible (they are different versions of a basic design), and each has a corresponding Export / instance.

This builds with `fontmake -g familyname.glyphs -o otf --masters-as-instances`. However, I can’t get it to build from the gftools builder, even if I set `interpolate: false` in the `config.yaml`.

So, I think that perhaps I need `--masters-as-instances` as an option in the builder. Or, is there another solution that I might be missing?

Thanks for any help!

**Comment by anthrotype** [comment]
I don't think you need that option, it's a remnant of the old noto build toolchain. You just need to have the instances defined in your glyphs source at the same locations as the masters, and use the -i option so that the instances get built (and not the masters). No interpolation takes place if the instance is exactly on top of a master

**Comment by arrowtype** [comment]
Hey Cosimo, thanks so much for the quick answer! 

I thought I had tested your recommendation before I asked this, but I’ve just found that the instances also need `Axis Location` custom parameters in order for it to work. When they have that, the basic `-i` option (just `interpolate: true` in the builder config.yaml) does indeed work to export the individual instances.

I’ll close the issue because it wasn’t actually an issue in the end. I really appreciate your help and insight here!

**Comment by simoncozens** [comment]
FWIW, builder2 has `extraFontmakeArgs:`, `extraVariableFontmakeArgs:` and `extraStaticFontmakeArgs:` config keys.
