### ISSUE TITLE
Packager should create branch off main

### ISSUE THREAD

**Issue by simoncozens** [googlefonts/gftools#862]
With the new packager, if you've been working on one PR and then start working on another without changing to `main` first, it creates the new branch and commit on top of where you were before - the previous packager branch you were working on:

```
* bee9fa196 - (HEAD -> gftools_packager_ofl_eduqldhand) Edu QLD Hand: Version 2.000 added (15 seconds ago) <Simon Cozens>
* a13ad6f0d - (origin/gftools_packager_ofl_edunswacthand, gftools_packager_ofl_edunswacthand) Edu NSW ACT Hand: Version 2.000 added (5 hours ago) <Simon Cozens>
```

It should always switch to main (and fetch/pull) before branching.

**Comment by m4rc1e** [comment]
Currently working on this now. Will tackle #873 at the same time since they're semi related.
