### ISSUE TITLE
new tool: transfer hints

### ISSUE THREAD

**Issue by m4rc1e** [googlefonts/gftools#91]
Well I've hit the dreaded situation where I have a VTT hinted family and I need to make some modifications.

Before anyone suggests "Just use file > import > glyph" in VTT. What if you need to replace many ranges of glyphs? it would take many hours to do this correctly. I can think of far better ways for anyone to spend their time. What if you also change the glyph order?

At two other foundries I've worked for, they've had hint transfer scripts.

---
My C learning is progressing ok. I hope in a few months I'll be able to sit down and work on ttfautohint.

**Comment by anthrotype** [comment]
Back in the days I wrote this vttLib, but now I've forgot all the details of how it works :)
https://github.com/daltonmaag/vttLib

**Comment by anthrotype** [comment]
it's not on PyPI, but I think if you ask @madig he should be able to publish it
see https://github.com/daltonmaag/vttLib/issues/12

**Comment by m4rc1e** [comment]
Thanks @anthrotype! vttLib seems to be a compiler for VTT hints. I simply want to take vtt hints from font_a to font_b. I remember writing something similar over four years ago.

**Comment by anthrotype** [comment]
oh, you want to transfer the VTT sources that are stored in the private `TSI*` tables between two TTFs...
the vttLib workflow assumes that those sources are stored as TTX files inside UFO/data directory.
A "hint transfer" for vttLib would mean, either recompiling the TTF from the same UFO -- where something in the meantime has changed (either the VTT ttx data itself, or something else) --, or copying these VTT ttx files to another UFO and compile that to TTF (hoping that all goes smoothly).
vttLib has dump and merge subcommands that respectively export VTT tables from TTF to UFO (dump them as ttx), and import VTT ttx files from a UFO data into a TTF file (so they can be further edited inside VTT).
The compile command takes a TTF which contains VTT TSI tables and creates TrueType bytecode in fpgm, prep, cvt, and glyf tables (optionally stripping the TSI source tables).

**Comment by anthrotype** [comment]
the idea was to treat VTT sources as "first class" sources that are committed to version control, not a binary blob that gets obscurely "transferred" by some getto fonttools script which leaves no trace

**Comment by madig** [comment]
I wrote something that takes an old font and its TSI3 code (TSI1 isn't handled) and rewrites the instructions to point to the same points in the new font. Again, TSI1 is not handled. I want to eventually upstream this into vttLib, but it's low on the priority list. Maybe it's useful for you still.

[vtt_transplanter.zip](https://github.com/googlefonts/gftools/files/2510606/vtt_transplanter.zip)

**Comment by m4rc1e** [comment]
> the idea was to treat VTT sources as "first class" sources that are committed to version control, not a binary blob that gets obscurely "transferred" by some getto fonttools script which leaves no trace

Nearly fell off my chair laughing at this.

We're in a situation where we may use VTT for 2-3 families just to test the water. I'm hoping/praying we don't do more than this.

For the time being, a script would be sufficient (it may be quicker for me to write this script than to manually tranfer hints in a joseph and his technicolour dreamcoat kind of way)

I agree that treating them as "first class" is the way to go. We're just in playing for now.

@madig thank you kind sir, I will investigate this. I owe you a beer.

**Comment by anthrotype** [comment]
@madig the LICENSE is the same as vttLib?

**Comment by m4rc1e** [comment]
@madig this is the first use of Python types I've seen the wild ;-). Unfortunately it can't construct all the commands which are available in VTT, such as _resyanchor_ etc. Thanks though!

**Comment by madig** [comment]
@anthrotype waiting for clarification on this.

@m4rc1e That's a matter of adding the command somewhere. See how the other stuff is implemented.

**Comment by anthrotype** [comment]
@madig I had a quick look and it looks pretty good actually, especially that vttparser.py module for parsing TSI3 aka VTTTalk code. I'd like to see this merged into fonttools eventually :)

**Comment by madig** [comment]
Some day, some day I tell you. Then, when MS releases their VTT compiler, let's turn it into a Python wheel with wine bundled on Linux and macOS!

**Comment by anthrotype** [comment]
> when MS releases their VTT compiler, let's turn it into a Python wheel with wine bundled on Linux and macOS!

nah...

**Comment by m4rc1e** [comment]
I've solved my initial issue.

I now have a script sitting on my desktop called **nice_n_spicy.py**. It will copy TSI3 instructions from a hinted font to an unhinted font... It's way too dangerous to share. I'm praying I only need to do this once.

I agree with the above. This should really be done in vttlib and the code (apart from that whole type business ;-)) Nikolaus has provided is good.

**Comment by m4rc1e** [comment]
Closing this since we can just use vttLib which is now pip installable.
