### ISSUE TITLE
`gftools builder` hangs indefinitely

### ISSUE THREAD

**Issue by RickyDaMa** [googlefonts/gftools#911]
This was previously working on v0.9.52, but both releases since have this issue.

I'm afraid I'm not a ninja expert to debug the issue, but the indefinite hang is happening on `[0/3] buildVariable`.

Because it's ninja running Python programs from the commandline, I'm struggling to stick a debugger in and work out why I'm getting hangs with zero output / indication as to the problem. All I can say is that if I run `ninja` in my `sources/` directory (where the generated `build.ninja` is), it also hangs on the same step

If you have access to the project I'm using it with, you'll see the backlink below to be able to reproduce this

**Comment by simoncozens** [comment]
This is not a gftools-builder problem, even though it looks like one. Your fontmake job (buildVariable) is really taking a semi-infinite amount of time. More details in the other issue.
