### ISSUE TITLE
mannage-traffic-jam: expects a `info.pb` on a `ofl/font` dir

### ISSUE THREAD

**Issue by vv-monsalve** [googlefonts/gftools#920]
Running the commands:

- `gftools manage-traffic-jam --update-servers-only .`
- `gftools manage-traffic-jam .`

The reports the following error `FileNotFoundError: [Errno 2] No such file or directory: 'ofl/buenard/info.pb'`

It's unclear why it expects it to be an `info.pb` file on a `ofl/project` dir.

**Comment by vv-monsalve** [comment]
Marc solved this on [this commit](https://github.com/googlefonts/gftools/commit/f7db9db801d9f98ef25e65d5631cd98eae2aa30f). 

However, now the tool is failing to update the server status in the Traffic Jam Board. E.g. The `Jacquard 12 Charted` family is still listed as `In Sandbox` despite it was pushed to production last week.

@simoncozens, could you please have a look at this? :) 

**Traffic board**

<img width="1066" alt="Screen Shot 2024-04-16 at 16 21 10" src="https://github.com/googlefonts/gftools/assets/48698976/57dfb19b-6e1b-46a5-84e3-1a61233ebe7f">
<br><br>

**Catalog**

<img width="699" alt="Screen Shot 2024-04-16 at 16 22 59" src="https://github.com/googlefonts/gftools/assets/48698976/4fda598c-4d1c-4592-b43e-6dbab05c24b5">

**Comment by simoncozens** [comment]
Fixed in 1472d07; you will need to delete the cache file ".gf_traffic_jam_data.json" in your home directory. (`rm ~/.gf_traffic_jam_data.json`)

**Comment by vv-monsalve** [comment]
Excellent. Thank you.
