### ISSUE TITLE
Packager prefixes repository_url with "www", triggering FB check failure

### ISSUE THREAD

**Issue by n8willis** [googlefonts/gftools#923]
When running `gftools packager` on a new font, the autogenerated METADATA.pb inserts a boilerplate `repository_url` of

```
source {
  repository_url: "https://www.github.com/user/repo"
 # archive_url: "https://www.github.com/user/repo/family.zip"
```

The `www.` hostname component there means that the `repository_url` value clashes with the way that GitHub URLs are normally written (www-less): `https://github.com/user/repo` which, in turn, causes a FAIL from Fontbakery if somebody just replaces `user/repo` with the correct value.

It'd be better to use a boilerplate URL without the www., to avoid having users accidentally triggering that FAIL simply by editing the boilerplate.

**Comment by n8willis** [comment]
Actually, quick update: `www.github.com` is a 301 permanently redirected to `github.com`, so there's no reason to use the `www.` prefix at all; it should just be removed from the boilerplate.

( via the output of `curl -I -L https://www.github.com/` .)

**Comment by felipesanches** [comment]
thanks!
