### ISSUE TITLE
gftools-add-font.py: Not working with variable fonts

### ISSUE THREAD

**Issue by eliheuer** [googlefonts/gftools#93]
gftools-add-font.py works for static fonts, for the root directory of `gftools` I do the following:
```
python2 bin/gftools-add-font.py ~/Google/fonts/ofl/staatliches
```
And get the result:
```
Wrote /Users/Air/Google/fonts/ofl/font/DESCRIPTION.en_us.html
Wrote /Users/Air/Google/fonts/ofl/font/METADATA.pb
```

But when I run the same command from the same directory on a variable font, I get the following traceack:
```
Traceback (most recent call last):
  File "bin/gftools-add-font.py", line 267, in <module>
    app.run()
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/google/apputils/app.py", line 238, in run
    return _actual_start()
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/google/apputils/app.py", line 267, in _actual_start
    really_start()
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/google/apputils/app.py", line 220, in really_start
    sys.exit(main(argv))
  File "bin/gftools-add-font.py", line 253, in main
    metadata = _MakeMetadata(fontdir, is_new)
  File "bin/gftools-add-font.py", line 114, in _MakeMetadata
    file_family_style_weights = _FileFamilyStyleWeights(fontdir)
  File "bin/gftools-add-font.py", line 89, in _FileFamilyStyleWeights
    result = [fonts.FileFamilyStyleWeight(f) for f in files]
  File "/Users/Air/Demo/gftools/Lib/gftools/util/google_fonts.py", line 462, in FileFamilyStyleWeight
    sw = StyleWeight(m.group(2))
  File "/Users/Air/Demo/gftools/Lib/gftools/util/google_fonts.py", line 446, in StyleWeight
    return ('normal', _KNOWN_WEIGHTS[styleweight])
KeyError: 'VF'
```

**Comment by rsheeter** [comment]
update from internal, I believe we fixed this?

**Comment by nyshadhr9** [comment]
This is happening because google_fonts.py expects the font filenames to be in a certain format (Ex: FamilyName-Regular.ttf). I'm guessing the filename which caused the error was something like this: FamilyName-VF.ttf. Changing it to FamilyName-(Style).ttf where Style is one of [these](https://github.com/googlefonts/gftools/blob/94e1e9af533d5ccb14299a366528e8d6671489d4/Lib/gftools/util/google_fonts.py#L82) depending on the default weight of the VF, should fix the issue. Maybe we can document this somewhere, if not already there.

**Comment by rsheeter** [comment]
Suggest just making the error message better

**Comment by eliheuer** [comment]
Do variable fonts have a default style? Naming a variable font `FamilyName-(style).ttf` instead of `FamilyName-VF.ttf` seems like it could cause confusion in the future.

I will look into adding a check for `FamilyName-VF.ttf `

**Comment by eliheuer** [comment]
I don't have any strong opinions about this, I'm just putting my thoughts down. 

If we call the variable font `FamilyName-(default-style).ttf` the filename will be indistinguishable from a static regular style ttf. If the font is downloaded from fonts.google, will the downloaded font appear as `FamilyName-(default-style).ttf`?

This might cause confusion as it would seem only the one style has been downloaded.

**Comment by nyshadhr9** [comment]
Thanks Eli :)

There shouldn't be any confusion with static files, since we wouldn't have both static and VF for a family. Re Downloads, we plan to avoid that confusion either through a README file or changing the filename. 

As we make changes internally to add more support for VF, some of these things might change. Until then, I'd suggest not making any changes for this issue, since internally we rely on the filenames being in a certain format.

**Comment by eliheuer** [comment]
Ok, that sounds good. It seems like `FamilyName-Regular.ttf` works in most cases. I'll close this for now.

**Comment by eliheuer** [comment]
I think the confusion would be on the users end.

I will need to look into this more to better understand the issue.

**Comment by eliheuer** [comment]
@nyshadhr9 I'm trying this with a new variable font that was VTT hinted last week and I'm still having issues:

Here is the font I want to use: https://github.com/eliheuer/dosis-vf/blob/master/fonts/Dosis-VF_VTT.ttf

When I move this font file to the `google/font/ofl/dosis` directory I rename it `Dosis-Regular.ttf` as discussed above. But get the following output from running `python2 bin/gftools-add-font.py ~/Google/fonts/ofl/dosis`:

```

```

**Comment by davelab6** [comment]
The VF of Dosis should not be called Dosis-Regular.ttf because that is the
filename of the non-VF regular style.

I would expect

Dosis-Roman.ttf
Dosis-Italic.ttf

or

Dosis-Roman-VF.ttf
Dosis-Italic-VF.ttf

**Comment by nyshadhr9** [comment]
Dave, do you foresee any issues with the VF being named as Dosis-Regular.ttf.

Agreed, the static non-VF regular will have the same name but the filenames are never user except for in Directory downloads. There we intend to have a VF suffix to avoid any confusion. During onboarding we would either have a static version of the font or a VF, but not both. Hence there shouldn't be any clashes in the filenames.

**Comment by eliheuer** [comment]
I'm always in favor of accurately naming files. Things like this create institutional knowledge and complex documentation needs that make it difficult for people to contribute fonts to the Google Fonts project. I think Ideally it should be very easy for anyone to make a PR to Google Fonts if they want their font included. We should do everything we can to make the process as simple as possible.

If this issue isn't addressed now it will need to be in the future. Renaming the file to `Font-Regular.ttf` introduces friction into the pipeline because the font files will need to be renamed before a pull request.  

I think: `Dosis-Roman-VF.ttf`, `Dosis-Italic-VF.ttf`, `etc..` would be appropriate here. What do we need to do to make this work?

**Comment by eliheuer** [comment]
Here is a good example issue: https://github.com/google/fonts/issues/1455

Ideally add-font.py should be able to onboard something like this with minimal work.

**Comment by eliheuer** [comment]
PR https://github.com/googlefonts/gftools/pull/96 is working for me when Dosis is named `Dosis-Regular.ttf` and gives me the following METADATA.pb:
```
name: "Dosis"
designer: "UNKNOWN"
license: "OFL"
category: "SANS_SERIF"
date_added: "2018-11-06"
fonts {
  name: "Dosis"
  style: "normal"
  weight: 400
  filename: "Dosis-Regular.ttf"
  post_script_name: "Dosis-ExtraLight"
  full_name: "Dosis ExtraLight"
  copyright: "Copyright 2011 The Dosis Project Authors (https://github.com/impallari/Dosis)"
}
subsets: "latin"
subsets: "latin-ext"
subsets: "menu"
axes {
  tag: "wght"
  min_value: 200.0
  default_value: 200.0
  max_value: 800.0
}
```

**Comment by nyshadhr9** [comment]
The default value of the weight axis is 200, so the filename should be Dosis-ExtraLight.ttf.

**Comment by eliheuer** [comment]
Ok, I can do that, I think @m4rc1e is trying to merge this today, should we include this new style of `METADATA.pb` in the PR https://github.com/google/fonts/pull/1733 ?

@davelab6 I talked to @nyshadhr9 about this in person today and we thought a good temporary solution might be having `add-font.py` automatically rename the file. But could you make an internal Google issue about fixing this? It doesn't have to be urgent, but it seems like this will cause problems down the road.

**Comment by davelab6** [comment]
I don't think we should have any autofixing; we should have fixing scripts in gf-tools that the user is reminded about in an error message. 

I think `Family-Roman.ttf` is better than `Family-Style.ttf` for VFs, because it sub-communicates the file is a VF without explicitly labelling it, and allows a set of static fonts + VFs to be in the same directory (a) which `Family-Style.ttf` prevents and (b) which we may want the GF download ZIPs to do. 

> The default value of the weight axis is 200

Why is that not 400?

**Comment by eliheuer** [comment]
I have no idea why that happened, but I updated the font and METADATA to 400 in the PR: https://github.com/google/fonts/pull/1733

**Comment by m4rc1e** [comment]
> Why is that not 400?

Because its origin (default master) is the ExtraLight. There is no Regular master in the font. I suggest a revert.

**Comment by eliheuer** [comment]
I reverted the two commits that changed the default weight axis: https://github.com/google/fonts/pull/1733

**Comment by davelab6** [comment]
Origin and default are different things though?

**Comment by eliheuer** [comment]
Yeah. I'm starting to think dave is right. the `fvar` table header should look like this, correct?
```
  <fvar>

    <!-- Weight -->
    <Axis>
      <AxisTag>wght</AxisTag>
      <Flags>0x0</Flags>
      <MinValue>200.0</MinValue>
      <DefaultValue>400.0</DefaultValue>
      <MaxValue>800.0</MaxValue>
      <AxisNameID>256</AxisNameID>
    </Axis>
```

See the example table here: https://docs.microsoft.com/en-us/typography/opentype/spec/fvar

**Comment by eliheuer** [comment]
What, no Marc is right. The source file doesn't have a master at 400. 

from the Microsoft docs:
```
The default value interacts with the glyph and glyph variations tables in a particular way: the variation instance that has the default coordinate value for each axis will use glyph outlines as defined in the glyph table, without any variations from the glyph variations table applied. This instance is referred to as the default instance.
```

So if there are only masters at 200 and 800, should the `fvar` table look like this? 
```
  <fvar>

    <!-- Weight -->
    <Axis>
      <AxisTag>wght</AxisTag>
      <Flags>0x0</Flags>
      <MinValue>200.0</MinValue>
      <DefaultValue>200.0</DefaultValue>
      <MaxValue>800.0</MaxValue>
      <AxisNameID>256</AxisNameID>
    </Axis>
```

**Comment by thundernixon** [comment]
Reading a bit more on the GlyphsApp docs, Rainer justifies his assertion of why the default must be a source weight:

> **Default Appearance:** ... for desktop fonts, pick the Regular as origin, or whatever the user will expect as the ‘default appearance’ of your font family. If all else fails, this is the weight the user will still be able to use.
> 
> **File Size:** Picking a middle master will likely increase the number of your point deltas, and therefore, also increase the eventual file size. On a single-axis setup, it will likely double the number of deltas, if not more. In other words, for webfonts, it makes more sense to pick one of the masters in an extreme end of the design space, because you want to keep file sizes and load times down.

This leads me to two conclusions:
1. **We should keep the default value as a master** in case the font is used in a desktop app lacking VF support, where, presumably, it might not render at all if the default isn't at a source*
2. **We should not add a middle master** just to support a default in the middle if the outlines of the font do not depend on it. It would increase file size with no benefit to the design or the web.**

* I would want to test whether this is actually a risk, but I'm not sure how to. From a one-on-one conversation, it sounds like things were still working when @eliheuer set a middle default via TTX. However, I wonder whether it only works well on some platforms/apps, and might fail in others. How might we test this?

**On the web, a quick check shows that the font weight `400` is applied to VFs on the web, even if it's not set as the default. So, that seems to indicate that the "default" specified wght value doesn't matter for webfonts, anyway. 

https://codesandbox.io/s/o9ww5z57ry

![image](https://user-images.githubusercontent.com/7355414/48167035-77688b00-e2b8-11e8-96a2-237031cb05d8.png)


The above is the result of the following CSS:

```css
@font-face {
  font-family: "signika";
  src: url("Signika-VF-3_masters.ttf");
  font-weight: 300 700;
}

html,
h1,
p {
  font-family: "signika", monospace;
  font-size: 32px;
}
```

**Comment by thundernixon** [comment]
Thanks, @davelab6, I was really curious about it and wanted to see what I could find out. 

I definitely agree with you on this:

> `Family-Roman.ttf` is better than `Family-Style.ttf` for VFs, because it sub-communicates the file is a VF without explicitly labeling it, and allows a set of static fonts + VFs to be in the same directory (a) which `Family-Style.ttf` prevents and (b) which we may want the GF download ZIPs to do.

I know that we don't want to call out that VFs are a new technology, but I would say that even so, keeping `-var` or `VF` in the naming would likely be a user benefit.

There are still plenty of cases in which a static fonts are still important for people to download. I don't think anyone is debating this, but I do think that these scenarios show why it's important that the VF have clearly-different naming from static instances. A few that come to mind:
- Self-hosting web fonts and linking to fallback static font files ([browser support is still just 78%](https://caniuse.com/#search=variable))
- Self-hosting a web font for a site that uses only a single weight
- Some apps, such as Adobe InDesign, don't yet support VFs. This will likely change over time, but..
- Some printers don't properly render VFs. For instance, contour overlaps are rendered in white rather than in black. I could see this being much slower to change than app support.

Further, if a VF has a name like `Family-Thin.ttf`, isn't there a high likelihood that it might confuse file systems if people try to place them into the same folder as the static weights? It confuses my Mac:

![image](https://user-images.githubusercontent.com/7355414/48208716-6adc4500-e341-11e8-8aab-0fcfa3859f97.png)

If a business or designer is going to be using a font from Google Fonts for a brand or a project, they will need to have access to both variable and static files, and it shouldn't be confusing which is which.  

I don't know how much work it would take to support a clear naming structure, but from my perspective, it seems like a faily-critical aspect of providing variable fonts on the platform.

**Comment by m4rc1e** [comment]
> If a business or designer is going to be using a font from Google Fonts for a brand or a project, they will need to have access to both variable and static files

Why would you need both?

For [Markazi Text](https://fonts.google.com/specimen/Markazi+Text), we provide just the VF when downloading the family.

**Comment by eliheuer** [comment]
>I don't know how much work it would take to support a clear naming structure, but from my perspective, it seems like a fairly-critical aspect of providing variable fonts on the platform.

I said earlier in this thread that I don't have any strong opinions about this, but I have changed my mind. I suggest we should at least start the process needed to make the names for the fonts in incoming PRs as accurate as possible. It doesn't need to happen right away, but it would be nice to know it isn't something that will be put off indefinitely.

**Comment by thundernixon** [comment]
@m4rc1e they need both for the reasons I listed above, and likely others I can't think of right now. As Dave said: legacy systems.

As one concrete example, there's a great article on Medium about using Source Sans Variable in a conference website. 

https://medium.com/clear-left-thinking/how-to-use-variable-fonts-in-the-real-world-e6d73065a604

They specify a variable font with static fallbacks, with the following CSS:

```css
@font-face {
  font-family: 'SourceSans';
  src: url('source-sans-variable.woff2') format('woff2-variations'), /* var font*/
       url('source-sans-regular.woff2') format('woff2'); /* static fallback*/
  font-weight: 400; 
}
@font-face {
  font-family: 'SourceSans';
  src: url('source-sans-variable.woff2') format('woff2-variations'), /* var font*/
       url('source-sans-black.woff2') format('woff2'); /* static fallback*/
  font-weight: 900; 
}
```

Obviously, we don't expect most Google Fonts users to self-host fonts, but I don't think it should be unecessarily difficult or confusing to do so. If the variable font had a name with a style name included, I suspect that it would be confusing in this kind of use case.

**Comment by davelab6** [comment]
I have a strong conviction that we must keep the file naming of VFs and static fonts 'compatible' to allow them to exist within the same directory. 

The only VF in the main GF catalog is Markazi Text, which is named `ofl/markazitext/MarkaziText-Roman-VF.ttf`

**Comment by davelab6** [comment]
I also wonder that this repo needs updating like https://github.com/googlefonts/fontbakery/pull/2156/files

**Comment by eliheuer** [comment]
I updated https://github.com/google/fonts/pull/1743 to use `Orbitron-Roman.ttf` and that breaks `add-font.py`. I get the following: 

```
Traceback (most recent call last):
  File "bin/gftools-add-font.py", line 267, in <module>
    app.run()
  File "/Users/Air/Py/Venvs/Python2/lib/python2.7/site-packages/google/apputils/app.py", line 238, in run
    return _actual_start()
  File "/Users/Air/Py/Venvs/Python2/lib/python2.7/site-packages/google/apputils/app.py", line 267, in _actual_start
    really_start()
  File "/Users/Air/Py/Venvs/Python2/lib/python2.7/site-packages/google/apputils/app.py", line 220, in really_start
    sys.exit(main(argv))
  File "bin/gftools-add-font.py", line 253, in main
    metadata = _MakeMetadata(fontdir, is_new)
  File "bin/gftools-add-font.py", line 114, in _MakeMetadata
    file_family_style_weights = _FileFamilyStyleWeights(fontdir)
  File "bin/gftools-add-font.py", line 89, in _FileFamilyStyleWeights
    result = [fonts.FileFamilyStyleWeight(f) for f in files]
  File "/Users/Air/Py/Source/gftools/Lib/gftools/util/google_fonts.py", line 462, in FileFamilyStyleWeight
    sw = StyleWeight(m.group(2))
  File "/Users/Air/Py/Source/gftools/Lib/gftools/util/google_fonts.py", line 446, in StyleWeight
    return ('normal', _KNOWN_WEIGHTS[styleweight])
KeyError: 'Roman'
```

**Comment by thlinard** [comment]
> I have a strong conviction that we must keep the file naming of VFs and static fonts 'compatible' to allow them to exist within the same directory.
> 
> The only VF in the main GF catalog is Markazi Text, which is named `ofl/markazitext/MarkaziText-Roman-VF.ttf`

Indeed! https://github.com/google/fonts/issues/1666 btw.

**Comment by eliheuer** [comment]
Ok, I assigned this issue to me and will work on it in this branch: https://github.com/eliheuer/gftools/tree/add-vfont

**Comment by thundernixon** [comment]
As an update, add-font doesn't work with multi-axis fonts.

```
▶ gftools add-font /Users/stephennixon/type-repos/google-font-repos/fonts/ofl/inter

Traceback (most recent call last):
  File "/Users/stephennixon/type-repos/google-font-repos/inter/build/venv3/bin/gftools-add-font.py", line 269, in <module>
    app.run(main)
  File "/Users/stephennixon/type-repos/google-font-repos/inter/build/venv3/lib/python3.7/site-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/Users/stephennixon/type-repos/google-font-repos/inter/build/venv3/lib/python3.7/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "/Users/stephennixon/type-repos/google-font-repos/inter/build/venv3/bin/gftools-add-font.py", line 255, in main
    metadata = _MakeMetadata(fontdir, is_new)
  File "/Users/stephennixon/type-repos/google-font-repos/inter/build/venv3/bin/gftools-add-font.py", line 116, in _MakeMetadata
    file_family_style_weights = _FileFamilyStyleWeights(fontdir)
  File "/Users/stephennixon/type-repos/google-font-repos/inter/build/venv3/bin/gftools-add-font.py", line 91, in _FileFamilyStyleWeights
    result = [fonts.FileFamilyStyleWeight(f) for f in files]
  File "/Users/stephennixon/type-repos/google-font-repos/inter/build/venv3/bin/gftools-add-font.py", line 91, in <listcomp>
    result = [fonts.FileFamilyStyleWeight(f) for f in files]
  File "/Users/stephennixon/type-repos/google-font-repos/inter/build/venv3/lib/python3.7/site-packages/gftools/util/google_fonts.py", line 463, in FileFamilyStyleWeight
    raise ParseError('Could not parse %s' % filename)
gftools.util.google_fonts.ParseError: Could not parse /Users/stephennixon/type-repos/google-font-repos/fonts/ofl/inter/Inter[slnt,wght].ttf
```

**Comment by m4rc1e** [comment]
add-font now works with VFs with multiple axes so I'm going to close this.
