### ISSUE TITLE
[builder] "rename" operation removes intended wordspace in style name, in name IDs 1, 4, and 17

### ISSUE THREAD

**Issue by arrowtype** [googlefonts/gftools#931]
I’m working on building a font in which the designer set weight style names with spaces, like `Extra Light` and `Extra Bold`. This works with most the gfbuilder chain.

However, I’m also using a custom recipe to apply a "rename" operation after the build, so we can include the suffix "Variable" in the family name.

Unfortunately, this rename operation has the collateral damage of changing `Extra Light` to `ExtraLight`.

Without rename operation:

```xml
    <namerecord nameID="1" platformID="3" platEncID="1" langID="0x409">
      Familyname Extra Light
    </namerecord>
    <namerecord nameID="2" platformID="3" platEncID="1" langID="0x409">
      Regular
    </namerecord>
    <namerecord nameID="4" platformID="3" platEncID="1" langID="0x409">
      Familyname Extra Light
    </namerecord>
    <namerecord nameID="16" platformID="3" platEncID="1" langID="0x409">
      Familyname
    </namerecord>
    <namerecord nameID="17" platformID="3" platEncID="1" langID="0x409">
      Extra Light
    </namerecord>
```

With rename operation:

```xml
    <namerecord nameID="1" platformID="3" platEncID="1" langID="0x409">
      Familyname Variable ExtraLight
    </namerecord>
    <namerecord nameID="2" platformID="3" platEncID="1" langID="0x409">
      Regular
    </namerecord>
    <namerecord nameID="4" platformID="3" platEncID="1" langID="0x409">
      Familyname Variable ExtraLight
    </namerecord>
    <namerecord nameID="16" platformID="3" platEncID="1" langID="0x409">
      Familyname Variable
    </namerecord>
    <namerecord nameID="17" platformID="3" platEncID="1" langID="0x409">
      ExtraLight
    </namerecord>
```

This results in a mismatch of the font’s default instance name with its base name table info, which results in fontbakery fail of [invalid-default-instance-subfamily-name](https://github.com/fonttools/fontbakery/blob/4ca7c9e018a9623a1ee2eea2f036580e1fec8c64/Lib/fontbakery/checks/opentype/fvar.py#L430-L473).

Trying to understand what’s happening here... This name change seems to be because the current [rename_font()](https://github.com/googlefonts/gftools/blob/8aaa98113d7e0e2be441f9afc52098d67a48537e/Lib/gftools/fix.py#L320-L328) function pulls from [build_name_table() function](https://github.com/googlefonts/axisregistry/blob/00162cc6d4fc765bf6bf80f0f9894cb1db9367f5/Lib/axisregistry/__init__.py#L260) the GF Axis Registry, which results in concise code, but forces weight style names to have no spaces.

I happen to agree that PascalCase weight names are better than weight names that include a space, but plenty of designers take the opposite stance, and it’s not ideal that the gfbuilder enforces the former view in fonts that otherwise use the latter.

Or, am I misunderstanding, and might there be a custom recipe approach to keeping that space in the default style name?

Thanks so much for your time!

**Comment by simoncozens** [comment]
Try adding:

```
args: --just-family
```

to the rename operation.
