### ISSUE TITLE
TypeError: 'GSFont' object has no attribute '__getitem__'

### ISSUE THREAD

**Issue by weiweihuanghuang** [googlefonts/gftools#94]
Just tried to run 

`gftools fix-glyphs WorkSans-Upright.glyphs`
```
Traceback (most recent call last):
  File "/usr/local/bin/gftools-fix-glyphs.py", line 55, in <module>
    main()
  File "/usr/local/bin/gftools-fix-glyphs.py", line 39, in main
    print('Copyright: "{}"'.format(data["copyright"]))
TypeError: 'GSFont' object has no attribute '__getitem__'
```
Returned this error?

**Comment by m4rc1e** [comment]
This script is misleading and still appears to be a wip. It doesn't fix anything, https://github.com/googlefonts/gftools/blob/master/bin/gftools-fix-glyphs.py#L38-L43


There's a fix QA and fix script here (specific to GF), https://github.com/googlefonts/gf-glyphs-scripts.

**Comment by simoncozens** [comment]
I'm gonna remove it. -> #710
