### ISSUE TITLE
packager: update the font version in the title after updating a PR

### ISSUE THREAD

**Issue by vv-monsalve** [googlefonts/gftools#944]

**Comment by m4rc1e** [comment]
Thanks, sgtm.

**Comment by vv-monsalve** [comment]
The font version still needs to be updated after updating a PR.
A recent example is [HostGrotesk PR](https://github.com/google/fonts/pull/8247). I just manually updated the font version in the PR title.

Given that the title appears on the boards, having the correct version is key during PR revision and when creating push lists :)
