### ISSUE TITLE
packager: interferes with itself when rebase=true

### ISSUE THREAD

**Issue by simoncozens** [googlefonts/gftools#947]
I have

```
[pull]
rebase=true
```

in my `.gitconfig`. This is normally a good idea because it means that any local changes are applied to the state of the branch as it is *now*, rather than as it was when the changes were made. However, this doesn't work with the packager. When I run

```
% gftools-packager notosansadlamunjoined ~/others-repos/fonts --latest-release -p
```

the packager downloads the family, and updates the METADATA.pb and DESCRIPTION.en_us.html, which makes the working tree dirty. Next, it runs `git pull origin main:gftools_packager_... --force` to create the new branch. This fails with `[pull]rebase=true` because there are unstaged changes which blocks the rebase.

I'm not sure what the fix is - the obvious fix is that I change my git config. But I wonder if we could also just use `git branch` instead of `git pull main:newbranch`.

**Comment by m4rc1e** [comment]
Thanks Simon. @vv-monsalve this may be related to the rebase issue you encountered. I wasn't able to replicate this because my .gitconfig is

```
[user]
	name = Marc Foley
	email = m.foley.88@gmail.com
[core]
	editor = vi
[init]
	defaultBranch = main
[alias]
	co = checkout
	br = branch
	ci = commit
	st = status
```

**Comment by vv-monsalve** [comment]
My config files are way more simple than any of the above. After hearing this from you guys I think I'll make it smarter :D
