### ISSUE TITLE
gftools builder adds extra weights in fvar table

### ISSUE THREAD

**Issue by mrecord** [googlefonts/gftools#956]
I'm building a variable font with wght axis, values at `[200, 300, 400, 500, [NOT 600], 700]`. 

When I make a font using gftools builder + config.yaml file, the resulting variable font includes a fvar weight for `600 SemiBold`. 
(And then fontbakery complains that I don't have a stat value for wght:600)

Does gftools builder include all values in the wght range, even if they're not specified in the config.yaml or .designspace? 

I tried again with wght axis of `[100, 700]`, and the resulting fvar table shows `[100, 200, 300, 400, 500, 600, 700]`.

Is this a bug, or is there a reason gftools builder is adding un-specified values?

**Comment by simoncozens** [comment]
gftools-builder runs gftools-fix on the variable font, which runs a set of hotfixes to bring the VF up to Google Fonts' requirements; one of those requirements is a wght=600 Semibold instance. This isn't a bug; its how we need the fonts to be built.
