### ISSUE TITLE
Error with otf zones and ps autohint when AscenderHeight=CapsHeight

### ISSUE THREAD

**Issue by RosaWagner** [googlefonts/gftools#962]
Please tell me where to open issues related to postscript hinting if not here.

```
ERROR: In FDDict FDArray[0]. The top of zone AscenderHeight at 724 overlaps zone LcHeight with the bottom at 710.
```

Ascenders and Caps have the same height. I set up `CapHeight=710+14` and `AscenderHeight=710+0` to avoid overlapping.  That is what works with Glyphs in this very common case. It doesn't seem to be a good move to remove the AscenderHeight value. The autohinter should remove the duplicated zone if there is one. It is also a bit strange that the names of the zones are confused in the error message.

**Comment by simoncozens** [comment]
psautohint/otfautohint is part of https://github.com/adobe-type-tools/afdko
