### ISSUE TITLE
HTML reformatting issues 

### ISSUE THREAD

**Issue by emmamarichal** [googlefonts/gftools#967]
@m4rc1e, maybe you know?
cc @vv-monsalve 

Some spaces are added automatically after adding links or italic. 

<img width="191" alt="Screenshot 2024-05-30 at 16 11 21" src="https://github.com/googlefonts/gftools/assets/64773544/9adc95b3-0dce-4f8f-b6ed-6351706a439d">

<img width="172" alt="Screenshot 2024-05-30 at 11 43 22" src="https://github.com/googlefonts/gftools/assets/64773544/f874867a-873a-4df3-b0dd-5f76f4747532">

Can this be solved? It impacts all the Playwrite PRs.

**Example**

```
<p>
 Playwrite Polska appears in font menus with a two-letter country code ‘PL’,
 <i>
  Playwrite PL
 </i>
 , and features four styles: Thin, ExtraLight, Light, and Regular.
 <br/>
```

You can see a space between `PL` and `</i>`, that gives: _Playwrite_ , and features

**Comment by chrissimpkins** [comment]
Requires removal of the space following `PL`
