### ISSUE TITLE
pip install issue for py3 virtualenv: No matching distribution found for gftools

### ISSUE THREAD

**Issue by thundernixon** [googlefonts/gftools#97]
In trying to fix my `dsig` table, I needed to use `gftools fix-dsig`. To use that, I needed to add gftools to my current Python 3 virtual environment.

I followed the directions in the readme and tried to install via `pip install --upgrade gftools`. However, this gave me the error:

```
Could not find a version that satisfies the requirement gftools (from versions: )
No matching distribution found for gftools
```

...even immediately after upgrading pip. 

I eventually found that modules can be installed via pip [with a git URL](https://stackoverflow.com/questions/42987521/pip-could-not-find-a-version-no-matching-distribution-found), so I ran:

```
pip install "git+https://github.com/googlefonts/gftools"
```

...and it began to work fine.

I'm not quite sure whether I had made a mistake along the way, or whether this is a Python 2/3 transitional thing, and therefore something others might experience. In any case, `gftools fix-dsig --autofix` seems to be working fine, now.

If this isn't a gftools issue, please close this issue. If it's obvious what might have been the problem, or if it's not recommended to install from the git URL, I'd be grateful to find out. Thanks!

**Comment by eliheuer** [comment]
It just needs an updated push to PyPI. I think only Felipe has the credentials to do that ATM, but I'll try to get the ball rolling on this soon.

**Comment by thundernixon** [comment]
Hmm, in the latest version of the repo, `pip install "git+https://github.com/googlefonts/gftools"` no longer works as a workaround for this issue.

Even when installed in a completely-fresh, python3 virtual environment, I get the following error when trying to run `add-font`:

```
👨‍💻 gftools add-font --help                                 
------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/bin/gftools", line 4, in <module>
    __import__('pkg_resources').require('gftools==0.2.0')
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3191, in <module>
    @_call_aside
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3175, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3204, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'gftools==0.2.0' distribution was not found and is required by the application
```

**Comment by eliheuer** [comment]
I'm having this same problem from the above today.
