### ISSUE TITLE
[builder] Duplicate ital axis in STAT after new splitter

### ISSUE THREAD

**Issue by yanone** [googlefonts/gftools#976]
Please see [my fork](https://github.com/yanone/mona-sans) of Mona Sans which has an updated `config.yaml` (saves to `/googlefonts`, `ital` axis instead of `slnt`).

The new `ital` splitter works great, in some ways better than plain `varlib.instancer` in how it handles the `fvar` instances. 

But Mona Sans now shows two `ital` axes in STAT, which I assume is a bug.

Both Italic and Roman show a similar behaviour, except that the Italic says `Italic` in the first screenshot instead of `(Roman)`

![Bildschirmfoto 2024-06-06 um 16 10 06](https://github.com/googlefonts/gftools/assets/175386/33ceee3e-b05a-4ad9-8fa8-f9380e1eb199)
![Bildschirmfoto 2024-06-06 um 16 10 01](https://github.com/googlefonts/gftools/assets/175386/7b1686b4-7254-4696-9e87-eeae1e243cc9)

**Comment by simoncozens** [comment]
OK, it looks like `gftools-gen-stat` is adding the second STAT ital axis.

```
$ ttx -o - -t STAT googlefonts/variable/MonaSans-Italic\[wdth,wght\].ttf | grep Italic | grep Axis
Dumping "googlefonts/variable/MonaSans-Italic[wdth,wght].ttf" to "<stdout>"...
Dumping 'STAT' table...
        <AxisNameID value="265"/>  <!-- Italic -->
```

OK so far, but then...

```
$ gftools-gen-stat --src stat.yml googlefonts/variable/*ttf
Saving font to googlefonts/variable/MonaSans-Italic[wdth,wght].ttf.fix
Saving font to googlefonts/variable/MonaSans[wdth,wght].ttf.fix
$ noglob ttx -o - -t STAT googlefonts/variable/MonaSans-Italic[wdth,wght].ttf.fix | grep Italic | grep Axis
Dumping "googlefonts/variable/MonaSans-Italic[wdth,wght].ttf.fix" to "<stdout>"...
Dumping 'STAT' table...
        <AxisNameID value="268"/>  <!-- Italic -->
        <AxisNameID value="268"/>  <!-- Italic -->
```

**Comment by yanone** [comment]
Removing works indeed. Thank you.
