### ISSUE TITLE
bin/fix-vf-meta.py: NameError: global name 'os' is not defined

### ISSUE THREAD

**Issue by weiweihuanghuang** [googlefonts/gftools#98]
I tried to use this script on two VF.ttf running it like
`python gftools-fix-vf-meta.py WorkSans-VF.ttf WorkSans-Italic-VF.ttf`
```
Traceback (most recent call last):
  File "/gftools-fix-vf-meta.py", line 330, in <module>
    main()
  File "gftools-fix-vf-meta.py", line 318, in main
    ', '.join(map(os.path.basename, ttfonts))
NameError: global name 'os' is not defined
```

**Comment by m4rc1e** [comment]
I've just pushed a commit to #83 which will solve this. 

Could you send me the vf please?

The script thinks the families don't share the same name.

**Comment by weiweihuanghuang** [comment]
Original files:
[WS-VF.zip](https://github.com/googlefonts/gftools/files/2561067/WS-VF.zip)
Hey Marc, great to hear, here are the files. I realised actually as part my shell script I had been processing them both individually already with the script, now that i did it again without processing using the script I just had, these are the files:
[Archive2.zip](https://github.com/googlefonts/gftools/files/2561145/Archive2.zip) 
and the new error:
```
    from fontTools.ttLib.tables import otTablesos
ImportError: cannot import name otTablesos
```

**Comment by m4rc1e** [comment]
Thanks

That error isn't possible sir ;-) https://github.com/googlefonts/gftools/pull/83/files. I take it you've done some edits by hand?

**Comment by m4rc1e** [comment]
Today I'll update the script so it will work.

**Comment by weiweihuanghuang** [comment]
Yep, I've update my repo right now too
